#pragma once
#ifndef MIQT_QT_WEBKIT_GEN_QGRAPHICSWEBVIEW_H
#define MIQT_QT_WEBKIT_GEN_QGRAPHICSWEBVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QCloseEvent;
class QEvent;
class QFocusEvent;
class QGraphicsItem;
class QGraphicsLayoutItem;
class QGraphicsObject;
class QGraphicsSceneContextMenuEvent;
class QGraphicsSceneDragDropEvent;
class QGraphicsSceneHoverEvent;
class QGraphicsSceneMouseEvent;
class QGraphicsSceneMoveEvent;
class QGraphicsSceneResizeEvent;
class QGraphicsSceneWheelEvent;
class QGraphicsWebView;
class QGraphicsWidget;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QMetaObject;
class QNetworkRequest;
class QObject;
class QPainter;
class QPainterPath;
class QPointF;
class QRectF;
class QShowEvent;
class QSizeF;
class QStyleOption;
class QStyleOptionGraphicsItem;
class QUrl;
class QVariant;
class QWebHistory;
class QWebPage;
class QWebSettings;
class QWidget;
#else
typedef struct QAction QAction;
typedef struct QCloseEvent QCloseEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsLayoutItem QGraphicsLayoutItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneMoveEvent QGraphicsSceneMoveEvent;
typedef struct QGraphicsSceneResizeEvent QGraphicsSceneResizeEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsWebView QGraphicsWebView;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaObject QMetaObject;
typedef struct QNetworkRequest QNetworkRequest;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QShowEvent QShowEvent;
typedef struct QSizeF QSizeF;
typedef struct QStyleOption QStyleOption;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWebHistory QWebHistory;
typedef struct QWebPage QWebPage;
typedef struct QWebSettings QWebSettings;
typedef struct QWidget QWidget;
#endif

QGraphicsWebView* QGraphicsWebView_new();
QGraphicsWebView* QGraphicsWebView_new2(QGraphicsItem* parent);
void QGraphicsWebView_virtbase(QGraphicsWebView* src, QGraphicsWidget** outptr_QGraphicsWidget);
QMetaObject* QGraphicsWebView_MetaObject(const QGraphicsWebView* self);
void* QGraphicsWebView_Metacast(QGraphicsWebView* self, const char* param1);
struct miqt_string QGraphicsWebView_Tr(const char* s);
struct miqt_string QGraphicsWebView_TrUtf8(const char* s);
QWebPage* QGraphicsWebView_Page(const QGraphicsWebView* self);
void QGraphicsWebView_SetPage(QGraphicsWebView* self, QWebPage* page);
QUrl* QGraphicsWebView_Url(const QGraphicsWebView* self);
void QGraphicsWebView_SetUrl(QGraphicsWebView* self, QUrl* url);
struct miqt_string QGraphicsWebView_Title(const QGraphicsWebView* self);
QIcon* QGraphicsWebView_Icon(const QGraphicsWebView* self);
double QGraphicsWebView_ZoomFactor(const QGraphicsWebView* self);
void QGraphicsWebView_SetZoomFactor(QGraphicsWebView* self, double zoomFactor);
bool QGraphicsWebView_IsModified(const QGraphicsWebView* self);
void QGraphicsWebView_Load(QGraphicsWebView* self, QUrl* url);
void QGraphicsWebView_LoadWithRequest(QGraphicsWebView* self, QNetworkRequest* request);
void QGraphicsWebView_SetHtml(QGraphicsWebView* self, struct miqt_string html);
void QGraphicsWebView_SetContent(QGraphicsWebView* self, struct miqt_string data);
QWebHistory* QGraphicsWebView_History(const QGraphicsWebView* self);
QWebSettings* QGraphicsWebView_Settings(const QGraphicsWebView* self);
QAction* QGraphicsWebView_PageAction(const QGraphicsWebView* self, int action);
void QGraphicsWebView_TriggerPageAction(QGraphicsWebView* self, int action);
bool QGraphicsWebView_FindText(QGraphicsWebView* self, struct miqt_string subString);
bool QGraphicsWebView_ResizesToContents(const QGraphicsWebView* self);
void QGraphicsWebView_SetResizesToContents(QGraphicsWebView* self, bool enabled);
bool QGraphicsWebView_IsTiledBackingStoreFrozen(const QGraphicsWebView* self);
void QGraphicsWebView_SetTiledBackingStoreFrozen(QGraphicsWebView* self, bool frozen);
void QGraphicsWebView_SetGeometry(QGraphicsWebView* self, QRectF* rect);
void QGraphicsWebView_UpdateGeometry(QGraphicsWebView* self);
void QGraphicsWebView_Paint(QGraphicsWebView* self, QPainter* param1, QStyleOptionGraphicsItem* options, QWidget* widget);
QVariant* QGraphicsWebView_ItemChange(QGraphicsWebView* self, int change, QVariant* value);
bool QGraphicsWebView_Event(QGraphicsWebView* self, QEvent* param1);
QSizeF* QGraphicsWebView_SizeHint(const QGraphicsWebView* self, int which, QSizeF* constraint);
QVariant* QGraphicsWebView_InputMethodQuery(const QGraphicsWebView* self, int query);
int QGraphicsWebView_RenderHints(const QGraphicsWebView* self);
void QGraphicsWebView_SetRenderHints(QGraphicsWebView* self, int renderHints);
void QGraphicsWebView_SetRenderHint(QGraphicsWebView* self, int param1);
void QGraphicsWebView_Stop(QGraphicsWebView* self);
void QGraphicsWebView_Back(QGraphicsWebView* self);
void QGraphicsWebView_Forward(QGraphicsWebView* self);
void QGraphicsWebView_Reload(QGraphicsWebView* self);
void QGraphicsWebView_LoadStarted(QGraphicsWebView* self);
void QGraphicsWebView_connect_LoadStarted(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_LoadFinished(QGraphicsWebView* self, bool param1);
void QGraphicsWebView_connect_LoadFinished(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_LoadProgress(QGraphicsWebView* self, int progress);
void QGraphicsWebView_connect_LoadProgress(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_UrlChanged(QGraphicsWebView* self, QUrl* param1);
void QGraphicsWebView_connect_UrlChanged(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_TitleChanged(QGraphicsWebView* self, struct miqt_string param1);
void QGraphicsWebView_connect_TitleChanged(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_IconChanged(QGraphicsWebView* self);
void QGraphicsWebView_connect_IconChanged(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_StatusBarMessage(QGraphicsWebView* self, struct miqt_string message);
void QGraphicsWebView_connect_StatusBarMessage(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_LinkClicked(QGraphicsWebView* self, QUrl* param1);
void QGraphicsWebView_connect_LinkClicked(QGraphicsWebView* self, intptr_t slot);
void QGraphicsWebView_MousePressEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_MouseDoubleClickEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_MouseReleaseEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_MouseMoveEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_HoverMoveEvent(QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_HoverLeaveEvent(QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_WheelEvent(QGraphicsWebView* self, QGraphicsSceneWheelEvent* param1);
void QGraphicsWebView_KeyPressEvent(QGraphicsWebView* self, QKeyEvent* param1);
void QGraphicsWebView_KeyReleaseEvent(QGraphicsWebView* self, QKeyEvent* param1);
void QGraphicsWebView_ContextMenuEvent(QGraphicsWebView* self, QGraphicsSceneContextMenuEvent* param1);
void QGraphicsWebView_DragEnterEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_DragLeaveEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_DragMoveEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_DropEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_FocusInEvent(QGraphicsWebView* self, QFocusEvent* param1);
void QGraphicsWebView_FocusOutEvent(QGraphicsWebView* self, QFocusEvent* param1);
void QGraphicsWebView_InputMethodEvent(QGraphicsWebView* self, QInputMethodEvent* param1);
bool QGraphicsWebView_FocusNextPrevChild(QGraphicsWebView* self, bool next);
bool QGraphicsWebView_SceneEvent(QGraphicsWebView* self, QEvent* param1);
struct miqt_string QGraphicsWebView_Tr2(const char* s, const char* c);
struct miqt_string QGraphicsWebView_Tr3(const char* s, const char* c, int n);
struct miqt_string QGraphicsWebView_TrUtf82(const char* s, const char* c);
struct miqt_string QGraphicsWebView_TrUtf83(const char* s, const char* c, int n);
void QGraphicsWebView_Load2(QGraphicsWebView* self, QNetworkRequest* request, int operation);
void QGraphicsWebView_Load3(QGraphicsWebView* self, QNetworkRequest* request, int operation, struct miqt_string body);
void QGraphicsWebView_SetHtml2(QGraphicsWebView* self, struct miqt_string html, QUrl* baseUrl);
void QGraphicsWebView_SetContent2(QGraphicsWebView* self, struct miqt_string data, struct miqt_string mimeType);
void QGraphicsWebView_SetContent3(QGraphicsWebView* self, struct miqt_string data, struct miqt_string mimeType, QUrl* baseUrl);
void QGraphicsWebView_TriggerPageAction2(QGraphicsWebView* self, int action, bool checked);
bool QGraphicsWebView_FindText2(QGraphicsWebView* self, struct miqt_string subString, int options);
void QGraphicsWebView_SetRenderHint2(QGraphicsWebView* self, int param1, bool enabled);
void QGraphicsWebView_override_virtual_SetGeometry(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_SetGeometry(void* self, QRectF* rect);
void QGraphicsWebView_override_virtual_UpdateGeometry(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_UpdateGeometry(void* self);
void QGraphicsWebView_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_Paint(void* self, QPainter* param1, QStyleOptionGraphicsItem* options, QWidget* widget);
void QGraphicsWebView_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsWebView_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsWebView_override_virtual_Event(void* self, intptr_t slot);
bool QGraphicsWebView_virtualbase_Event(void* self, QEvent* param1);
void QGraphicsWebView_override_virtual_SizeHint(void* self, intptr_t slot);
QSizeF* QGraphicsWebView_virtualbase_SizeHint(const void* self, int which, QSizeF* constraint);
void QGraphicsWebView_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsWebView_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsWebView_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* param1);
void QGraphicsWebView_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_KeyPressEvent(void* self, QKeyEvent* param1);
void QGraphicsWebView_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* param1);
void QGraphicsWebView_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* param1);
void QGraphicsWebView_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_FocusInEvent(void* self, QFocusEvent* param1);
void QGraphicsWebView_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_FocusOutEvent(void* self, QFocusEvent* param1);
void QGraphicsWebView_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
void QGraphicsWebView_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QGraphicsWebView_virtualbase_FocusNextPrevChild(void* self, bool next);
void QGraphicsWebView_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsWebView_virtualbase_SceneEvent(void* self, QEvent* param1);
void QGraphicsWebView_override_virtual_GetContentsMargins(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_GetContentsMargins(const void* self, double* left, double* top, double* right, double* bottom);
void QGraphicsWebView_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsWebView_virtualbase_Type(const void* self);
void QGraphicsWebView_override_virtual_PaintWindowFrame(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_PaintWindowFrame(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsWebView_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsWebView_virtualbase_BoundingRect(const void* self);
void QGraphicsWebView_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsWebView_virtualbase_Shape(const void* self);
void QGraphicsWebView_override_virtual_InitStyleOption(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_InitStyleOption(const void* self, QStyleOption* option);
void QGraphicsWebView_override_virtual_PropertyChange(void* self, intptr_t slot);
QVariant* QGraphicsWebView_virtualbase_PropertyChange(void* self, struct miqt_string propertyName, QVariant* value);
void QGraphicsWebView_override_virtual_WindowFrameEvent(void* self, intptr_t slot);
bool QGraphicsWebView_virtualbase_WindowFrameEvent(void* self, QEvent* e);
void QGraphicsWebView_override_virtual_WindowFrameSectionAt(void* self, intptr_t slot);
int QGraphicsWebView_virtualbase_WindowFrameSectionAt(const void* self, QPointF* pos);
void QGraphicsWebView_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_ChangeEvent(void* self, QEvent* event);
void QGraphicsWebView_override_virtual_CloseEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_CloseEvent(void* self, QCloseEvent* event);
void QGraphicsWebView_override_virtual_HideEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_HideEvent(void* self, QHideEvent* event);
void QGraphicsWebView_override_virtual_MoveEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_MoveEvent(void* self, QGraphicsSceneMoveEvent* event);
void QGraphicsWebView_override_virtual_PolishEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_PolishEvent(void* self);
void QGraphicsWebView_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_ResizeEvent(void* self, QGraphicsSceneResizeEvent* event);
void QGraphicsWebView_override_virtual_ShowEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_ShowEvent(void* self, QShowEvent* event);
void QGraphicsWebView_override_virtual_GrabMouseEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_GrabMouseEvent(void* self, QEvent* event);
void QGraphicsWebView_override_virtual_UngrabMouseEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_UngrabMouseEvent(void* self, QEvent* event);
void QGraphicsWebView_override_virtual_GrabKeyboardEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_GrabKeyboardEvent(void* self, QEvent* event);
void QGraphicsWebView_override_virtual_UngrabKeyboardEvent(void* self, intptr_t slot);
void QGraphicsWebView_virtualbase_UngrabKeyboardEvent(void* self, QEvent* event);
void QGraphicsWebView_Delete(QGraphicsWebView* self, bool isSubclass);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
