#pragma once
#ifndef MIQT_QT6_SCXML_GEN_QSCXMLEXECUTABLECONTENT_H
#define MIQT_QT6_SCXML_GEN_QSCXMLEXECUTABLECONTENT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QScxmlExecutableContent__AssignmentInfo)
typedef QScxmlExecutableContent::AssignmentInfo QScxmlExecutableContent__AssignmentInfo;
#else
class QScxmlExecutableContent__AssignmentInfo;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QScxmlExecutableContent__EvaluatorInfo)
typedef QScxmlExecutableContent::EvaluatorInfo QScxmlExecutableContent__EvaluatorInfo;
#else
class QScxmlExecutableContent__EvaluatorInfo;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QScxmlExecutableContent__ForeachInfo)
typedef QScxmlExecutableContent::ForeachInfo QScxmlExecutableContent__ForeachInfo;
#else
class QScxmlExecutableContent__ForeachInfo;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QScxmlExecutableContent__InvokeInfo)
typedef QScxmlExecutableContent::InvokeInfo QScxmlExecutableContent__InvokeInfo;
#else
class QScxmlExecutableContent__InvokeInfo;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QScxmlExecutableContent__ParameterInfo)
typedef QScxmlExecutableContent::ParameterInfo QScxmlExecutableContent__ParameterInfo;
#else
class QScxmlExecutableContent__ParameterInfo;
#endif
#else
typedef struct QScxmlExecutableContent__AssignmentInfo QScxmlExecutableContent__AssignmentInfo;
typedef struct QScxmlExecutableContent__EvaluatorInfo QScxmlExecutableContent__EvaluatorInfo;
typedef struct QScxmlExecutableContent__ForeachInfo QScxmlExecutableContent__ForeachInfo;
typedef struct QScxmlExecutableContent__InvokeInfo QScxmlExecutableContent__InvokeInfo;
typedef struct QScxmlExecutableContent__ParameterInfo QScxmlExecutableContent__ParameterInfo;
#endif

int QScxmlExecutableContent__EvaluatorInfo_expr(const QScxmlExecutableContent__EvaluatorInfo* self);
void QScxmlExecutableContent__EvaluatorInfo_setExpr(QScxmlExecutableContent__EvaluatorInfo* self, int expr);
int QScxmlExecutableContent__EvaluatorInfo_context(const QScxmlExecutableContent__EvaluatorInfo* self);
void QScxmlExecutableContent__EvaluatorInfo_setContext(QScxmlExecutableContent__EvaluatorInfo* self, int context);

void QScxmlExecutableContent__EvaluatorInfo_delete(QScxmlExecutableContent__EvaluatorInfo* self);

int QScxmlExecutableContent__AssignmentInfo_dest(const QScxmlExecutableContent__AssignmentInfo* self);
void QScxmlExecutableContent__AssignmentInfo_setDest(QScxmlExecutableContent__AssignmentInfo* self, int dest);
int QScxmlExecutableContent__AssignmentInfo_expr(const QScxmlExecutableContent__AssignmentInfo* self);
void QScxmlExecutableContent__AssignmentInfo_setExpr(QScxmlExecutableContent__AssignmentInfo* self, int expr);
int QScxmlExecutableContent__AssignmentInfo_context(const QScxmlExecutableContent__AssignmentInfo* self);
void QScxmlExecutableContent__AssignmentInfo_setContext(QScxmlExecutableContent__AssignmentInfo* self, int context);

void QScxmlExecutableContent__AssignmentInfo_delete(QScxmlExecutableContent__AssignmentInfo* self);

int QScxmlExecutableContent__ForeachInfo_array(const QScxmlExecutableContent__ForeachInfo* self);
void QScxmlExecutableContent__ForeachInfo_setArray(QScxmlExecutableContent__ForeachInfo* self, int array);
int QScxmlExecutableContent__ForeachInfo_item(const QScxmlExecutableContent__ForeachInfo* self);
void QScxmlExecutableContent__ForeachInfo_setItem(QScxmlExecutableContent__ForeachInfo* self, int item);
int QScxmlExecutableContent__ForeachInfo_index(const QScxmlExecutableContent__ForeachInfo* self);
void QScxmlExecutableContent__ForeachInfo_setIndex(QScxmlExecutableContent__ForeachInfo* self, int index);
int QScxmlExecutableContent__ForeachInfo_context(const QScxmlExecutableContent__ForeachInfo* self);
void QScxmlExecutableContent__ForeachInfo_setContext(QScxmlExecutableContent__ForeachInfo* self, int context);

void QScxmlExecutableContent__ForeachInfo_delete(QScxmlExecutableContent__ForeachInfo* self);

int QScxmlExecutableContent__ParameterInfo_name(const QScxmlExecutableContent__ParameterInfo* self);
void QScxmlExecutableContent__ParameterInfo_setName(QScxmlExecutableContent__ParameterInfo* self, int name);
int QScxmlExecutableContent__ParameterInfo_expr(const QScxmlExecutableContent__ParameterInfo* self);
void QScxmlExecutableContent__ParameterInfo_setExpr(QScxmlExecutableContent__ParameterInfo* self, int expr);
int QScxmlExecutableContent__ParameterInfo_location(const QScxmlExecutableContent__ParameterInfo* self);
void QScxmlExecutableContent__ParameterInfo_setLocation(QScxmlExecutableContent__ParameterInfo* self, int location);

void QScxmlExecutableContent__ParameterInfo_delete(QScxmlExecutableContent__ParameterInfo* self);

int QScxmlExecutableContent__InvokeInfo_id(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setId(QScxmlExecutableContent__InvokeInfo* self, int id);
int QScxmlExecutableContent__InvokeInfo_prefix(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setPrefix(QScxmlExecutableContent__InvokeInfo* self, int prefix);
int QScxmlExecutableContent__InvokeInfo_location(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setLocation(QScxmlExecutableContent__InvokeInfo* self, int location);
int QScxmlExecutableContent__InvokeInfo_context(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setContext(QScxmlExecutableContent__InvokeInfo* self, int context);
int QScxmlExecutableContent__InvokeInfo_expr(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setExpr(QScxmlExecutableContent__InvokeInfo* self, int expr);
int QScxmlExecutableContent__InvokeInfo_finalize(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setFinalize(QScxmlExecutableContent__InvokeInfo* self, int finalize);
bool QScxmlExecutableContent__InvokeInfo_autoforward(const QScxmlExecutableContent__InvokeInfo* self);
void QScxmlExecutableContent__InvokeInfo_setAutoforward(QScxmlExecutableContent__InvokeInfo* self, bool autoforward);

void QScxmlExecutableContent__InvokeInfo_delete(QScxmlExecutableContent__InvokeInfo* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
