<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by miqt-lupdate. To update this file, run the 'miqt-lupdate' command below. -->
<!-- //go:generate miqt-lupdate -InFile "main.go" -OutFile "lupdate_en.ts" -Language "en_US" -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Main</name>
    <message>
        <location filename="main.go" line="96"/>
        <source>L&amp;anguage:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="97"/>
        <source>&amp;Up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="98"/>
        <source>&amp;Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="99"/>
        <source>&amp;Left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="100"/>
        <source>&amp;Right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="101"/>
        <source>E&amp;xit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="102"/>
        <source>&amp;File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.go" line="104"/>
        <source>Ctrl+Q</source>
        <comment>Quit</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
