#pragma once
#ifndef MIQT_QT_EXTRAS_QWT_GEN_QWT_PLOT_H
#define MIQT_QT_EXTRAS_QWT_GEN_QWT_PLOT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QActionEvent;
class QBrush;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFrame;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
class QwtAbstractLegend;
class QwtInterval;
class QwtLegendData;
class QwtPlot;
class QwtPlotDict;
class QwtPlotItem;
class QwtPlotLayout;
class QwtScaleDiv;
class QwtScaleDraw;
class QwtScaleEngine;
class QwtScaleWidget;
class QwtText;
class QwtTextLabel;
#else
typedef struct QActionEvent QActionEvent;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QwtAbstractLegend QwtAbstractLegend;
typedef struct QwtInterval QwtInterval;
typedef struct QwtLegendData QwtLegendData;
typedef struct QwtPlot QwtPlot;
typedef struct QwtPlotDict QwtPlotDict;
typedef struct QwtPlotItem QwtPlotItem;
typedef struct QwtPlotLayout QwtPlotLayout;
typedef struct QwtScaleDiv QwtScaleDiv;
typedef struct QwtScaleDraw QwtScaleDraw;
typedef struct QwtScaleEngine QwtScaleEngine;
typedef struct QwtScaleWidget QwtScaleWidget;
typedef struct QwtText QwtText;
typedef struct QwtTextLabel QwtTextLabel;
#endif

QwtPlot* QwtPlot_new(QWidget* param1);
QwtPlot* QwtPlot_new2();
QwtPlot* QwtPlot_new3(QwtText* title);
QwtPlot* QwtPlot_new4(QwtText* title, QWidget* param2);
void QwtPlot_virtbase(QwtPlot* src, QFrame** outptr_QFrame, QwtPlotDict** outptr_QwtPlotDict);
QMetaObject* QwtPlot_metaObject(const QwtPlot* self);
void* QwtPlot_metacast(QwtPlot* self, const char* param1);
struct miqt_string QwtPlot_tr(const char* s);
struct miqt_string QwtPlot_trUtf8(const char* s);
void QwtPlot_applyProperties(QwtPlot* self, struct miqt_string param1);
struct miqt_string QwtPlot_grabProperties(const QwtPlot* self);
void QwtPlot_setAutoReplot(QwtPlot* self);
bool QwtPlot_autoReplot(const QwtPlot* self);
void QwtPlot_setPlotLayout(QwtPlot* self, QwtPlotLayout* plotLayout);
QwtPlotLayout* QwtPlot_plotLayout(QwtPlot* self);
QwtPlotLayout* QwtPlot_plotLayout2(const QwtPlot* self);
void QwtPlot_setTitle(QwtPlot* self, struct miqt_string title);
void QwtPlot_setTitleWithTitle(QwtPlot* self, QwtText* title);
QwtText* QwtPlot_title(const QwtPlot* self);
QwtTextLabel* QwtPlot_titleLabel(QwtPlot* self);
QwtTextLabel* QwtPlot_titleLabel2(const QwtPlot* self);
void QwtPlot_setFooter(QwtPlot* self, struct miqt_string footer);
void QwtPlot_setFooterWithFooter(QwtPlot* self, QwtText* footer);
QwtText* QwtPlot_footer(const QwtPlot* self);
QwtTextLabel* QwtPlot_footerLabel(QwtPlot* self);
QwtTextLabel* QwtPlot_footerLabel2(const QwtPlot* self);
void QwtPlot_setCanvas(QwtPlot* self, QWidget* canvas);
QWidget* QwtPlot_canvas(QwtPlot* self);
QWidget* QwtPlot_canvas2(const QwtPlot* self);
void QwtPlot_setCanvasBackground(QwtPlot* self, QBrush* canvasBackground);
QBrush* QwtPlot_canvasBackground(const QwtPlot* self);
double QwtPlot_invTransform(const QwtPlot* self, int axisId, int pos);
double QwtPlot_transform(const QwtPlot* self, int axisId, double value);
QwtScaleEngine* QwtPlot_axisScaleEngine(QwtPlot* self, int axisId);
QwtScaleEngine* QwtPlot_axisScaleEngineWithAxisId(const QwtPlot* self, int axisId);
void QwtPlot_setAxisScaleEngine(QwtPlot* self, int axisId, QwtScaleEngine* param2);
void QwtPlot_setAxisAutoScale(QwtPlot* self, int axisId);
bool QwtPlot_axisAutoScale(const QwtPlot* self, int axisId);
void QwtPlot_enableAxis(QwtPlot* self, int axisId);
bool QwtPlot_axisEnabled(const QwtPlot* self, int axisId);
void QwtPlot_setAxisFont(QwtPlot* self, int axisId, QFont* param2);
QFont* QwtPlot_axisFont(const QwtPlot* self, int axisId);
void QwtPlot_setAxisScale(QwtPlot* self, int axisId, double min, double max);
void QwtPlot_setAxisScaleDiv(QwtPlot* self, int axisId, QwtScaleDiv* param2);
void QwtPlot_setAxisScaleDraw(QwtPlot* self, int axisId, QwtScaleDraw* param2);
double QwtPlot_axisStepSize(const QwtPlot* self, int axisId);
QwtInterval* QwtPlot_axisInterval(const QwtPlot* self, int axisId);
QwtScaleDiv* QwtPlot_axisScaleDiv(const QwtPlot* self, int axisId);
QwtScaleDraw* QwtPlot_axisScaleDraw(const QwtPlot* self, int axisId);
QwtScaleDraw* QwtPlot_axisScaleDrawWithAxisId(QwtPlot* self, int axisId);
QwtScaleWidget* QwtPlot_axisWidget(const QwtPlot* self, int axisId);
QwtScaleWidget* QwtPlot_axisWidgetWithAxisId(QwtPlot* self, int axisId);
void QwtPlot_setAxisLabelAlignment(QwtPlot* self, int axisId, int param2);
void QwtPlot_setAxisLabelRotation(QwtPlot* self, int axisId, double rotation);
void QwtPlot_setAxisTitle(QwtPlot* self, int axisId, struct miqt_string param2);
void QwtPlot_setAxisTitle2(QwtPlot* self, int axisId, QwtText* param2);
QwtText* QwtPlot_axisTitle(const QwtPlot* self, int axisId);
void QwtPlot_setAxisMaxMinor(QwtPlot* self, int axisId, int maxMinor);
int QwtPlot_axisMaxMinor(const QwtPlot* self, int axisId);
void QwtPlot_setAxisMaxMajor(QwtPlot* self, int axisId, int maxMajor);
int QwtPlot_axisMaxMajor(const QwtPlot* self, int axisId);
void QwtPlot_insertLegend(QwtPlot* self, QwtAbstractLegend* param1);
QwtAbstractLegend* QwtPlot_legend(QwtPlot* self);
QwtAbstractLegend* QwtPlot_legend2(const QwtPlot* self);
void QwtPlot_updateLegend(QwtPlot* self);
void QwtPlot_updateLegendWithQwtPlotItem(QwtPlot* self, QwtPlotItem* param1);
QSize* QwtPlot_sizeHint(const QwtPlot* self);
QSize* QwtPlot_minimumSizeHint(const QwtPlot* self);
void QwtPlot_updateLayout(QwtPlot* self);
void QwtPlot_drawCanvas(QwtPlot* self, QPainter* param1);
void QwtPlot_updateAxes(QwtPlot* self);
void QwtPlot_updateCanvasMargins(QwtPlot* self);
bool QwtPlot_event(QwtPlot* self, QEvent* param1);
bool QwtPlot_eventFilter(QwtPlot* self, QObject* param1, QEvent* param2);
QVariant* QwtPlot_itemToInfo(const QwtPlot* self, QwtPlotItem* param1);
QwtPlotItem* QwtPlot_infoToItem(const QwtPlot* self, QVariant* param1);
void QwtPlot_itemAttached(QwtPlot* self, QwtPlotItem* plotItem, bool on);
void QwtPlot_connect_itemAttached(QwtPlot* self, intptr_t slot);
void QwtPlot_legendDataChanged(QwtPlot* self, QVariant* itemInfo, struct miqt_array /* of QwtLegendData* */  data);
void QwtPlot_connect_legendDataChanged(QwtPlot* self, intptr_t slot);
void QwtPlot_replot(QwtPlot* self);
void QwtPlot_autoRefresh(QwtPlot* self);
void QwtPlot_resizeEvent(QwtPlot* self, QResizeEvent* e);
struct miqt_string QwtPlot_tr2(const char* s, const char* c);
struct miqt_string QwtPlot_tr3(const char* s, const char* c, int n);
struct miqt_string QwtPlot_trUtf82(const char* s, const char* c);
struct miqt_string QwtPlot_trUtf83(const char* s, const char* c, int n);
void QwtPlot_setAutoReplotWithAutoReplot(QwtPlot* self, bool autoReplot);
void QwtPlot_setAxisAutoScale2(QwtPlot* self, int axisId, bool on);
void QwtPlot_enableAxis2(QwtPlot* self, int axisId, bool tf);
void QwtPlot_setAxisScale2(QwtPlot* self, int axisId, double min, double max, double stepSize);
void QwtPlot_insertLegend2(QwtPlot* self, QwtAbstractLegend* param1, int param2);
void QwtPlot_insertLegend3(QwtPlot* self, QwtAbstractLegend* param1, int param2, double ratio);

bool QwtPlot_override_virtual_sizeHint(void* self, intptr_t slot);
QSize* QwtPlot_virtualbase_sizeHint(const void* self);
bool QwtPlot_override_virtual_minimumSizeHint(void* self, intptr_t slot);
QSize* QwtPlot_virtualbase_minimumSizeHint(const void* self);
bool QwtPlot_override_virtual_updateLayout(void* self, intptr_t slot);
void QwtPlot_virtualbase_updateLayout(void* self);
bool QwtPlot_override_virtual_drawCanvas(void* self, intptr_t slot);
void QwtPlot_virtualbase_drawCanvas(void* self, QPainter* param1);
bool QwtPlot_override_virtual_event(void* self, intptr_t slot);
bool QwtPlot_virtualbase_event(void* self, QEvent* param1);
bool QwtPlot_override_virtual_eventFilter(void* self, intptr_t slot);
bool QwtPlot_virtualbase_eventFilter(void* self, QObject* param1, QEvent* param2);
bool QwtPlot_override_virtual_itemToInfo(void* self, intptr_t slot);
QVariant* QwtPlot_virtualbase_itemToInfo(const void* self, QwtPlotItem* param1);
bool QwtPlot_override_virtual_infoToItem(void* self, intptr_t slot);
QwtPlotItem* QwtPlot_virtualbase_infoToItem(const void* self, QVariant* param1);
bool QwtPlot_override_virtual_replot(void* self, intptr_t slot);
void QwtPlot_virtualbase_replot(void* self);
bool QwtPlot_override_virtual_resizeEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_resizeEvent(void* self, QResizeEvent* e);
bool QwtPlot_override_virtual_paintEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_paintEvent(void* self, QPaintEvent* param1);
bool QwtPlot_override_virtual_changeEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_changeEvent(void* self, QEvent* param1);
bool QwtPlot_override_virtual_devType(void* self, intptr_t slot);
int QwtPlot_virtualbase_devType(const void* self);
bool QwtPlot_override_virtual_setVisible(void* self, intptr_t slot);
void QwtPlot_virtualbase_setVisible(void* self, bool visible);
bool QwtPlot_override_virtual_heightForWidth(void* self, intptr_t slot);
int QwtPlot_virtualbase_heightForWidth(const void* self, int param1);
bool QwtPlot_override_virtual_hasHeightForWidth(void* self, intptr_t slot);
bool QwtPlot_virtualbase_hasHeightForWidth(const void* self);
bool QwtPlot_override_virtual_paintEngine(void* self, intptr_t slot);
QPaintEngine* QwtPlot_virtualbase_paintEngine(const void* self);
bool QwtPlot_override_virtual_mousePressEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
bool QwtPlot_override_virtual_mouseReleaseEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
bool QwtPlot_override_virtual_mouseDoubleClickEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QwtPlot_override_virtual_mouseMoveEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
bool QwtPlot_override_virtual_wheelEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_wheelEvent(void* self, QWheelEvent* event);
bool QwtPlot_override_virtual_keyPressEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
bool QwtPlot_override_virtual_keyReleaseEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
bool QwtPlot_override_virtual_focusInEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_focusInEvent(void* self, QFocusEvent* event);
bool QwtPlot_override_virtual_focusOutEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
bool QwtPlot_override_virtual_enterEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_enterEvent(void* self, QEvent* event);
bool QwtPlot_override_virtual_leaveEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_leaveEvent(void* self, QEvent* event);
bool QwtPlot_override_virtual_moveEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_moveEvent(void* self, QMoveEvent* event);
bool QwtPlot_override_virtual_closeEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_closeEvent(void* self, QCloseEvent* event);
bool QwtPlot_override_virtual_contextMenuEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* event);
bool QwtPlot_override_virtual_tabletEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_tabletEvent(void* self, QTabletEvent* event);
bool QwtPlot_override_virtual_actionEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_actionEvent(void* self, QActionEvent* event);
bool QwtPlot_override_virtual_dragEnterEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
bool QwtPlot_override_virtual_dragMoveEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
bool QwtPlot_override_virtual_dragLeaveEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
bool QwtPlot_override_virtual_dropEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_dropEvent(void* self, QDropEvent* event);
bool QwtPlot_override_virtual_showEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_showEvent(void* self, QShowEvent* event);
bool QwtPlot_override_virtual_hideEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QwtPlot_override_virtual_nativeEvent(void* self, intptr_t slot);
bool QwtPlot_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
bool QwtPlot_override_virtual_metric(void* self, intptr_t slot);
int QwtPlot_virtualbase_metric(const void* self, int param1);
bool QwtPlot_override_virtual_initPainter(void* self, intptr_t slot);
void QwtPlot_virtualbase_initPainter(const void* self, QPainter* painter);
bool QwtPlot_override_virtual_redirected(void* self, intptr_t slot);
QPaintDevice* QwtPlot_virtualbase_redirected(const void* self, QPoint* offset);
bool QwtPlot_override_virtual_sharedPainter(void* self, intptr_t slot);
QPainter* QwtPlot_virtualbase_sharedPainter(const void* self);
bool QwtPlot_override_virtual_inputMethodEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QwtPlot_override_virtual_inputMethodQuery(void* self, intptr_t slot);
QVariant* QwtPlot_virtualbase_inputMethodQuery(const void* self, int param1);
bool QwtPlot_override_virtual_focusNextPrevChild(void* self, intptr_t slot);
bool QwtPlot_virtualbase_focusNextPrevChild(void* self, bool next);
bool QwtPlot_override_virtual_timerEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_timerEvent(void* self, QTimerEvent* event);
bool QwtPlot_override_virtual_childEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_childEvent(void* self, QChildEvent* event);
bool QwtPlot_override_virtual_customEvent(void* self, intptr_t slot);
void QwtPlot_virtualbase_customEvent(void* self, QEvent* event);
bool QwtPlot_override_virtual_connectNotify(void* self, intptr_t slot);
void QwtPlot_virtualbase_connectNotify(void* self, QMetaMethod* signal);
bool QwtPlot_override_virtual_disconnectNotify(void* self, intptr_t slot);
void QwtPlot_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);

void QwtPlot_protectedbase_drawFrame(bool* _dynamic_cast_ok, void* self, QPainter* param1);
void QwtPlot_protectedbase_initStyleOption(bool* _dynamic_cast_ok, const void* self, QStyleOptionFrame* option);
void QwtPlot_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QwtPlot_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QwtPlot_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QwtPlot_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QwtPlot_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QwtPlot_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QwtPlot_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QwtPlot_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QwtPlot_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
void QwtPlot_protectedbase_insertItem(bool* _dynamic_cast_ok, void* self, QwtPlotItem* param1);
void QwtPlot_protectedbase_removeItem(bool* _dynamic_cast_ok, void* self, QwtPlotItem* param1);

void QwtPlot_delete(QwtPlot* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
