#pragma once
#ifndef MIQT_QT6_GEN_QCOMBOBOX_H
#define MIQT_QT6_GEN_QCOMBOBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemModel;
class QAbstractItemView;
class QActionEvent;
class QCloseEvent;
class QComboBox;
class QCompleter;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QLineEdit;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionComboBox;
class QTabletEvent;
class QValidator;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QActionEvent QActionEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QCompleter QCompleter;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QValidator QValidator;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QComboBox* QComboBox_new(QWidget* parent);
QComboBox* QComboBox_new2();
void QComboBox_virtbase(QComboBox* src, QWidget** outptr_QWidget);
QMetaObject* QComboBox_MetaObject(const QComboBox* self);
void* QComboBox_Metacast(QComboBox* self, const char* param1);
struct miqt_string QComboBox_Tr(const char* s);
int QComboBox_MaxVisibleItems(const QComboBox* self);
void QComboBox_SetMaxVisibleItems(QComboBox* self, int maxItems);
int QComboBox_Count(const QComboBox* self);
void QComboBox_SetMaxCount(QComboBox* self, int max);
int QComboBox_MaxCount(const QComboBox* self);
bool QComboBox_DuplicatesEnabled(const QComboBox* self);
void QComboBox_SetDuplicatesEnabled(QComboBox* self, bool enable);
void QComboBox_SetFrame(QComboBox* self, bool frame);
bool QComboBox_HasFrame(const QComboBox* self);
int QComboBox_FindText(const QComboBox* self, struct miqt_string text);
int QComboBox_FindData(const QComboBox* self, QVariant* data);
int QComboBox_InsertPolicy(const QComboBox* self);
void QComboBox_SetInsertPolicy(QComboBox* self, int policy);
int QComboBox_SizeAdjustPolicy(const QComboBox* self);
void QComboBox_SetSizeAdjustPolicy(QComboBox* self, int policy);
int QComboBox_MinimumContentsLength(const QComboBox* self);
void QComboBox_SetMinimumContentsLength(QComboBox* self, int characters);
QSize* QComboBox_IconSize(const QComboBox* self);
void QComboBox_SetIconSize(QComboBox* self, QSize* size);
void QComboBox_SetPlaceholderText(QComboBox* self, struct miqt_string placeholderText);
struct miqt_string QComboBox_PlaceholderText(const QComboBox* self);
bool QComboBox_IsEditable(const QComboBox* self);
void QComboBox_SetEditable(QComboBox* self, bool editable);
void QComboBox_SetLineEdit(QComboBox* self, QLineEdit* edit);
QLineEdit* QComboBox_LineEdit(const QComboBox* self);
void QComboBox_SetValidator(QComboBox* self, QValidator* v);
QValidator* QComboBox_Validator(const QComboBox* self);
void QComboBox_SetCompleter(QComboBox* self, QCompleter* c);
QCompleter* QComboBox_Completer(const QComboBox* self);
QAbstractItemDelegate* QComboBox_ItemDelegate(const QComboBox* self);
void QComboBox_SetItemDelegate(QComboBox* self, QAbstractItemDelegate* delegate);
QAbstractItemModel* QComboBox_Model(const QComboBox* self);
void QComboBox_SetModel(QComboBox* self, QAbstractItemModel* model);
QModelIndex* QComboBox_RootModelIndex(const QComboBox* self);
void QComboBox_SetRootModelIndex(QComboBox* self, QModelIndex* index);
int QComboBox_ModelColumn(const QComboBox* self);
void QComboBox_SetModelColumn(QComboBox* self, int visibleColumn);
int QComboBox_CurrentIndex(const QComboBox* self);
struct miqt_string QComboBox_CurrentText(const QComboBox* self);
QVariant* QComboBox_CurrentData(const QComboBox* self);
struct miqt_string QComboBox_ItemText(const QComboBox* self, int index);
QIcon* QComboBox_ItemIcon(const QComboBox* self, int index);
QVariant* QComboBox_ItemData(const QComboBox* self, int index);
void QComboBox_AddItem(QComboBox* self, struct miqt_string text);
void QComboBox_AddItem2(QComboBox* self, QIcon* icon, struct miqt_string text);
void QComboBox_AddItems(QComboBox* self, struct miqt_array /* of struct miqt_string */  texts);
void QComboBox_InsertItem(QComboBox* self, int index, struct miqt_string text);
void QComboBox_InsertItem2(QComboBox* self, int index, QIcon* icon, struct miqt_string text);
void QComboBox_InsertItems(QComboBox* self, int index, struct miqt_array /* of struct miqt_string */  texts);
void QComboBox_InsertSeparator(QComboBox* self, int index);
void QComboBox_RemoveItem(QComboBox* self, int index);
void QComboBox_SetItemText(QComboBox* self, int index, struct miqt_string text);
void QComboBox_SetItemIcon(QComboBox* self, int index, QIcon* icon);
void QComboBox_SetItemData(QComboBox* self, int index, QVariant* value);
QAbstractItemView* QComboBox_View(const QComboBox* self);
void QComboBox_SetView(QComboBox* self, QAbstractItemView* itemView);
QSize* QComboBox_SizeHint(const QComboBox* self);
QSize* QComboBox_MinimumSizeHint(const QComboBox* self);
void QComboBox_ShowPopup(QComboBox* self);
void QComboBox_HidePopup(QComboBox* self);
bool QComboBox_Event(QComboBox* self, QEvent* event);
QVariant* QComboBox_InputMethodQuery(const QComboBox* self, int param1);
QVariant* QComboBox_InputMethodQuery2(const QComboBox* self, int query, QVariant* argument);
void QComboBox_Clear(QComboBox* self);
void QComboBox_ClearEditText(QComboBox* self);
void QComboBox_SetEditText(QComboBox* self, struct miqt_string text);
void QComboBox_SetCurrentIndex(QComboBox* self, int index);
void QComboBox_SetCurrentText(QComboBox* self, struct miqt_string text);
void QComboBox_EditTextChanged(QComboBox* self, struct miqt_string param1);
void QComboBox_connect_EditTextChanged(QComboBox* self, intptr_t slot);
void QComboBox_Activated(QComboBox* self, int index);
void QComboBox_connect_Activated(QComboBox* self, intptr_t slot);
void QComboBox_TextActivated(QComboBox* self, struct miqt_string param1);
void QComboBox_connect_TextActivated(QComboBox* self, intptr_t slot);
void QComboBox_Highlighted(QComboBox* self, int index);
void QComboBox_connect_Highlighted(QComboBox* self, intptr_t slot);
void QComboBox_TextHighlighted(QComboBox* self, struct miqt_string param1);
void QComboBox_connect_TextHighlighted(QComboBox* self, intptr_t slot);
void QComboBox_CurrentIndexChanged(QComboBox* self, int index);
void QComboBox_connect_CurrentIndexChanged(QComboBox* self, intptr_t slot);
void QComboBox_CurrentTextChanged(QComboBox* self, struct miqt_string param1);
void QComboBox_connect_CurrentTextChanged(QComboBox* self, intptr_t slot);
void QComboBox_FocusInEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_FocusOutEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_ChangeEvent(QComboBox* self, QEvent* e);
void QComboBox_ResizeEvent(QComboBox* self, QResizeEvent* e);
void QComboBox_PaintEvent(QComboBox* self, QPaintEvent* e);
void QComboBox_ShowEvent(QComboBox* self, QShowEvent* e);
void QComboBox_HideEvent(QComboBox* self, QHideEvent* e);
void QComboBox_MousePressEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_MouseReleaseEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_KeyPressEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_KeyReleaseEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_WheelEvent(QComboBox* self, QWheelEvent* e);
void QComboBox_ContextMenuEvent(QComboBox* self, QContextMenuEvent* e);
void QComboBox_InputMethodEvent(QComboBox* self, QInputMethodEvent* param1);
void QComboBox_InitStyleOption(const QComboBox* self, QStyleOptionComboBox* option);
struct miqt_string QComboBox_Tr2(const char* s, const char* c);
struct miqt_string QComboBox_Tr3(const char* s, const char* c, int n);
int QComboBox_FindText2(const QComboBox* self, struct miqt_string text, int flags);
int QComboBox_FindData2(const QComboBox* self, QVariant* data, int role);
int QComboBox_FindData3(const QComboBox* self, QVariant* data, int role, int flags);
QVariant* QComboBox_CurrentData1(const QComboBox* self, int role);
QVariant* QComboBox_ItemData2(const QComboBox* self, int index, int role);
void QComboBox_AddItem22(QComboBox* self, struct miqt_string text, QVariant* userData);
void QComboBox_AddItem3(QComboBox* self, QIcon* icon, struct miqt_string text, QVariant* userData);
void QComboBox_InsertItem3(QComboBox* self, int index, struct miqt_string text, QVariant* userData);
void QComboBox_InsertItem4(QComboBox* self, int index, QIcon* icon, struct miqt_string text, QVariant* userData);
void QComboBox_SetItemData3(QComboBox* self, int index, QVariant* value, int role);
bool QComboBox_override_virtual_SetModel(void* self, intptr_t slot);
void QComboBox_virtualbase_SetModel(void* self, QAbstractItemModel* model);
bool QComboBox_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QComboBox_virtualbase_SizeHint(const void* self);
bool QComboBox_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QComboBox_virtualbase_MinimumSizeHint(const void* self);
bool QComboBox_override_virtual_ShowPopup(void* self, intptr_t slot);
void QComboBox_virtualbase_ShowPopup(void* self);
bool QComboBox_override_virtual_HidePopup(void* self, intptr_t slot);
void QComboBox_virtualbase_HidePopup(void* self);
bool QComboBox_override_virtual_Event(void* self, intptr_t slot);
bool QComboBox_virtualbase_Event(void* self, QEvent* event);
bool QComboBox_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QComboBox_virtualbase_InputMethodQuery(const void* self, int param1);
bool QComboBox_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_FocusInEvent(void* self, QFocusEvent* e);
bool QComboBox_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_FocusOutEvent(void* self, QFocusEvent* e);
bool QComboBox_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_ChangeEvent(void* self, QEvent* e);
bool QComboBox_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_ResizeEvent(void* self, QResizeEvent* e);
bool QComboBox_override_virtual_PaintEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_PaintEvent(void* self, QPaintEvent* e);
bool QComboBox_override_virtual_ShowEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_ShowEvent(void* self, QShowEvent* e);
bool QComboBox_override_virtual_HideEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_HideEvent(void* self, QHideEvent* e);
bool QComboBox_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_MousePressEvent(void* self, QMouseEvent* e);
bool QComboBox_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* e);
bool QComboBox_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_KeyPressEvent(void* self, QKeyEvent* e);
bool QComboBox_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* e);
bool QComboBox_override_virtual_WheelEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_WheelEvent(void* self, QWheelEvent* e);
bool QComboBox_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* e);
bool QComboBox_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
bool QComboBox_override_virtual_InitStyleOption(void* self, intptr_t slot);
void QComboBox_virtualbase_InitStyleOption(const void* self, QStyleOptionComboBox* option);
bool QComboBox_override_virtual_DevType(void* self, intptr_t slot);
int QComboBox_virtualbase_DevType(const void* self);
bool QComboBox_override_virtual_SetVisible(void* self, intptr_t slot);
void QComboBox_virtualbase_SetVisible(void* self, bool visible);
bool QComboBox_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QComboBox_virtualbase_HeightForWidth(const void* self, int param1);
bool QComboBox_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QComboBox_virtualbase_HasHeightForWidth(const void* self);
bool QComboBox_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QComboBox_virtualbase_PaintEngine(const void* self);
bool QComboBox_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QComboBox_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
bool QComboBox_override_virtual_EnterEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_EnterEvent(void* self, QEnterEvent* event);
bool QComboBox_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_LeaveEvent(void* self, QEvent* event);
bool QComboBox_override_virtual_MoveEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_MoveEvent(void* self, QMoveEvent* event);
bool QComboBox_override_virtual_CloseEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_CloseEvent(void* self, QCloseEvent* event);
bool QComboBox_override_virtual_TabletEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_TabletEvent(void* self, QTabletEvent* event);
bool QComboBox_override_virtual_ActionEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_ActionEvent(void* self, QActionEvent* event);
bool QComboBox_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
bool QComboBox_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
bool QComboBox_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
bool QComboBox_override_virtual_DropEvent(void* self, intptr_t slot);
void QComboBox_virtualbase_DropEvent(void* self, QDropEvent* event);
bool QComboBox_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QComboBox_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
bool QComboBox_override_virtual_Metric(void* self, intptr_t slot);
int QComboBox_virtualbase_Metric(const void* self, int param1);
bool QComboBox_override_virtual_InitPainter(void* self, intptr_t slot);
void QComboBox_virtualbase_InitPainter(const void* self, QPainter* painter);
bool QComboBox_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QComboBox_virtualbase_Redirected(const void* self, QPoint* offset);
bool QComboBox_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QComboBox_virtualbase_SharedPainter(const void* self);
bool QComboBox_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QComboBox_virtualbase_FocusNextPrevChild(void* self, bool next);
void QComboBox_Delete(QComboBox* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
