#pragma once
#ifndef MIQT_QT6_GEN_QTREEVIEW_H
#define MIQT_QT6_GEN_QTREEVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHeaderView;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QObject;
class QPaintDevice;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QSize;
class QStyleOptionViewItem;
class QTimerEvent;
class QTreeView;
class QVariant;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHeaderView QHeaderView;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeView QTreeView;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

QTreeView* QTreeView_new(QWidget* parent);
QTreeView* QTreeView_new2();
void QTreeView_virtbase(QTreeView* src, QAbstractItemView** outptr_QAbstractItemView);
QMetaObject* QTreeView_MetaObject(const QTreeView* self);
void* QTreeView_Metacast(QTreeView* self, const char* param1);
struct miqt_string QTreeView_Tr(const char* s);
void QTreeView_SetModel(QTreeView* self, QAbstractItemModel* model);
void QTreeView_SetRootIndex(QTreeView* self, QModelIndex* index);
void QTreeView_SetSelectionModel(QTreeView* self, QItemSelectionModel* selectionModel);
QHeaderView* QTreeView_Header(const QTreeView* self);
void QTreeView_SetHeader(QTreeView* self, QHeaderView* header);
int QTreeView_AutoExpandDelay(const QTreeView* self);
void QTreeView_SetAutoExpandDelay(QTreeView* self, int delay);
int QTreeView_Indentation(const QTreeView* self);
void QTreeView_SetIndentation(QTreeView* self, int i);
void QTreeView_ResetIndentation(QTreeView* self);
bool QTreeView_RootIsDecorated(const QTreeView* self);
void QTreeView_SetRootIsDecorated(QTreeView* self, bool show);
bool QTreeView_UniformRowHeights(const QTreeView* self);
void QTreeView_SetUniformRowHeights(QTreeView* self, bool uniform);
bool QTreeView_ItemsExpandable(const QTreeView* self);
void QTreeView_SetItemsExpandable(QTreeView* self, bool enable);
bool QTreeView_ExpandsOnDoubleClick(const QTreeView* self);
void QTreeView_SetExpandsOnDoubleClick(QTreeView* self, bool enable);
int QTreeView_ColumnViewportPosition(const QTreeView* self, int column);
int QTreeView_ColumnWidth(const QTreeView* self, int column);
void QTreeView_SetColumnWidth(QTreeView* self, int column, int width);
int QTreeView_ColumnAt(const QTreeView* self, int x);
bool QTreeView_IsColumnHidden(const QTreeView* self, int column);
void QTreeView_SetColumnHidden(QTreeView* self, int column, bool hide);
bool QTreeView_IsHeaderHidden(const QTreeView* self);
void QTreeView_SetHeaderHidden(QTreeView* self, bool hide);
bool QTreeView_IsRowHidden(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_SetRowHidden(QTreeView* self, int row, QModelIndex* parent, bool hide);
bool QTreeView_IsFirstColumnSpanned(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_SetFirstColumnSpanned(QTreeView* self, int row, QModelIndex* parent, bool span);
bool QTreeView_IsExpanded(const QTreeView* self, QModelIndex* index);
void QTreeView_SetExpanded(QTreeView* self, QModelIndex* index, bool expand);
void QTreeView_SetSortingEnabled(QTreeView* self, bool enable);
bool QTreeView_IsSortingEnabled(const QTreeView* self);
void QTreeView_SetAnimated(QTreeView* self, bool enable);
bool QTreeView_IsAnimated(const QTreeView* self);
void QTreeView_SetAllColumnsShowFocus(QTreeView* self, bool enable);
bool QTreeView_AllColumnsShowFocus(const QTreeView* self);
void QTreeView_SetWordWrap(QTreeView* self, bool on);
bool QTreeView_WordWrap(const QTreeView* self);
void QTreeView_SetTreePosition(QTreeView* self, int logicalIndex);
int QTreeView_TreePosition(const QTreeView* self);
void QTreeView_KeyboardSearch(QTreeView* self, struct miqt_string search);
QRect* QTreeView_VisualRect(const QTreeView* self, QModelIndex* index);
void QTreeView_ScrollTo(QTreeView* self, QModelIndex* index, int hint);
QModelIndex* QTreeView_IndexAt(const QTreeView* self, QPoint* p);
QModelIndex* QTreeView_IndexAbove(const QTreeView* self, QModelIndex* index);
QModelIndex* QTreeView_IndexBelow(const QTreeView* self, QModelIndex* index);
void QTreeView_DoItemsLayout(QTreeView* self);
void QTreeView_Reset(QTreeView* self);
void QTreeView_DataChanged(QTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
void QTreeView_SelectAll(QTreeView* self);
void QTreeView_Expanded(QTreeView* self, QModelIndex* index);
void QTreeView_connect_Expanded(QTreeView* self, intptr_t slot);
void QTreeView_Collapsed(QTreeView* self, QModelIndex* index);
void QTreeView_connect_Collapsed(QTreeView* self, intptr_t slot);
void QTreeView_HideColumn(QTreeView* self, int column);
void QTreeView_ShowColumn(QTreeView* self, int column);
void QTreeView_Expand(QTreeView* self, QModelIndex* index);
void QTreeView_Collapse(QTreeView* self, QModelIndex* index);
void QTreeView_ResizeColumnToContents(QTreeView* self, int column);
void QTreeView_SortByColumn(QTreeView* self, int column, int order);
void QTreeView_ExpandAll(QTreeView* self);
void QTreeView_ExpandRecursively(QTreeView* self, QModelIndex* index);
void QTreeView_CollapseAll(QTreeView* self);
void QTreeView_ExpandToDepth(QTreeView* self, int depth);
void QTreeView_VerticalScrollbarValueChanged(QTreeView* self, int value);
void QTreeView_ScrollContentsBy(QTreeView* self, int dx, int dy);
void QTreeView_RowsInserted(QTreeView* self, QModelIndex* parent, int start, int end);
void QTreeView_RowsAboutToBeRemoved(QTreeView* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeView_MoveCursor(QTreeView* self, int cursorAction, int modifiers);
int QTreeView_HorizontalOffset(const QTreeView* self);
int QTreeView_VerticalOffset(const QTreeView* self);
void QTreeView_SetSelection(QTreeView* self, QRect* rect, int command);
QRegion* QTreeView_VisualRegionForSelection(const QTreeView* self, QItemSelection* selection);
struct miqt_array /* of QModelIndex* */  QTreeView_SelectedIndexes(const QTreeView* self);
void QTreeView_ChangeEvent(QTreeView* self, QEvent* event);
void QTreeView_TimerEvent(QTreeView* self, QTimerEvent* event);
void QTreeView_PaintEvent(QTreeView* self, QPaintEvent* event);
void QTreeView_DrawRow(const QTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_DrawBranches(const QTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_MousePressEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_MouseReleaseEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_MouseDoubleClickEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_MouseMoveEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_KeyPressEvent(QTreeView* self, QKeyEvent* event);
void QTreeView_DragMoveEvent(QTreeView* self, QDragMoveEvent* event);
bool QTreeView_ViewportEvent(QTreeView* self, QEvent* event);
void QTreeView_UpdateGeometries(QTreeView* self);
QSize* QTreeView_ViewportSizeHint(const QTreeView* self);
int QTreeView_SizeHintForColumn(const QTreeView* self, int column);
void QTreeView_HorizontalScrollbarAction(QTreeView* self, int action);
bool QTreeView_IsIndexHidden(const QTreeView* self, QModelIndex* index);
void QTreeView_SelectionChanged(QTreeView* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_CurrentChanged(QTreeView* self, QModelIndex* current, QModelIndex* previous);
struct miqt_string QTreeView_Tr2(const char* s, const char* c);
struct miqt_string QTreeView_Tr3(const char* s, const char* c, int n);
void QTreeView_ExpandRecursively2(QTreeView* self, QModelIndex* index, int depth);
void QTreeView_override_virtual_SetModel(void* self, intptr_t slot);
void QTreeView_virtualbase_SetModel(void* self, QAbstractItemModel* model);
void QTreeView_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QTreeView_virtualbase_SetRootIndex(void* self, QModelIndex* index);
void QTreeView_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QTreeView_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
void QTreeView_override_virtual_KeyboardSearch(void* self, intptr_t slot);
void QTreeView_virtualbase_KeyboardSearch(void* self, struct miqt_string search);
void QTreeView_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QTreeView_virtualbase_VisualRect(const void* self, QModelIndex* index);
void QTreeView_override_virtual_ScrollTo(void* self, intptr_t slot);
void QTreeView_virtualbase_ScrollTo(void* self, QModelIndex* index, int hint);
void QTreeView_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QTreeView_virtualbase_IndexAt(const void* self, QPoint* p);
void QTreeView_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QTreeView_virtualbase_DoItemsLayout(void* self);
void QTreeView_override_virtual_Reset(void* self, intptr_t slot);
void QTreeView_virtualbase_Reset(void* self);
void QTreeView_override_virtual_DataChanged(void* self, intptr_t slot);
void QTreeView_virtualbase_DataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
void QTreeView_override_virtual_SelectAll(void* self, intptr_t slot);
void QTreeView_virtualbase_SelectAll(void* self);
void QTreeView_override_virtual_VerticalScrollbarValueChanged(void* self, intptr_t slot);
void QTreeView_virtualbase_VerticalScrollbarValueChanged(void* self, int value);
void QTreeView_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QTreeView_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
void QTreeView_override_virtual_RowsInserted(void* self, intptr_t slot);
void QTreeView_virtualbase_RowsInserted(void* self, QModelIndex* parent, int start, int end);
void QTreeView_override_virtual_RowsAboutToBeRemoved(void* self, intptr_t slot);
void QTreeView_virtualbase_RowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
void QTreeView_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QTreeView_virtualbase_MoveCursor(void* self, int cursorAction, int modifiers);
void QTreeView_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QTreeView_virtualbase_HorizontalOffset(const void* self);
void QTreeView_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QTreeView_virtualbase_VerticalOffset(const void* self);
void QTreeView_override_virtual_SetSelection(void* self, intptr_t slot);
void QTreeView_virtualbase_SetSelection(void* self, QRect* rect, int command);
void QTreeView_override_virtual_VisualRegionForSelection(void* self, intptr_t slot);
QRegion* QTreeView_virtualbase_VisualRegionForSelection(const void* self, QItemSelection* selection);
void QTreeView_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QTreeView_virtualbase_SelectedIndexes(const void* self);
void QTreeView_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_ChangeEvent(void* self, QEvent* event);
void QTreeView_override_virtual_TimerEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_TimerEvent(void* self, QTimerEvent* event);
void QTreeView_override_virtual_PaintEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_PaintEvent(void* self, QPaintEvent* event);
void QTreeView_override_virtual_DrawRow(void* self, intptr_t slot);
void QTreeView_virtualbase_DrawRow(const void* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_override_virtual_DrawBranches(void* self, intptr_t slot);
void QTreeView_virtualbase_DrawBranches(const void* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
void QTreeView_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
void QTreeView_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
void QTreeView_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
void QTreeView_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QTreeView_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
void QTreeView_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QTreeView_virtualbase_ViewportEvent(void* self, QEvent* event);
void QTreeView_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QTreeView_virtualbase_UpdateGeometries(void* self);
void QTreeView_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QTreeView_virtualbase_ViewportSizeHint(const void* self);
void QTreeView_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QTreeView_virtualbase_SizeHintForColumn(const void* self, int column);
void QTreeView_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QTreeView_virtualbase_HorizontalScrollbarAction(void* self, int action);
void QTreeView_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QTreeView_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
void QTreeView_override_virtual_SelectionChanged(void* self, intptr_t slot);
void QTreeView_virtualbase_SelectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QTreeView_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
void QTreeView_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QTreeView_virtualbase_SizeHintForRow(const void* self, int row);
void QTreeView_override_virtual_ItemDelegateForIndex(void* self, intptr_t slot);
QAbstractItemDelegate* QTreeView_virtualbase_ItemDelegateForIndex(const void* self, QModelIndex* index);
void QTreeView_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QTreeView_virtualbase_InputMethodQuery(const void* self, int query);
void QTreeView_override_virtual_UpdateEditorData(void* self, intptr_t slot);
void QTreeView_virtualbase_UpdateEditorData(void* self);
void QTreeView_override_virtual_UpdateEditorGeometries(void* self, intptr_t slot);
void QTreeView_virtualbase_UpdateEditorGeometries(void* self);
void QTreeView_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QTreeView_virtualbase_VerticalScrollbarAction(void* self, int action);
void QTreeView_override_virtual_HorizontalScrollbarValueChanged(void* self, intptr_t slot);
void QTreeView_virtualbase_HorizontalScrollbarValueChanged(void* self, int value);
void QTreeView_override_virtual_CloseEditor(void* self, intptr_t slot);
void QTreeView_virtualbase_CloseEditor(void* self, QWidget* editor, int hint);
void QTreeView_override_virtual_CommitData(void* self, intptr_t slot);
void QTreeView_virtualbase_CommitData(void* self, QWidget* editor);
void QTreeView_override_virtual_EditorDestroyed(void* self, intptr_t slot);
void QTreeView_virtualbase_EditorDestroyed(void* self, QObject* editor);
void QTreeView_override_virtual_Edit2(void* self, intptr_t slot);
bool QTreeView_virtualbase_Edit2(void* self, QModelIndex* index, int trigger, QEvent* event);
void QTreeView_override_virtual_SelectionCommand(void* self, intptr_t slot);
int QTreeView_virtualbase_SelectionCommand(const void* self, QModelIndex* index, QEvent* event);
void QTreeView_override_virtual_StartDrag(void* self, intptr_t slot);
void QTreeView_virtualbase_StartDrag(void* self, int supportedActions);
void QTreeView_override_virtual_InitViewItemOption(void* self, intptr_t slot);
void QTreeView_virtualbase_InitViewItemOption(const void* self, QStyleOptionViewItem* option);
void QTreeView_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QTreeView_virtualbase_FocusNextPrevChild(void* self, bool next);
void QTreeView_override_virtual_Event(void* self, intptr_t slot);
bool QTreeView_virtualbase_Event(void* self, QEvent* event);
void QTreeView_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
void QTreeView_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
void QTreeView_override_virtual_DropEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_DropEvent(void* self, QDropEvent* event);
void QTreeView_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QTreeView_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QTreeView_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
void QTreeView_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QTreeView_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QTreeView_override_virtual_EventFilter(void* self, intptr_t slot);
bool QTreeView_virtualbase_EventFilter(void* self, QObject* object, QEvent* event);
void QTreeView_Delete(QTreeView* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
