#pragma once
#ifndef MIQT_QT6_GEN_QTREEWIDGET_H
#define MIQT_QT6_GEN_QTREEWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QBrush;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDataStream;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFrame;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QTreeView;
class QTreeWidget;
class QTreeWidgetItem;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDataStream QDataStream;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeView QTreeView;
typedef struct QTreeWidget QTreeWidget;
typedef struct QTreeWidgetItem QTreeWidgetItem;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QTreeWidgetItem* QTreeWidgetItem_new();
QTreeWidgetItem* QTreeWidgetItem_new2(struct miqt_array /* of struct miqt_string */  strings);
QTreeWidgetItem* QTreeWidgetItem_new3(QTreeWidget* treeview);
QTreeWidgetItem* QTreeWidgetItem_new4(QTreeWidget* treeview, struct miqt_array /* of struct miqt_string */  strings);
QTreeWidgetItem* QTreeWidgetItem_new5(QTreeWidget* treeview, QTreeWidgetItem* after);
QTreeWidgetItem* QTreeWidgetItem_new6(QTreeWidgetItem* parent);
QTreeWidgetItem* QTreeWidgetItem_new7(QTreeWidgetItem* parent, struct miqt_array /* of struct miqt_string */  strings);
QTreeWidgetItem* QTreeWidgetItem_new8(QTreeWidgetItem* parent, QTreeWidgetItem* after);
QTreeWidgetItem* QTreeWidgetItem_new9(QTreeWidgetItem* other);
QTreeWidgetItem* QTreeWidgetItem_new10(int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new11(struct miqt_array /* of struct miqt_string */  strings, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new12(QTreeWidget* treeview, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new13(QTreeWidget* treeview, struct miqt_array /* of struct miqt_string */  strings, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new14(QTreeWidget* treeview, QTreeWidgetItem* after, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new15(QTreeWidgetItem* parent, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new16(QTreeWidgetItem* parent, struct miqt_array /* of struct miqt_string */  strings, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_new17(QTreeWidgetItem* parent, QTreeWidgetItem* after, int typeVal);
QTreeWidgetItem* QTreeWidgetItem_Clone(const QTreeWidgetItem* self);
QTreeWidget* QTreeWidgetItem_TreeWidget(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetSelected(QTreeWidgetItem* self, bool selectVal);
bool QTreeWidgetItem_IsSelected(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetHidden(QTreeWidgetItem* self, bool hide);
bool QTreeWidgetItem_IsHidden(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetExpanded(QTreeWidgetItem* self, bool expand);
bool QTreeWidgetItem_IsExpanded(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetFirstColumnSpanned(QTreeWidgetItem* self, bool span);
bool QTreeWidgetItem_IsFirstColumnSpanned(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetDisabled(QTreeWidgetItem* self, bool disabled);
bool QTreeWidgetItem_IsDisabled(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetChildIndicatorPolicy(QTreeWidgetItem* self, int policy);
int QTreeWidgetItem_ChildIndicatorPolicy(const QTreeWidgetItem* self);
int QTreeWidgetItem_Flags(const QTreeWidgetItem* self);
void QTreeWidgetItem_SetFlags(QTreeWidgetItem* self, int flags);
struct miqt_string QTreeWidgetItem_Text(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetText(QTreeWidgetItem* self, int column, struct miqt_string text);
QIcon* QTreeWidgetItem_Icon(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetIcon(QTreeWidgetItem* self, int column, QIcon* icon);
struct miqt_string QTreeWidgetItem_StatusTip(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetStatusTip(QTreeWidgetItem* self, int column, struct miqt_string statusTip);
struct miqt_string QTreeWidgetItem_ToolTip(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetToolTip(QTreeWidgetItem* self, int column, struct miqt_string toolTip);
struct miqt_string QTreeWidgetItem_WhatsThis(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetWhatsThis(QTreeWidgetItem* self, int column, struct miqt_string whatsThis);
QFont* QTreeWidgetItem_Font(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetFont(QTreeWidgetItem* self, int column, QFont* font);
int QTreeWidgetItem_TextAlignment(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetTextAlignment(QTreeWidgetItem* self, int column, int alignment);
void QTreeWidgetItem_SetTextAlignment2(QTreeWidgetItem* self, int column, int alignment);
void QTreeWidgetItem_SetTextAlignment3(QTreeWidgetItem* self, int column, int alignment);
QBrush* QTreeWidgetItem_Background(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetBackground(QTreeWidgetItem* self, int column, QBrush* brush);
QBrush* QTreeWidgetItem_Foreground(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetForeground(QTreeWidgetItem* self, int column, QBrush* brush);
int QTreeWidgetItem_CheckState(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetCheckState(QTreeWidgetItem* self, int column, int state);
QSize* QTreeWidgetItem_SizeHint(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_SetSizeHint(QTreeWidgetItem* self, int column, QSize* size);
QVariant* QTreeWidgetItem_Data(const QTreeWidgetItem* self, int column, int role);
void QTreeWidgetItem_SetData(QTreeWidgetItem* self, int column, int role, QVariant* value);
bool QTreeWidgetItem_OperatorLesser(const QTreeWidgetItem* self, QTreeWidgetItem* other);
void QTreeWidgetItem_Read(QTreeWidgetItem* self, QDataStream* in);
void QTreeWidgetItem_Write(const QTreeWidgetItem* self, QDataStream* out);
void QTreeWidgetItem_OperatorAssign(QTreeWidgetItem* self, QTreeWidgetItem* other);
QTreeWidgetItem* QTreeWidgetItem_Parent(const QTreeWidgetItem* self);
QTreeWidgetItem* QTreeWidgetItem_Child(const QTreeWidgetItem* self, int index);
int QTreeWidgetItem_ChildCount(const QTreeWidgetItem* self);
int QTreeWidgetItem_ColumnCount(const QTreeWidgetItem* self);
int QTreeWidgetItem_IndexOfChild(const QTreeWidgetItem* self, QTreeWidgetItem* child);
void QTreeWidgetItem_AddChild(QTreeWidgetItem* self, QTreeWidgetItem* child);
void QTreeWidgetItem_InsertChild(QTreeWidgetItem* self, int index, QTreeWidgetItem* child);
void QTreeWidgetItem_RemoveChild(QTreeWidgetItem* self, QTreeWidgetItem* child);
QTreeWidgetItem* QTreeWidgetItem_TakeChild(QTreeWidgetItem* self, int index);
void QTreeWidgetItem_AddChildren(QTreeWidgetItem* self, struct miqt_array /* of QTreeWidgetItem* */  children);
void QTreeWidgetItem_InsertChildren(QTreeWidgetItem* self, int index, struct miqt_array /* of QTreeWidgetItem* */  children);
struct miqt_array /* of QTreeWidgetItem* */  QTreeWidgetItem_TakeChildren(QTreeWidgetItem* self);
int QTreeWidgetItem_Type(const QTreeWidgetItem* self);
void QTreeWidgetItem_SortChildren(QTreeWidgetItem* self, int column, int order);
bool QTreeWidgetItem_override_virtual_Clone(void* self, intptr_t slot);
QTreeWidgetItem* QTreeWidgetItem_virtualbase_Clone(const void* self);
bool QTreeWidgetItem_override_virtual_Data(void* self, intptr_t slot);
QVariant* QTreeWidgetItem_virtualbase_Data(const void* self, int column, int role);
bool QTreeWidgetItem_override_virtual_SetData(void* self, intptr_t slot);
void QTreeWidgetItem_virtualbase_SetData(void* self, int column, int role, QVariant* value);
bool QTreeWidgetItem_override_virtual_OperatorLesser(void* self, intptr_t slot);
bool QTreeWidgetItem_virtualbase_OperatorLesser(const void* self, QTreeWidgetItem* other);
bool QTreeWidgetItem_override_virtual_Read(void* self, intptr_t slot);
void QTreeWidgetItem_virtualbase_Read(void* self, QDataStream* in);
bool QTreeWidgetItem_override_virtual_Write(void* self, intptr_t slot);
void QTreeWidgetItem_virtualbase_Write(const void* self, QDataStream* out);
void QTreeWidgetItem_Delete(QTreeWidgetItem* self);

QTreeWidget* QTreeWidget_new(QWidget* parent);
QTreeWidget* QTreeWidget_new2();
void QTreeWidget_virtbase(QTreeWidget* src, QTreeView** outptr_QTreeView);
QMetaObject* QTreeWidget_MetaObject(const QTreeWidget* self);
void* QTreeWidget_Metacast(QTreeWidget* self, const char* param1);
struct miqt_string QTreeWidget_Tr(const char* s);
int QTreeWidget_ColumnCount(const QTreeWidget* self);
void QTreeWidget_SetColumnCount(QTreeWidget* self, int columns);
QTreeWidgetItem* QTreeWidget_InvisibleRootItem(const QTreeWidget* self);
QTreeWidgetItem* QTreeWidget_TopLevelItem(const QTreeWidget* self, int index);
int QTreeWidget_TopLevelItemCount(const QTreeWidget* self);
void QTreeWidget_InsertTopLevelItem(QTreeWidget* self, int index, QTreeWidgetItem* item);
void QTreeWidget_AddTopLevelItem(QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_TakeTopLevelItem(QTreeWidget* self, int index);
int QTreeWidget_IndexOfTopLevelItem(const QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_InsertTopLevelItems(QTreeWidget* self, int index, struct miqt_array /* of QTreeWidgetItem* */  items);
void QTreeWidget_AddTopLevelItems(QTreeWidget* self, struct miqt_array /* of QTreeWidgetItem* */  items);
QTreeWidgetItem* QTreeWidget_HeaderItem(const QTreeWidget* self);
void QTreeWidget_SetHeaderItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_SetHeaderLabels(QTreeWidget* self, struct miqt_array /* of struct miqt_string */  labels);
void QTreeWidget_SetHeaderLabel(QTreeWidget* self, struct miqt_string label);
QTreeWidgetItem* QTreeWidget_CurrentItem(const QTreeWidget* self);
int QTreeWidget_CurrentColumn(const QTreeWidget* self);
void QTreeWidget_SetCurrentItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_SetCurrentItem2(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_SetCurrentItem3(QTreeWidget* self, QTreeWidgetItem* item, int column, int command);
QTreeWidgetItem* QTreeWidget_ItemAt(const QTreeWidget* self, QPoint* p);
QTreeWidgetItem* QTreeWidget_ItemAt2(const QTreeWidget* self, int x, int y);
QRect* QTreeWidget_VisualItemRect(const QTreeWidget* self, QTreeWidgetItem* item);
int QTreeWidget_SortColumn(const QTreeWidget* self);
void QTreeWidget_SortItems(QTreeWidget* self, int column, int order);
void QTreeWidget_EditItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_OpenPersistentEditor(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_ClosePersistentEditor(QTreeWidget* self, QTreeWidgetItem* item);
bool QTreeWidget_IsPersistentEditorOpen(const QTreeWidget* self, QTreeWidgetItem* item);
QWidget* QTreeWidget_ItemWidget(const QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_SetItemWidget(QTreeWidget* self, QTreeWidgetItem* item, int column, QWidget* widget);
void QTreeWidget_RemoveItemWidget(QTreeWidget* self, QTreeWidgetItem* item, int column);
struct miqt_array /* of QTreeWidgetItem* */  QTreeWidget_SelectedItems(const QTreeWidget* self);
struct miqt_array /* of QTreeWidgetItem* */  QTreeWidget_FindItems(const QTreeWidget* self, struct miqt_string text, int flags);
QTreeWidgetItem* QTreeWidget_ItemAbove(const QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_ItemBelow(const QTreeWidget* self, QTreeWidgetItem* item);
QModelIndex* QTreeWidget_IndexFromItem(const QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_ItemFromIndex(const QTreeWidget* self, QModelIndex* index);
void QTreeWidget_SetSelectionModel(QTreeWidget* self, QItemSelectionModel* selectionModel);
void QTreeWidget_ScrollToItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_ExpandItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_CollapseItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_Clear(QTreeWidget* self);
void QTreeWidget_ItemPressed(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemPressed(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemClicked(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemClicked(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemDoubleClicked(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemDoubleClicked(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemActivated(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemActivated(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemEntered(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemEntered(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemChanged(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_ItemChanged(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemExpanded(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_connect_ItemExpanded(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemCollapsed(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_connect_ItemCollapsed(QTreeWidget* self, intptr_t slot);
void QTreeWidget_CurrentItemChanged(QTreeWidget* self, QTreeWidgetItem* current, QTreeWidgetItem* previous);
void QTreeWidget_connect_CurrentItemChanged(QTreeWidget* self, intptr_t slot);
void QTreeWidget_ItemSelectionChanged(QTreeWidget* self);
void QTreeWidget_connect_ItemSelectionChanged(QTreeWidget* self, intptr_t slot);
bool QTreeWidget_Event(QTreeWidget* self, QEvent* e);
struct miqt_array /* of struct miqt_string */  QTreeWidget_MimeTypes(const QTreeWidget* self);
QMimeData* QTreeWidget_MimeData(const QTreeWidget* self, struct miqt_array /* of QTreeWidgetItem* */  items);
bool QTreeWidget_DropMimeData(QTreeWidget* self, QTreeWidgetItem* parent, int index, QMimeData* data, int action);
int QTreeWidget_SupportedDropActions(const QTreeWidget* self);
void QTreeWidget_DropEvent(QTreeWidget* self, QDropEvent* event);
struct miqt_string QTreeWidget_Tr2(const char* s, const char* c);
struct miqt_string QTreeWidget_Tr3(const char* s, const char* c, int n);
void QTreeWidget_EditItem2(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_OpenPersistentEditor2(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_ClosePersistentEditor2(QTreeWidget* self, QTreeWidgetItem* item, int column);
bool QTreeWidget_IsPersistentEditorOpen2(const QTreeWidget* self, QTreeWidgetItem* item, int column);
struct miqt_array /* of QTreeWidgetItem* */  QTreeWidget_FindItems3(const QTreeWidget* self, struct miqt_string text, int flags, int column);
QModelIndex* QTreeWidget_IndexFromItem2(const QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_ScrollToItem2(QTreeWidget* self, QTreeWidgetItem* item, int hint);
bool QTreeWidget_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
bool QTreeWidget_override_virtual_Event(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_Event(void* self, QEvent* e);
bool QTreeWidget_override_virtual_MimeTypes(void* self, intptr_t slot);
struct miqt_array /* of struct miqt_string */  QTreeWidget_virtualbase_MimeTypes(const void* self);
bool QTreeWidget_override_virtual_MimeData(void* self, intptr_t slot);
QMimeData* QTreeWidget_virtualbase_MimeData(const void* self, struct miqt_array /* of QTreeWidgetItem* */  items);
bool QTreeWidget_override_virtual_DropMimeData(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_DropMimeData(void* self, QTreeWidgetItem* parent, int index, QMimeData* data, int action);
bool QTreeWidget_override_virtual_SupportedDropActions(void* self, intptr_t slot);
int QTreeWidget_virtualbase_SupportedDropActions(const void* self);
bool QTreeWidget_override_virtual_DropEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DropEvent(void* self, QDropEvent* event);
bool QTreeWidget_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SetRootIndex(void* self, QModelIndex* index);
bool QTreeWidget_override_virtual_KeyboardSearch(void* self, intptr_t slot);
void QTreeWidget_virtualbase_KeyboardSearch(void* self, struct miqt_string search);
bool QTreeWidget_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QTreeWidget_virtualbase_VisualRect(const void* self, QModelIndex* index);
bool QTreeWidget_override_virtual_ScrollTo(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ScrollTo(void* self, QModelIndex* index, int hint);
bool QTreeWidget_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QTreeWidget_virtualbase_IndexAt(const void* self, QPoint* p);
bool QTreeWidget_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DoItemsLayout(void* self);
bool QTreeWidget_override_virtual_Reset(void* self, intptr_t slot);
void QTreeWidget_virtualbase_Reset(void* self);
bool QTreeWidget_override_virtual_DataChanged(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
bool QTreeWidget_override_virtual_SelectAll(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SelectAll(void* self);
bool QTreeWidget_override_virtual_VerticalScrollbarValueChanged(void* self, intptr_t slot);
void QTreeWidget_virtualbase_VerticalScrollbarValueChanged(void* self, int value);
bool QTreeWidget_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
bool QTreeWidget_override_virtual_RowsInserted(void* self, intptr_t slot);
void QTreeWidget_virtualbase_RowsInserted(void* self, QModelIndex* parent, int start, int end);
bool QTreeWidget_override_virtual_RowsAboutToBeRemoved(void* self, intptr_t slot);
void QTreeWidget_virtualbase_RowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
bool QTreeWidget_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QTreeWidget_virtualbase_MoveCursor(void* self, int cursorAction, int modifiers);
bool QTreeWidget_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QTreeWidget_virtualbase_HorizontalOffset(const void* self);
bool QTreeWidget_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QTreeWidget_virtualbase_VerticalOffset(const void* self);
bool QTreeWidget_override_virtual_SetSelection(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SetSelection(void* self, QRect* rect, int command);
bool QTreeWidget_override_virtual_VisualRegionForSelection(void* self, intptr_t slot);
QRegion* QTreeWidget_virtualbase_VisualRegionForSelection(const void* self, QItemSelection* selection);
bool QTreeWidget_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QTreeWidget_virtualbase_SelectedIndexes(const void* self);
bool QTreeWidget_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ChangeEvent(void* self, QEvent* event);
bool QTreeWidget_override_virtual_TimerEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_TimerEvent(void* self, QTimerEvent* event);
bool QTreeWidget_override_virtual_PaintEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_PaintEvent(void* self, QPaintEvent* event);
bool QTreeWidget_override_virtual_DrawRow(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DrawRow(const void* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
bool QTreeWidget_override_virtual_DrawBranches(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DrawBranches(const void* self, QPainter* painter, QRect* rect, QModelIndex* index);
bool QTreeWidget_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
bool QTreeWidget_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
bool QTreeWidget_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QTreeWidget_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
bool QTreeWidget_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
bool QTreeWidget_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
bool QTreeWidget_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_ViewportEvent(void* self, QEvent* event);
bool QTreeWidget_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QTreeWidget_virtualbase_UpdateGeometries(void* self);
bool QTreeWidget_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QTreeWidget_virtualbase_ViewportSizeHint(const void* self);
bool QTreeWidget_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QTreeWidget_virtualbase_SizeHintForColumn(const void* self, int column);
bool QTreeWidget_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QTreeWidget_virtualbase_HorizontalScrollbarAction(void* self, int action);
bool QTreeWidget_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
bool QTreeWidget_override_virtual_SelectionChanged(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SelectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
bool QTreeWidget_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QTreeWidget_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
bool QTreeWidget_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QTreeWidget_virtualbase_SizeHintForRow(const void* self, int row);
bool QTreeWidget_override_virtual_ItemDelegateForIndex(void* self, intptr_t slot);
QAbstractItemDelegate* QTreeWidget_virtualbase_ItemDelegateForIndex(const void* self, QModelIndex* index);
bool QTreeWidget_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QTreeWidget_virtualbase_InputMethodQuery(const void* self, int query);
bool QTreeWidget_override_virtual_UpdateEditorData(void* self, intptr_t slot);
void QTreeWidget_virtualbase_UpdateEditorData(void* self);
bool QTreeWidget_override_virtual_UpdateEditorGeometries(void* self, intptr_t slot);
void QTreeWidget_virtualbase_UpdateEditorGeometries(void* self);
bool QTreeWidget_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QTreeWidget_virtualbase_VerticalScrollbarAction(void* self, int action);
bool QTreeWidget_override_virtual_HorizontalScrollbarValueChanged(void* self, intptr_t slot);
void QTreeWidget_virtualbase_HorizontalScrollbarValueChanged(void* self, int value);
bool QTreeWidget_override_virtual_CloseEditor(void* self, intptr_t slot);
void QTreeWidget_virtualbase_CloseEditor(void* self, QWidget* editor, int hint);
bool QTreeWidget_override_virtual_CommitData(void* self, intptr_t slot);
void QTreeWidget_virtualbase_CommitData(void* self, QWidget* editor);
bool QTreeWidget_override_virtual_EditorDestroyed(void* self, intptr_t slot);
void QTreeWidget_virtualbase_EditorDestroyed(void* self, QObject* editor);
bool QTreeWidget_override_virtual_Edit2(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_Edit2(void* self, QModelIndex* index, int trigger, QEvent* event);
bool QTreeWidget_override_virtual_SelectionCommand(void* self, intptr_t slot);
int QTreeWidget_virtualbase_SelectionCommand(const void* self, QModelIndex* index, QEvent* event);
bool QTreeWidget_override_virtual_StartDrag(void* self, intptr_t slot);
void QTreeWidget_virtualbase_StartDrag(void* self, int supportedActions);
bool QTreeWidget_override_virtual_InitViewItemOption(void* self, intptr_t slot);
void QTreeWidget_virtualbase_InitViewItemOption(const void* self, QStyleOptionViewItem* option);
bool QTreeWidget_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_FocusNextPrevChild(void* self, bool next);
bool QTreeWidget_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
bool QTreeWidget_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
bool QTreeWidget_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
bool QTreeWidget_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
bool QTreeWidget_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
bool QTreeWidget_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
bool QTreeWidget_override_virtual_EventFilter(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_EventFilter(void* self, QObject* object, QEvent* event);
bool QTreeWidget_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QTreeWidget_virtualbase_MinimumSizeHint(const void* self);
bool QTreeWidget_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QTreeWidget_virtualbase_SizeHint(const void* self);
bool QTreeWidget_override_virtual_SetupViewport(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SetupViewport(void* self, QWidget* viewport);
bool QTreeWidget_override_virtual_WheelEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_WheelEvent(void* self, QWheelEvent* param1);
bool QTreeWidget_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* param1);
bool QTreeWidget_override_virtual_InitStyleOption(void* self, intptr_t slot);
void QTreeWidget_virtualbase_InitStyleOption(const void* self, QStyleOptionFrame* option);
bool QTreeWidget_override_virtual_DevType(void* self, intptr_t slot);
int QTreeWidget_virtualbase_DevType(const void* self);
bool QTreeWidget_override_virtual_SetVisible(void* self, intptr_t slot);
void QTreeWidget_virtualbase_SetVisible(void* self, bool visible);
bool QTreeWidget_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QTreeWidget_virtualbase_HeightForWidth(const void* self, int param1);
bool QTreeWidget_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_HasHeightForWidth(const void* self);
bool QTreeWidget_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QTreeWidget_virtualbase_PaintEngine(const void* self);
bool QTreeWidget_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
bool QTreeWidget_override_virtual_EnterEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_EnterEvent(void* self, QEnterEvent* event);
bool QTreeWidget_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_LeaveEvent(void* self, QEvent* event);
bool QTreeWidget_override_virtual_MoveEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_MoveEvent(void* self, QMoveEvent* event);
bool QTreeWidget_override_virtual_CloseEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_CloseEvent(void* self, QCloseEvent* event);
bool QTreeWidget_override_virtual_TabletEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_TabletEvent(void* self, QTabletEvent* event);
bool QTreeWidget_override_virtual_ActionEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ActionEvent(void* self, QActionEvent* event);
bool QTreeWidget_override_virtual_ShowEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ShowEvent(void* self, QShowEvent* event);
bool QTreeWidget_override_virtual_HideEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_HideEvent(void* self, QHideEvent* event);
bool QTreeWidget_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QTreeWidget_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
bool QTreeWidget_override_virtual_Metric(void* self, intptr_t slot);
int QTreeWidget_virtualbase_Metric(const void* self, int param1);
bool QTreeWidget_override_virtual_InitPainter(void* self, intptr_t slot);
void QTreeWidget_virtualbase_InitPainter(const void* self, QPainter* painter);
bool QTreeWidget_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QTreeWidget_virtualbase_Redirected(const void* self, QPoint* offset);
bool QTreeWidget_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QTreeWidget_virtualbase_SharedPainter(const void* self);
bool QTreeWidget_override_virtual_ChildEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ChildEvent(void* self, QChildEvent* event);
bool QTreeWidget_override_virtual_CustomEvent(void* self, intptr_t slot);
void QTreeWidget_virtualbase_CustomEvent(void* self, QEvent* event);
bool QTreeWidget_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QTreeWidget_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
bool QTreeWidget_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QTreeWidget_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
void QTreeWidget_Delete(QTreeWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
