#pragma once
#ifndef MIQT_QT_GEN_QGRAPHICSITEM_H
#define MIQT_QT_GEN_QGRAPHICSITEM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractGraphicsShapeItem;
class QBrush;
class QChildEvent;
class QColor;
class QCursor;
class QEvent;
class QFocusEvent;
class QFont;
class QGraphicsEffect;
class QGraphicsEllipseItem;
class QGraphicsItem;
class QGraphicsItemGroup;
class QGraphicsLineItem;
class QGraphicsObject;
class QGraphicsPathItem;
class QGraphicsPixmapItem;
class QGraphicsPolygonItem;
class QGraphicsRectItem;
class QGraphicsScene;
class QGraphicsSceneContextMenuEvent;
class QGraphicsSceneDragDropEvent;
class QGraphicsSceneHoverEvent;
class QGraphicsSceneMouseEvent;
class QGraphicsSceneWheelEvent;
class QGraphicsSimpleTextItem;
class QGraphicsTextItem;
class QGraphicsTransform;
class QGraphicsWidget;
class QInputMethodEvent;
class QKeyEvent;
class QLineF;
class QMatrix;
class QMetaMethod;
class QMetaObject;
class QObject;
class QPainter;
class QPainterPath;
class QPen;
class QPixmap;
class QPointF;
class QRectF;
class QRegion;
class QSize;
class QStyleOptionGraphicsItem;
class QTextCursor;
class QTextDocument;
class QTimerEvent;
class QTransform;
class QVariant;
class QWidget;
#else
typedef struct QAbstractGraphicsShapeItem QAbstractGraphicsShapeItem;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QColor QColor;
typedef struct QCursor QCursor;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsEllipseItem QGraphicsEllipseItem;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsItemGroup QGraphicsItemGroup;
typedef struct QGraphicsLineItem QGraphicsLineItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsPathItem QGraphicsPathItem;
typedef struct QGraphicsPixmapItem QGraphicsPixmapItem;
typedef struct QGraphicsPolygonItem QGraphicsPolygonItem;
typedef struct QGraphicsRectItem QGraphicsRectItem;
typedef struct QGraphicsScene QGraphicsScene;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsSimpleTextItem QGraphicsSimpleTextItem;
typedef struct QGraphicsTextItem QGraphicsTextItem;
typedef struct QGraphicsTransform QGraphicsTransform;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineF QLineF;
typedef struct QMatrix QMatrix;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPen QPen;
typedef struct QPixmap QPixmap;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QRegion QRegion;
typedef struct QSize QSize;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTextCursor QTextCursor;
typedef struct QTextDocument QTextDocument;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTransform QTransform;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

void QGraphicsItem_new(QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsItem_new2(QGraphicsItem* parent, QGraphicsItem** outptr_QGraphicsItem);
QGraphicsScene* QGraphicsItem_Scene(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_ParentItem(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_TopLevelItem(const QGraphicsItem* self);
QGraphicsObject* QGraphicsItem_ParentObject(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_ParentWidget(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_TopLevelWidget(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_Window(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_Panel(const QGraphicsItem* self);
void QGraphicsItem_SetParentItem(QGraphicsItem* self, QGraphicsItem* parent);
struct miqt_array /* of QGraphicsItem* */  QGraphicsItem_ChildItems(const QGraphicsItem* self);
bool QGraphicsItem_IsWidget(const QGraphicsItem* self);
bool QGraphicsItem_IsWindow(const QGraphicsItem* self);
bool QGraphicsItem_IsPanel(const QGraphicsItem* self);
QGraphicsObject* QGraphicsItem_ToGraphicsObject(QGraphicsItem* self);
QGraphicsObject* QGraphicsItem_ToGraphicsObject2(const QGraphicsItem* self);
QGraphicsItemGroup* QGraphicsItem_Group(const QGraphicsItem* self);
void QGraphicsItem_SetGroup(QGraphicsItem* self, QGraphicsItemGroup* group);
int QGraphicsItem_Flags(const QGraphicsItem* self);
void QGraphicsItem_SetFlag(QGraphicsItem* self, int flag);
void QGraphicsItem_SetFlags(QGraphicsItem* self, int flags);
int QGraphicsItem_CacheMode(const QGraphicsItem* self);
void QGraphicsItem_SetCacheMode(QGraphicsItem* self, int mode);
int QGraphicsItem_PanelModality(const QGraphicsItem* self);
void QGraphicsItem_SetPanelModality(QGraphicsItem* self, int panelModality);
bool QGraphicsItem_IsBlockedByModalPanel(const QGraphicsItem* self);
struct miqt_string QGraphicsItem_ToolTip(const QGraphicsItem* self);
void QGraphicsItem_SetToolTip(QGraphicsItem* self, struct miqt_string toolTip);
QCursor* QGraphicsItem_Cursor(const QGraphicsItem* self);
void QGraphicsItem_SetCursor(QGraphicsItem* self, QCursor* cursor);
bool QGraphicsItem_HasCursor(const QGraphicsItem* self);
void QGraphicsItem_UnsetCursor(QGraphicsItem* self);
bool QGraphicsItem_IsVisible(const QGraphicsItem* self);
bool QGraphicsItem_IsVisibleTo(const QGraphicsItem* self, QGraphicsItem* parent);
void QGraphicsItem_SetVisible(QGraphicsItem* self, bool visible);
void QGraphicsItem_Hide(QGraphicsItem* self);
void QGraphicsItem_Show(QGraphicsItem* self);
bool QGraphicsItem_IsEnabled(const QGraphicsItem* self);
void QGraphicsItem_SetEnabled(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_IsSelected(const QGraphicsItem* self);
void QGraphicsItem_SetSelected(QGraphicsItem* self, bool selected);
bool QGraphicsItem_AcceptDrops(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptDrops(QGraphicsItem* self, bool on);
double QGraphicsItem_Opacity(const QGraphicsItem* self);
double QGraphicsItem_EffectiveOpacity(const QGraphicsItem* self);
void QGraphicsItem_SetOpacity(QGraphicsItem* self, double opacity);
QGraphicsEffect* QGraphicsItem_GraphicsEffect(const QGraphicsItem* self);
void QGraphicsItem_SetGraphicsEffect(QGraphicsItem* self, QGraphicsEffect* effect);
int QGraphicsItem_AcceptedMouseButtons(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptedMouseButtons(QGraphicsItem* self, int buttons);
bool QGraphicsItem_AcceptHoverEvents(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptHoverEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_AcceptTouchEvents(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptTouchEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_FiltersChildEvents(const QGraphicsItem* self);
void QGraphicsItem_SetFiltersChildEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_HandlesChildEvents(const QGraphicsItem* self);
void QGraphicsItem_SetHandlesChildEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_IsActive(const QGraphicsItem* self);
void QGraphicsItem_SetActive(QGraphicsItem* self, bool active);
bool QGraphicsItem_HasFocus(const QGraphicsItem* self);
void QGraphicsItem_SetFocus(QGraphicsItem* self);
void QGraphicsItem_ClearFocus(QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_FocusProxy(const QGraphicsItem* self);
void QGraphicsItem_SetFocusProxy(QGraphicsItem* self, QGraphicsItem* item);
QGraphicsItem* QGraphicsItem_FocusItem(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_FocusScopeItem(const QGraphicsItem* self);
void QGraphicsItem_GrabMouse(QGraphicsItem* self);
void QGraphicsItem_UngrabMouse(QGraphicsItem* self);
void QGraphicsItem_GrabKeyboard(QGraphicsItem* self);
void QGraphicsItem_UngrabKeyboard(QGraphicsItem* self);
QPointF* QGraphicsItem_Pos(const QGraphicsItem* self);
double QGraphicsItem_X(const QGraphicsItem* self);
void QGraphicsItem_SetX(QGraphicsItem* self, double x);
double QGraphicsItem_Y(const QGraphicsItem* self);
void QGraphicsItem_SetY(QGraphicsItem* self, double y);
QPointF* QGraphicsItem_ScenePos(const QGraphicsItem* self);
void QGraphicsItem_SetPos(QGraphicsItem* self, QPointF* pos);
void QGraphicsItem_SetPos2(QGraphicsItem* self, double x, double y);
void QGraphicsItem_MoveBy(QGraphicsItem* self, double dx, double dy);
void QGraphicsItem_EnsureVisible(QGraphicsItem* self);
void QGraphicsItem_EnsureVisible2(QGraphicsItem* self, double x, double y, double w, double h);
QMatrix* QGraphicsItem_Matrix(const QGraphicsItem* self);
QMatrix* QGraphicsItem_SceneMatrix(const QGraphicsItem* self);
void QGraphicsItem_SetMatrix(QGraphicsItem* self, QMatrix* matrix);
void QGraphicsItem_ResetMatrix(QGraphicsItem* self);
QTransform* QGraphicsItem_Transform(const QGraphicsItem* self);
QTransform* QGraphicsItem_SceneTransform(const QGraphicsItem* self);
QTransform* QGraphicsItem_DeviceTransform(const QGraphicsItem* self, QTransform* viewportTransform);
QTransform* QGraphicsItem_ItemTransform(const QGraphicsItem* self, QGraphicsItem* other);
void QGraphicsItem_SetTransform(QGraphicsItem* self, QTransform* matrix);
void QGraphicsItem_ResetTransform(QGraphicsItem* self);
void QGraphicsItem_SetRotation(QGraphicsItem* self, double angle);
double QGraphicsItem_Rotation(const QGraphicsItem* self);
void QGraphicsItem_SetScale(QGraphicsItem* self, double scale);
double QGraphicsItem_Scale(const QGraphicsItem* self);
struct miqt_array /* of QGraphicsTransform* */  QGraphicsItem_Transformations(const QGraphicsItem* self);
void QGraphicsItem_SetTransformations(QGraphicsItem* self, struct miqt_array /* of QGraphicsTransform* */  transformations);
QPointF* QGraphicsItem_TransformOriginPoint(const QGraphicsItem* self);
void QGraphicsItem_SetTransformOriginPoint(QGraphicsItem* self, QPointF* origin);
void QGraphicsItem_SetTransformOriginPoint2(QGraphicsItem* self, double ax, double ay);
void QGraphicsItem_Advance(QGraphicsItem* self, int phase);
double QGraphicsItem_ZValue(const QGraphicsItem* self);
void QGraphicsItem_SetZValue(QGraphicsItem* self, double z);
void QGraphicsItem_StackBefore(QGraphicsItem* self, QGraphicsItem* sibling);
QRectF* QGraphicsItem_BoundingRect(const QGraphicsItem* self);
QRectF* QGraphicsItem_ChildrenBoundingRect(const QGraphicsItem* self);
QRectF* QGraphicsItem_SceneBoundingRect(const QGraphicsItem* self);
QPainterPath* QGraphicsItem_Shape(const QGraphicsItem* self);
bool QGraphicsItem_IsClipped(const QGraphicsItem* self);
QPainterPath* QGraphicsItem_ClipPath(const QGraphicsItem* self);
bool QGraphicsItem_Contains(const QGraphicsItem* self, QPointF* point);
bool QGraphicsItem_CollidesWithItem(const QGraphicsItem* self, QGraphicsItem* other, int mode);
bool QGraphicsItem_CollidesWithPath(const QGraphicsItem* self, QPainterPath* path, int mode);
struct miqt_array /* of QGraphicsItem* */  QGraphicsItem_CollidingItems(const QGraphicsItem* self);
bool QGraphicsItem_IsObscured(const QGraphicsItem* self);
bool QGraphicsItem_IsObscured2(const QGraphicsItem* self, double x, double y, double w, double h);
bool QGraphicsItem_IsObscuredBy(const QGraphicsItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsItem_OpaqueArea(const QGraphicsItem* self);
QRegion* QGraphicsItem_BoundingRegion(const QGraphicsItem* self, QTransform* itemToDeviceTransform);
double QGraphicsItem_BoundingRegionGranularity(const QGraphicsItem* self);
void QGraphicsItem_SetBoundingRegionGranularity(QGraphicsItem* self, double granularity);
void QGraphicsItem_Paint(QGraphicsItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItem_Update(QGraphicsItem* self);
void QGraphicsItem_Update2(QGraphicsItem* self, double x, double y, double width, double height);
void QGraphicsItem_Scroll(QGraphicsItem* self, double dx, double dy);
QPointF* QGraphicsItem_MapToItem(const QGraphicsItem* self, QGraphicsItem* item, QPointF* point);
QPointF* QGraphicsItem_MapToParent(const QGraphicsItem* self, QPointF* point);
QPointF* QGraphicsItem_MapToScene(const QGraphicsItem* self, QPointF* point);
QRectF* QGraphicsItem_MapRectToItem(const QGraphicsItem* self, QGraphicsItem* item, QRectF* rect);
QRectF* QGraphicsItem_MapRectToParent(const QGraphicsItem* self, QRectF* rect);
QRectF* QGraphicsItem_MapRectToScene(const QGraphicsItem* self, QRectF* rect);
QPainterPath* QGraphicsItem_MapToItem4(const QGraphicsItem* self, QGraphicsItem* item, QPainterPath* path);
QPainterPath* QGraphicsItem_MapToParentWithPath(const QGraphicsItem* self, QPainterPath* path);
QPainterPath* QGraphicsItem_MapToSceneWithPath(const QGraphicsItem* self, QPainterPath* path);
QPointF* QGraphicsItem_MapFromItem(const QGraphicsItem* self, QGraphicsItem* item, QPointF* point);
QPointF* QGraphicsItem_MapFromParent(const QGraphicsItem* self, QPointF* point);
QPointF* QGraphicsItem_MapFromScene(const QGraphicsItem* self, QPointF* point);
QRectF* QGraphicsItem_MapRectFromItem(const QGraphicsItem* self, QGraphicsItem* item, QRectF* rect);
QRectF* QGraphicsItem_MapRectFromParent(const QGraphicsItem* self, QRectF* rect);
QRectF* QGraphicsItem_MapRectFromScene(const QGraphicsItem* self, QRectF* rect);
QPainterPath* QGraphicsItem_MapFromItem4(const QGraphicsItem* self, QGraphicsItem* item, QPainterPath* path);
QPainterPath* QGraphicsItem_MapFromParentWithPath(const QGraphicsItem* self, QPainterPath* path);
QPainterPath* QGraphicsItem_MapFromSceneWithPath(const QGraphicsItem* self, QPainterPath* path);
QPointF* QGraphicsItem_MapToItem5(const QGraphicsItem* self, QGraphicsItem* item, double x, double y);
QPointF* QGraphicsItem_MapToParent2(const QGraphicsItem* self, double x, double y);
QPointF* QGraphicsItem_MapToScene2(const QGraphicsItem* self, double x, double y);
QRectF* QGraphicsItem_MapRectToItem2(const QGraphicsItem* self, QGraphicsItem* item, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectToParent2(const QGraphicsItem* self, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectToScene2(const QGraphicsItem* self, double x, double y, double w, double h);
QPointF* QGraphicsItem_MapFromItem5(const QGraphicsItem* self, QGraphicsItem* item, double x, double y);
QPointF* QGraphicsItem_MapFromParent2(const QGraphicsItem* self, double x, double y);
QPointF* QGraphicsItem_MapFromScene2(const QGraphicsItem* self, double x, double y);
QRectF* QGraphicsItem_MapRectFromItem2(const QGraphicsItem* self, QGraphicsItem* item, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectFromParent2(const QGraphicsItem* self, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectFromScene2(const QGraphicsItem* self, double x, double y, double w, double h);
bool QGraphicsItem_IsAncestorOf(const QGraphicsItem* self, QGraphicsItem* child);
QGraphicsItem* QGraphicsItem_CommonAncestorItem(const QGraphicsItem* self, QGraphicsItem* other);
bool QGraphicsItem_IsUnderMouse(const QGraphicsItem* self);
QVariant* QGraphicsItem_Data(const QGraphicsItem* self, int key);
void QGraphicsItem_SetData(QGraphicsItem* self, int key, QVariant* value);
int QGraphicsItem_InputMethodHints(const QGraphicsItem* self);
void QGraphicsItem_SetInputMethodHints(QGraphicsItem* self, int hints);
int QGraphicsItem_Type(const QGraphicsItem* self);
void QGraphicsItem_InstallSceneEventFilter(QGraphicsItem* self, QGraphicsItem* filterItem);
void QGraphicsItem_RemoveSceneEventFilter(QGraphicsItem* self, QGraphicsItem* filterItem);
bool QGraphicsItem_SceneEventFilter(QGraphicsItem* self, QGraphicsItem* watched, QEvent* event);
bool QGraphicsItem_SceneEvent(QGraphicsItem* self, QEvent* event);
void QGraphicsItem_ContextMenuEvent(QGraphicsItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsItem_DragEnterEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DragLeaveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DragMoveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DropEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_FocusInEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_FocusOutEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_HoverEnterEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_HoverMoveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_HoverLeaveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_KeyPressEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_KeyReleaseEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_MousePressEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseMoveEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseReleaseEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseDoubleClickEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_WheelEvent(QGraphicsItem* self, QGraphicsSceneWheelEvent* event);
void QGraphicsItem_InputMethodEvent(QGraphicsItem* self, QInputMethodEvent* event);
QVariant* QGraphicsItem_InputMethodQuery(const QGraphicsItem* self, int query);
QVariant* QGraphicsItem_ItemChange(QGraphicsItem* self, int change, QVariant* value);
bool QGraphicsItem_SupportsExtension(const QGraphicsItem* self, int extension);
void QGraphicsItem_SetExtension(QGraphicsItem* self, int extension, QVariant* variant);
QVariant* QGraphicsItem_Extension(const QGraphicsItem* self, QVariant* variant);
void QGraphicsItem_SetFlag2(QGraphicsItem* self, int flag, bool enabled);
void QGraphicsItem_SetCacheMode2(QGraphicsItem* self, int mode, QSize* cacheSize);
void QGraphicsItem_SetFocus1(QGraphicsItem* self, int focusReason);
void QGraphicsItem_EnsureVisible1(QGraphicsItem* self, QRectF* rect);
void QGraphicsItem_EnsureVisible22(QGraphicsItem* self, QRectF* rect, int xmargin);
void QGraphicsItem_EnsureVisible3(QGraphicsItem* self, QRectF* rect, int xmargin, int ymargin);
void QGraphicsItem_EnsureVisible5(QGraphicsItem* self, double x, double y, double w, double h, int xmargin);
void QGraphicsItem_EnsureVisible6(QGraphicsItem* self, double x, double y, double w, double h, int xmargin, int ymargin);
void QGraphicsItem_SetMatrix2(QGraphicsItem* self, QMatrix* matrix, bool combine);
QTransform* QGraphicsItem_ItemTransform2(const QGraphicsItem* self, QGraphicsItem* other, bool* ok);
void QGraphicsItem_SetTransform2(QGraphicsItem* self, QTransform* matrix, bool combine);
struct miqt_array /* of QGraphicsItem* */  QGraphicsItem_CollidingItems1(const QGraphicsItem* self, int mode);
bool QGraphicsItem_IsObscured1(const QGraphicsItem* self, QRectF* rect);
void QGraphicsItem_Update1(QGraphicsItem* self, QRectF* rect);
void QGraphicsItem_Scroll3(QGraphicsItem* self, double dx, double dy, QRectF* rect);
void QGraphicsItem_override_virtual_Advance(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_Advance(void* self, int phase);
void QGraphicsItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsItem_virtualbase_BoundingRect(const void* self);
void QGraphicsItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsItem_virtualbase_Shape(const void* self);
void QGraphicsItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsItem_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QGraphicsItem_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QGraphicsItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsItem_virtualbase_Type(const void* self);
void QGraphicsItem_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsItem_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsItem_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsItem_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsItem_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsItem_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsItem_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsItem_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsItem_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsItem_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsItem_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsItem_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsItem_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsItem_Delete(QGraphicsItem* self, bool isSubclass);

void QGraphicsObject_new(QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsObject_new2(QGraphicsItem* parent, QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
QMetaObject* QGraphicsObject_MetaObject(const QGraphicsObject* self);
void* QGraphicsObject_Metacast(QGraphicsObject* self, const char* param1);
struct miqt_string QGraphicsObject_Tr(const char* s);
struct miqt_string QGraphicsObject_TrUtf8(const char* s);
void QGraphicsObject_GrabGesture(QGraphicsObject* self, int typeVal);
void QGraphicsObject_UngrabGesture(QGraphicsObject* self, int typeVal);
void QGraphicsObject_ParentChanged(QGraphicsObject* self);
void QGraphicsObject_connect_ParentChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_OpacityChanged(QGraphicsObject* self);
void QGraphicsObject_connect_OpacityChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_VisibleChanged(QGraphicsObject* self);
void QGraphicsObject_connect_VisibleChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_EnabledChanged(QGraphicsObject* self);
void QGraphicsObject_connect_EnabledChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_XChanged(QGraphicsObject* self);
void QGraphicsObject_connect_XChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_YChanged(QGraphicsObject* self);
void QGraphicsObject_connect_YChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ZChanged(QGraphicsObject* self);
void QGraphicsObject_connect_ZChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_RotationChanged(QGraphicsObject* self);
void QGraphicsObject_connect_RotationChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ScaleChanged(QGraphicsObject* self);
void QGraphicsObject_connect_ScaleChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ChildrenChanged(QGraphicsObject* self);
void QGraphicsObject_connect_ChildrenChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_WidthChanged(QGraphicsObject* self);
void QGraphicsObject_connect_WidthChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_HeightChanged(QGraphicsObject* self);
void QGraphicsObject_connect_HeightChanged(QGraphicsObject* self, intptr_t slot);
bool QGraphicsObject_Event(QGraphicsObject* self, QEvent* ev);
struct miqt_string QGraphicsObject_Tr2(const char* s, const char* c);
struct miqt_string QGraphicsObject_Tr3(const char* s, const char* c, int n);
struct miqt_string QGraphicsObject_TrUtf82(const char* s, const char* c);
struct miqt_string QGraphicsObject_TrUtf83(const char* s, const char* c, int n);
void QGraphicsObject_GrabGesture2(QGraphicsObject* self, int typeVal, int flags);
void QGraphicsObject_override_virtual_Event(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_Event(void* self, QEvent* ev);
void QGraphicsObject_override_virtual_EventFilter(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_EventFilter(void* self, QObject* watched, QEvent* event);
void QGraphicsObject_override_virtual_TimerEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_TimerEvent(void* self, QTimerEvent* event);
void QGraphicsObject_override_virtual_ChildEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_ChildEvent(void* self, QChildEvent* event);
void QGraphicsObject_override_virtual_CustomEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_CustomEvent(void* self, QEvent* event);
void QGraphicsObject_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
void QGraphicsObject_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
void QGraphicsObject_override_virtual_Advance(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_Advance(void* self, int phase);
void QGraphicsObject_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsObject_virtualbase_BoundingRect(const void* self);
void QGraphicsObject_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsObject_virtualbase_Shape(const void* self);
void QGraphicsObject_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsObject_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QGraphicsObject_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QGraphicsObject_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsObject_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsObject_virtualbase_OpaqueArea(const void* self);
void QGraphicsObject_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsObject_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsObject_virtualbase_Type(const void* self);
void QGraphicsObject_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsObject_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsObject_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsObject_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsObject_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsObject_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsObject_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsObject_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsObject_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsObject_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsObject_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsObject_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsObject_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsObject_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsObject_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsObject_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsObject_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsObject_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsObject_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsObject_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsObject_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsObject_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsObject_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsObject_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsObject_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsObject_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsObject_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsObject_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsObject_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsObject_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsObject_Delete(QGraphicsObject* self, bool isSubclass);

void QAbstractGraphicsShapeItem_new(QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QAbstractGraphicsShapeItem_new2(QGraphicsItem* parent, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
QPen* QAbstractGraphicsShapeItem_Pen(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_SetPen(QAbstractGraphicsShapeItem* self, QPen* pen);
QBrush* QAbstractGraphicsShapeItem_Brush(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_SetBrush(QAbstractGraphicsShapeItem* self, QBrush* brush);
bool QAbstractGraphicsShapeItem_IsObscuredBy(const QAbstractGraphicsShapeItem* self, QGraphicsItem* item);
QPainterPath* QAbstractGraphicsShapeItem_OpaqueArea(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QAbstractGraphicsShapeItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QAbstractGraphicsShapeItem_virtualbase_OpaqueArea(const void* self);
void QAbstractGraphicsShapeItem_override_virtual_Advance(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_Advance(void* self, int phase);
void QAbstractGraphicsShapeItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QAbstractGraphicsShapeItem_virtualbase_BoundingRect(const void* self);
void QAbstractGraphicsShapeItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QAbstractGraphicsShapeItem_virtualbase_Shape(const void* self);
void QAbstractGraphicsShapeItem_override_virtual_Contains(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_Contains(const void* self, QPointF* point);
void QAbstractGraphicsShapeItem_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QAbstractGraphicsShapeItem_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QAbstractGraphicsShapeItem_override_virtual_Paint(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QAbstractGraphicsShapeItem_override_virtual_Type(void* self, intptr_t slot);
int QAbstractGraphicsShapeItem_virtualbase_Type(const void* self);
void QAbstractGraphicsShapeItem_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_SceneEvent(void* self, QEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_DropEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_WheelEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QAbstractGraphicsShapeItem_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QAbstractGraphicsShapeItem_virtualbase_InputMethodQuery(const void* self, int query);
void QAbstractGraphicsShapeItem_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QAbstractGraphicsShapeItem_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QAbstractGraphicsShapeItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_virtualbase_SupportsExtension(const void* self, int extension);
void QAbstractGraphicsShapeItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QAbstractGraphicsShapeItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QAbstractGraphicsShapeItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QAbstractGraphicsShapeItem_virtualbase_Extension(const void* self, QVariant* variant);
void QAbstractGraphicsShapeItem_Delete(QAbstractGraphicsShapeItem* self, bool isSubclass);

void QGraphicsPathItem_new(QGraphicsPathItem** outptr_QGraphicsPathItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPathItem_new2(QPainterPath* path, QGraphicsPathItem** outptr_QGraphicsPathItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPathItem_new3(QGraphicsItem* parent, QGraphicsPathItem** outptr_QGraphicsPathItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPathItem_new4(QPainterPath* path, QGraphicsItem* parent, QGraphicsPathItem** outptr_QGraphicsPathItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
QPainterPath* QGraphicsPathItem_Path(const QGraphicsPathItem* self);
void QGraphicsPathItem_SetPath(QGraphicsPathItem* self, QPainterPath* path);
QRectF* QGraphicsPathItem_BoundingRect(const QGraphicsPathItem* self);
QPainterPath* QGraphicsPathItem_Shape(const QGraphicsPathItem* self);
bool QGraphicsPathItem_Contains(const QGraphicsPathItem* self, QPointF* point);
void QGraphicsPathItem_Paint(QGraphicsPathItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPathItem_IsObscuredBy(const QGraphicsPathItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsPathItem_OpaqueArea(const QGraphicsPathItem* self);
int QGraphicsPathItem_Type(const QGraphicsPathItem* self);
bool QGraphicsPathItem_SupportsExtension(const QGraphicsPathItem* self, int extension);
void QGraphicsPathItem_SetExtension(QGraphicsPathItem* self, int extension, QVariant* variant);
QVariant* QGraphicsPathItem_Extension(const QGraphicsPathItem* self, QVariant* variant);
void QGraphicsPathItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsPathItem_virtualbase_BoundingRect(const void* self);
void QGraphicsPathItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsPathItem_virtualbase_Shape(const void* self);
void QGraphicsPathItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsPathItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsPathItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsPathItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPathItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsPathItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsPathItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsPathItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsPathItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsPathItem_virtualbase_Type(const void* self);
void QGraphicsPathItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsPathItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsPathItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsPathItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsPathItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsPathItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsPathItem_Delete(QGraphicsPathItem* self, bool isSubclass);

void QGraphicsRectItem_new(QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsRectItem_new2(QRectF* rect, QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsRectItem_new3(double x, double y, double w, double h, QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsRectItem_new4(QGraphicsItem* parent, QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsRectItem_new5(QRectF* rect, QGraphicsItem* parent, QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsRectItem_new6(double x, double y, double w, double h, QGraphicsItem* parent, QGraphicsRectItem** outptr_QGraphicsRectItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
QRectF* QGraphicsRectItem_Rect(const QGraphicsRectItem* self);
void QGraphicsRectItem_SetRect(QGraphicsRectItem* self, QRectF* rect);
void QGraphicsRectItem_SetRect2(QGraphicsRectItem* self, double x, double y, double w, double h);
QRectF* QGraphicsRectItem_BoundingRect(const QGraphicsRectItem* self);
QPainterPath* QGraphicsRectItem_Shape(const QGraphicsRectItem* self);
bool QGraphicsRectItem_Contains(const QGraphicsRectItem* self, QPointF* point);
void QGraphicsRectItem_Paint(QGraphicsRectItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsRectItem_IsObscuredBy(const QGraphicsRectItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsRectItem_OpaqueArea(const QGraphicsRectItem* self);
int QGraphicsRectItem_Type(const QGraphicsRectItem* self);
bool QGraphicsRectItem_SupportsExtension(const QGraphicsRectItem* self, int extension);
void QGraphicsRectItem_SetExtension(QGraphicsRectItem* self, int extension, QVariant* variant);
QVariant* QGraphicsRectItem_Extension(const QGraphicsRectItem* self, QVariant* variant);
void QGraphicsRectItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsRectItem_virtualbase_BoundingRect(const void* self);
void QGraphicsRectItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsRectItem_virtualbase_Shape(const void* self);
void QGraphicsRectItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsRectItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsRectItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsRectItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsRectItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsRectItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsRectItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsRectItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsRectItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsRectItem_virtualbase_Type(const void* self);
void QGraphicsRectItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsRectItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsRectItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsRectItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsRectItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsRectItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsRectItem_Delete(QGraphicsRectItem* self, bool isSubclass);

void QGraphicsEllipseItem_new(QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsEllipseItem_new2(QRectF* rect, QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsEllipseItem_new3(double x, double y, double w, double h, QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsEllipseItem_new4(QGraphicsItem* parent, QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsEllipseItem_new5(QRectF* rect, QGraphicsItem* parent, QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsEllipseItem_new6(double x, double y, double w, double h, QGraphicsItem* parent, QGraphicsEllipseItem** outptr_QGraphicsEllipseItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
QRectF* QGraphicsEllipseItem_Rect(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetRect(QGraphicsEllipseItem* self, QRectF* rect);
void QGraphicsEllipseItem_SetRect2(QGraphicsEllipseItem* self, double x, double y, double w, double h);
int QGraphicsEllipseItem_StartAngle(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetStartAngle(QGraphicsEllipseItem* self, int angle);
int QGraphicsEllipseItem_SpanAngle(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetSpanAngle(QGraphicsEllipseItem* self, int angle);
QRectF* QGraphicsEllipseItem_BoundingRect(const QGraphicsEllipseItem* self);
QPainterPath* QGraphicsEllipseItem_Shape(const QGraphicsEllipseItem* self);
bool QGraphicsEllipseItem_Contains(const QGraphicsEllipseItem* self, QPointF* point);
void QGraphicsEllipseItem_Paint(QGraphicsEllipseItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsEllipseItem_IsObscuredBy(const QGraphicsEllipseItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsEllipseItem_OpaqueArea(const QGraphicsEllipseItem* self);
int QGraphicsEllipseItem_Type(const QGraphicsEllipseItem* self);
bool QGraphicsEllipseItem_SupportsExtension(const QGraphicsEllipseItem* self, int extension);
void QGraphicsEllipseItem_SetExtension(QGraphicsEllipseItem* self, int extension, QVariant* variant);
QVariant* QGraphicsEllipseItem_Extension(const QGraphicsEllipseItem* self, QVariant* variant);
void QGraphicsEllipseItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsEllipseItem_virtualbase_BoundingRect(const void* self);
void QGraphicsEllipseItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsEllipseItem_virtualbase_Shape(const void* self);
void QGraphicsEllipseItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsEllipseItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsEllipseItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsEllipseItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsEllipseItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsEllipseItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsEllipseItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsEllipseItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsEllipseItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsEllipseItem_virtualbase_Type(const void* self);
void QGraphicsEllipseItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsEllipseItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsEllipseItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsEllipseItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsEllipseItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsEllipseItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsEllipseItem_Delete(QGraphicsEllipseItem* self, bool isSubclass);

void QGraphicsPolygonItem_new(QGraphicsPolygonItem** outptr_QGraphicsPolygonItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPolygonItem_new2(QGraphicsItem* parent, QGraphicsPolygonItem** outptr_QGraphicsPolygonItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
int QGraphicsPolygonItem_FillRule(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_SetFillRule(QGraphicsPolygonItem* self, int rule);
QRectF* QGraphicsPolygonItem_BoundingRect(const QGraphicsPolygonItem* self);
QPainterPath* QGraphicsPolygonItem_Shape(const QGraphicsPolygonItem* self);
bool QGraphicsPolygonItem_Contains(const QGraphicsPolygonItem* self, QPointF* point);
void QGraphicsPolygonItem_Paint(QGraphicsPolygonItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPolygonItem_IsObscuredBy(const QGraphicsPolygonItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsPolygonItem_OpaqueArea(const QGraphicsPolygonItem* self);
int QGraphicsPolygonItem_Type(const QGraphicsPolygonItem* self);
bool QGraphicsPolygonItem_SupportsExtension(const QGraphicsPolygonItem* self, int extension);
void QGraphicsPolygonItem_SetExtension(QGraphicsPolygonItem* self, int extension, QVariant* variant);
QVariant* QGraphicsPolygonItem_Extension(const QGraphicsPolygonItem* self, QVariant* variant);
void QGraphicsPolygonItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsPolygonItem_virtualbase_BoundingRect(const void* self);
void QGraphicsPolygonItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsPolygonItem_virtualbase_Shape(const void* self);
void QGraphicsPolygonItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsPolygonItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsPolygonItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsPolygonItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPolygonItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsPolygonItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsPolygonItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsPolygonItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsPolygonItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsPolygonItem_virtualbase_Type(const void* self);
void QGraphicsPolygonItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsPolygonItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsPolygonItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsPolygonItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsPolygonItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsPolygonItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsPolygonItem_Delete(QGraphicsPolygonItem* self, bool isSubclass);

void QGraphicsLineItem_new(QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsLineItem_new2(QLineF* line, QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsLineItem_new3(double x1, double y1, double x2, double y2, QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsLineItem_new4(QGraphicsItem* parent, QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsLineItem_new5(QLineF* line, QGraphicsItem* parent, QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsLineItem_new6(double x1, double y1, double x2, double y2, QGraphicsItem* parent, QGraphicsLineItem** outptr_QGraphicsLineItem, QGraphicsItem** outptr_QGraphicsItem);
QPen* QGraphicsLineItem_Pen(const QGraphicsLineItem* self);
void QGraphicsLineItem_SetPen(QGraphicsLineItem* self, QPen* pen);
QLineF* QGraphicsLineItem_Line(const QGraphicsLineItem* self);
void QGraphicsLineItem_SetLine(QGraphicsLineItem* self, QLineF* line);
void QGraphicsLineItem_SetLine2(QGraphicsLineItem* self, double x1, double y1, double x2, double y2);
QRectF* QGraphicsLineItem_BoundingRect(const QGraphicsLineItem* self);
QPainterPath* QGraphicsLineItem_Shape(const QGraphicsLineItem* self);
bool QGraphicsLineItem_Contains(const QGraphicsLineItem* self, QPointF* point);
void QGraphicsLineItem_Paint(QGraphicsLineItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsLineItem_IsObscuredBy(const QGraphicsLineItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsLineItem_OpaqueArea(const QGraphicsLineItem* self);
int QGraphicsLineItem_Type(const QGraphicsLineItem* self);
bool QGraphicsLineItem_SupportsExtension(const QGraphicsLineItem* self, int extension);
void QGraphicsLineItem_SetExtension(QGraphicsLineItem* self, int extension, QVariant* variant);
QVariant* QGraphicsLineItem_Extension(const QGraphicsLineItem* self, QVariant* variant);
void QGraphicsLineItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsLineItem_virtualbase_BoundingRect(const void* self);
void QGraphicsLineItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsLineItem_virtualbase_Shape(const void* self);
void QGraphicsLineItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsLineItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsLineItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsLineItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsLineItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsLineItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsLineItem_virtualbase_Type(const void* self);
void QGraphicsLineItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsLineItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsLineItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsLineItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsLineItem_override_virtual_Advance(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_Advance(void* self, int phase);
void QGraphicsLineItem_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QGraphicsLineItem_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QGraphicsLineItem_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsLineItem_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsLineItem_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsLineItem_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsLineItem_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsLineItem_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsLineItem_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsLineItem_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsLineItem_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsLineItem_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsLineItem_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsLineItem_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsLineItem_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsLineItem_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsLineItem_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsLineItem_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsLineItem_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsLineItem_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsLineItem_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsLineItem_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsLineItem_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsLineItem_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsLineItem_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsLineItem_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsLineItem_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsLineItem_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsLineItem_Delete(QGraphicsLineItem* self, bool isSubclass);

void QGraphicsPixmapItem_new(QGraphicsPixmapItem** outptr_QGraphicsPixmapItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPixmapItem_new2(QPixmap* pixmap, QGraphicsPixmapItem** outptr_QGraphicsPixmapItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPixmapItem_new3(QGraphicsItem* parent, QGraphicsPixmapItem** outptr_QGraphicsPixmapItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsPixmapItem_new4(QPixmap* pixmap, QGraphicsItem* parent, QGraphicsPixmapItem** outptr_QGraphicsPixmapItem, QGraphicsItem** outptr_QGraphicsItem);
QPixmap* QGraphicsPixmapItem_Pixmap(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetPixmap(QGraphicsPixmapItem* self, QPixmap* pixmap);
int QGraphicsPixmapItem_TransformationMode(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetTransformationMode(QGraphicsPixmapItem* self, int mode);
QPointF* QGraphicsPixmapItem_Offset(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetOffset(QGraphicsPixmapItem* self, QPointF* offset);
void QGraphicsPixmapItem_SetOffset2(QGraphicsPixmapItem* self, double x, double y);
QRectF* QGraphicsPixmapItem_BoundingRect(const QGraphicsPixmapItem* self);
QPainterPath* QGraphicsPixmapItem_Shape(const QGraphicsPixmapItem* self);
bool QGraphicsPixmapItem_Contains(const QGraphicsPixmapItem* self, QPointF* point);
void QGraphicsPixmapItem_Paint(QGraphicsPixmapItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPixmapItem_IsObscuredBy(const QGraphicsPixmapItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsPixmapItem_OpaqueArea(const QGraphicsPixmapItem* self);
int QGraphicsPixmapItem_Type(const QGraphicsPixmapItem* self);
int QGraphicsPixmapItem_ShapeMode(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetShapeMode(QGraphicsPixmapItem* self, int mode);
bool QGraphicsPixmapItem_SupportsExtension(const QGraphicsPixmapItem* self, int extension);
void QGraphicsPixmapItem_SetExtension(QGraphicsPixmapItem* self, int extension, QVariant* variant);
QVariant* QGraphicsPixmapItem_Extension(const QGraphicsPixmapItem* self, QVariant* variant);
void QGraphicsPixmapItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsPixmapItem_virtualbase_BoundingRect(const void* self);
void QGraphicsPixmapItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsPixmapItem_virtualbase_Shape(const void* self);
void QGraphicsPixmapItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsPixmapItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPixmapItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsPixmapItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsPixmapItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsPixmapItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsPixmapItem_virtualbase_Type(const void* self);
void QGraphicsPixmapItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsPixmapItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsPixmapItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsPixmapItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsPixmapItem_override_virtual_Advance(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_Advance(void* self, int phase);
void QGraphicsPixmapItem_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QGraphicsPixmapItem_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QGraphicsPixmapItem_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsPixmapItem_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsPixmapItem_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsPixmapItem_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsPixmapItem_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsPixmapItem_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsPixmapItem_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsPixmapItem_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsPixmapItem_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsPixmapItem_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsPixmapItem_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsPixmapItem_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsPixmapItem_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsPixmapItem_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsPixmapItem_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsPixmapItem_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsPixmapItem_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsPixmapItem_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsPixmapItem_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsPixmapItem_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsPixmapItem_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsPixmapItem_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsPixmapItem_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsPixmapItem_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsPixmapItem_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsPixmapItem_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsPixmapItem_Delete(QGraphicsPixmapItem* self, bool isSubclass);

void QGraphicsTextItem_new(QGraphicsTextItem** outptr_QGraphicsTextItem, QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsTextItem_new2(struct miqt_string text, QGraphicsTextItem** outptr_QGraphicsTextItem, QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsTextItem_new3(QGraphicsItem* parent, QGraphicsTextItem** outptr_QGraphicsTextItem, QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsTextItem_new4(struct miqt_string text, QGraphicsItem* parent, QGraphicsTextItem** outptr_QGraphicsTextItem, QGraphicsObject** outptr_QGraphicsObject, QObject** outptr_QObject, QGraphicsItem** outptr_QGraphicsItem);
QMetaObject* QGraphicsTextItem_MetaObject(const QGraphicsTextItem* self);
void* QGraphicsTextItem_Metacast(QGraphicsTextItem* self, const char* param1);
struct miqt_string QGraphicsTextItem_Tr(const char* s);
struct miqt_string QGraphicsTextItem_TrUtf8(const char* s);
struct miqt_string QGraphicsTextItem_ToHtml(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetHtml(QGraphicsTextItem* self, struct miqt_string html);
struct miqt_string QGraphicsTextItem_ToPlainText(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetPlainText(QGraphicsTextItem* self, struct miqt_string text);
QFont* QGraphicsTextItem_Font(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetFont(QGraphicsTextItem* self, QFont* font);
void QGraphicsTextItem_SetDefaultTextColor(QGraphicsTextItem* self, QColor* c);
QColor* QGraphicsTextItem_DefaultTextColor(const QGraphicsTextItem* self);
QRectF* QGraphicsTextItem_BoundingRect(const QGraphicsTextItem* self);
QPainterPath* QGraphicsTextItem_Shape(const QGraphicsTextItem* self);
bool QGraphicsTextItem_Contains(const QGraphicsTextItem* self, QPointF* point);
void QGraphicsTextItem_Paint(QGraphicsTextItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsTextItem_IsObscuredBy(const QGraphicsTextItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsTextItem_OpaqueArea(const QGraphicsTextItem* self);
int QGraphicsTextItem_Type(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextWidth(QGraphicsTextItem* self, double width);
double QGraphicsTextItem_TextWidth(const QGraphicsTextItem* self);
void QGraphicsTextItem_AdjustSize(QGraphicsTextItem* self);
void QGraphicsTextItem_SetDocument(QGraphicsTextItem* self, QTextDocument* document);
QTextDocument* QGraphicsTextItem_Document(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextInteractionFlags(QGraphicsTextItem* self, int flags);
int QGraphicsTextItem_TextInteractionFlags(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTabChangesFocus(QGraphicsTextItem* self, bool b);
bool QGraphicsTextItem_TabChangesFocus(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetOpenExternalLinks(QGraphicsTextItem* self, bool open);
bool QGraphicsTextItem_OpenExternalLinks(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextCursor(QGraphicsTextItem* self, QTextCursor* cursor);
QTextCursor* QGraphicsTextItem_TextCursor(const QGraphicsTextItem* self);
void QGraphicsTextItem_LinkActivated(QGraphicsTextItem* self, struct miqt_string param1);
void QGraphicsTextItem_connect_LinkActivated(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_LinkHovered(QGraphicsTextItem* self, struct miqt_string param1);
void QGraphicsTextItem_connect_LinkHovered(QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_SceneEvent(QGraphicsTextItem* self, QEvent* event);
void QGraphicsTextItem_MousePressEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseMoveEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseReleaseEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseDoubleClickEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_ContextMenuEvent(QGraphicsTextItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsTextItem_KeyPressEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_KeyReleaseEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_FocusInEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_FocusOutEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_DragEnterEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DragLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DragMoveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DropEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_InputMethodEvent(QGraphicsTextItem* self, QInputMethodEvent* event);
void QGraphicsTextItem_HoverEnterEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_HoverMoveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_HoverLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
QVariant* QGraphicsTextItem_InputMethodQuery(const QGraphicsTextItem* self, int query);
bool QGraphicsTextItem_SupportsExtension(const QGraphicsTextItem* self, int extension);
void QGraphicsTextItem_SetExtension(QGraphicsTextItem* self, int extension, QVariant* variant);
QVariant* QGraphicsTextItem_Extension(const QGraphicsTextItem* self, QVariant* variant);
struct miqt_string QGraphicsTextItem_Tr2(const char* s, const char* c);
struct miqt_string QGraphicsTextItem_Tr3(const char* s, const char* c, int n);
struct miqt_string QGraphicsTextItem_TrUtf82(const char* s, const char* c);
struct miqt_string QGraphicsTextItem_TrUtf83(const char* s, const char* c, int n);
void QGraphicsTextItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsTextItem_virtualbase_BoundingRect(const void* self);
void QGraphicsTextItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsTextItem_virtualbase_Shape(const void* self);
void QGraphicsTextItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsTextItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsTextItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsTextItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsTextItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsTextItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsTextItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsTextItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsTextItem_virtualbase_Type(const void* self);
void QGraphicsTextItem_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsTextItem_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsTextItem_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsTextItem_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsTextItem_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsTextItem_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsTextItem_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsTextItem_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsTextItem_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsTextItem_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsTextItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsTextItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsTextItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsTextItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsTextItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsTextItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsTextItem_override_virtual_Event(void* self, intptr_t slot);
bool QGraphicsTextItem_virtualbase_Event(void* self, QEvent* ev);
void QGraphicsTextItem_Delete(QGraphicsTextItem* self, bool isSubclass);

void QGraphicsSimpleTextItem_new(QGraphicsSimpleTextItem** outptr_QGraphicsSimpleTextItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsSimpleTextItem_new2(struct miqt_string text, QGraphicsSimpleTextItem** outptr_QGraphicsSimpleTextItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsSimpleTextItem_new3(QGraphicsItem* parent, QGraphicsSimpleTextItem** outptr_QGraphicsSimpleTextItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsSimpleTextItem_new4(struct miqt_string text, QGraphicsItem* parent, QGraphicsSimpleTextItem** outptr_QGraphicsSimpleTextItem, QAbstractGraphicsShapeItem** outptr_QAbstractGraphicsShapeItem, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsSimpleTextItem_SetText(QGraphicsSimpleTextItem* self, struct miqt_string text);
struct miqt_string QGraphicsSimpleTextItem_Text(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_SetFont(QGraphicsSimpleTextItem* self, QFont* font);
QFont* QGraphicsSimpleTextItem_Font(const QGraphicsSimpleTextItem* self);
QRectF* QGraphicsSimpleTextItem_BoundingRect(const QGraphicsSimpleTextItem* self);
QPainterPath* QGraphicsSimpleTextItem_Shape(const QGraphicsSimpleTextItem* self);
bool QGraphicsSimpleTextItem_Contains(const QGraphicsSimpleTextItem* self, QPointF* point);
void QGraphicsSimpleTextItem_Paint(QGraphicsSimpleTextItem* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsSimpleTextItem_IsObscuredBy(const QGraphicsSimpleTextItem* self, QGraphicsItem* item);
QPainterPath* QGraphicsSimpleTextItem_OpaqueArea(const QGraphicsSimpleTextItem* self);
int QGraphicsSimpleTextItem_Type(const QGraphicsSimpleTextItem* self);
bool QGraphicsSimpleTextItem_SupportsExtension(const QGraphicsSimpleTextItem* self, int extension);
void QGraphicsSimpleTextItem_SetExtension(QGraphicsSimpleTextItem* self, int extension, QVariant* variant);
QVariant* QGraphicsSimpleTextItem_Extension(const QGraphicsSimpleTextItem* self, QVariant* variant);
void QGraphicsSimpleTextItem_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsSimpleTextItem_virtualbase_BoundingRect(const void* self);
void QGraphicsSimpleTextItem_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsSimpleTextItem_virtualbase_Shape(const void* self);
void QGraphicsSimpleTextItem_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsSimpleTextItem_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsSimpleTextItem_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsSimpleTextItem_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsSimpleTextItem_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsSimpleTextItem_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsSimpleTextItem_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsSimpleTextItem_virtualbase_OpaqueArea(const void* self);
void QGraphicsSimpleTextItem_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsSimpleTextItem_virtualbase_Type(const void* self);
void QGraphicsSimpleTextItem_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsSimpleTextItem_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsSimpleTextItem_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsSimpleTextItem_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsSimpleTextItem_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsSimpleTextItem_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsSimpleTextItem_Delete(QGraphicsSimpleTextItem* self, bool isSubclass);

void QGraphicsItemGroup_new(QGraphicsItemGroup** outptr_QGraphicsItemGroup, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsItemGroup_new2(QGraphicsItem* parent, QGraphicsItemGroup** outptr_QGraphicsItemGroup, QGraphicsItem** outptr_QGraphicsItem);
void QGraphicsItemGroup_AddToGroup(QGraphicsItemGroup* self, QGraphicsItem* item);
void QGraphicsItemGroup_RemoveFromGroup(QGraphicsItemGroup* self, QGraphicsItem* item);
QRectF* QGraphicsItemGroup_BoundingRect(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_Paint(QGraphicsItemGroup* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsItemGroup_IsObscuredBy(const QGraphicsItemGroup* self, QGraphicsItem* item);
QPainterPath* QGraphicsItemGroup_OpaqueArea(const QGraphicsItemGroup* self);
int QGraphicsItemGroup_Type(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_override_virtual_BoundingRect(void* self, intptr_t slot);
QRectF* QGraphicsItemGroup_virtualbase_BoundingRect(const void* self);
void QGraphicsItemGroup_override_virtual_Paint(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_Paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItemGroup_override_virtual_IsObscuredBy(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_IsObscuredBy(const void* self, QGraphicsItem* item);
void QGraphicsItemGroup_override_virtual_OpaqueArea(void* self, intptr_t slot);
QPainterPath* QGraphicsItemGroup_virtualbase_OpaqueArea(const void* self);
void QGraphicsItemGroup_override_virtual_Type(void* self, intptr_t slot);
int QGraphicsItemGroup_virtualbase_Type(const void* self);
void QGraphicsItemGroup_override_virtual_Advance(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_Advance(void* self, int phase);
void QGraphicsItemGroup_override_virtual_Shape(void* self, intptr_t slot);
QPainterPath* QGraphicsItemGroup_virtualbase_Shape(const void* self);
void QGraphicsItemGroup_override_virtual_Contains(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_Contains(const void* self, QPointF* point);
void QGraphicsItemGroup_override_virtual_CollidesWithItem(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_CollidesWithItem(const void* self, QGraphicsItem* other, int mode);
void QGraphicsItemGroup_override_virtual_CollidesWithPath(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_CollidesWithPath(const void* self, QPainterPath* path, int mode);
void QGraphicsItemGroup_override_virtual_SceneEventFilter(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_SceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsItemGroup_override_virtual_SceneEvent(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_SceneEvent(void* self, QEvent* event);
void QGraphicsItemGroup_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_ContextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsItemGroup_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_DragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItemGroup_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_DragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItemGroup_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_DragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItemGroup_override_virtual_DropEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_DropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItemGroup_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
void QGraphicsItemGroup_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
void QGraphicsItemGroup_override_virtual_HoverEnterEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_HoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItemGroup_override_virtual_HoverMoveEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_HoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItemGroup_override_virtual_HoverLeaveEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_HoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItemGroup_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
void QGraphicsItemGroup_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsItemGroup_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_MousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItemGroup_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_MouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItemGroup_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_MouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItemGroup_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_MouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItemGroup_override_virtual_WheelEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_WheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsItemGroup_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
void QGraphicsItemGroup_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QGraphicsItemGroup_virtualbase_InputMethodQuery(const void* self, int query);
void QGraphicsItemGroup_override_virtual_ItemChange(void* self, intptr_t slot);
QVariant* QGraphicsItemGroup_virtualbase_ItemChange(void* self, int change, QVariant* value);
void QGraphicsItemGroup_override_virtual_SupportsExtension(void* self, intptr_t slot);
bool QGraphicsItemGroup_virtualbase_SupportsExtension(const void* self, int extension);
void QGraphicsItemGroup_override_virtual_SetExtension(void* self, intptr_t slot);
void QGraphicsItemGroup_virtualbase_SetExtension(void* self, int extension, QVariant* variant);
void QGraphicsItemGroup_override_virtual_Extension(void* self, intptr_t slot);
QVariant* QGraphicsItemGroup_virtualbase_Extension(const void* self, QVariant* variant);
void QGraphicsItemGroup_Delete(QGraphicsItemGroup* self, bool isSubclass);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
