#pragma once
#ifndef MIQT_QT_GEN_QUNDOVIEW_H
#define MIQT_QT_GEN_QUNDOVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QListView;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QUndoGroup;
class QUndoStack;
class QUndoView;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QListView QListView;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUndoGroup QUndoGroup;
typedef struct QUndoStack QUndoStack;
typedef struct QUndoView QUndoView;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QUndoView* QUndoView_new(QWidget* parent);
QUndoView* QUndoView_new2();
QUndoView* QUndoView_new3(QUndoStack* stack);
QUndoView* QUndoView_new4(QUndoGroup* group);
QUndoView* QUndoView_new5(QUndoStack* stack, QWidget* parent);
QUndoView* QUndoView_new6(QUndoGroup* group, QWidget* parent);
void QUndoView_virtbase(QUndoView* src, QListView** outptr_QListView);
QMetaObject* QUndoView_MetaObject(const QUndoView* self);
void* QUndoView_Metacast(QUndoView* self, const char* param1);
struct miqt_string QUndoView_Tr(const char* s);
struct miqt_string QUndoView_TrUtf8(const char* s);
QUndoStack* QUndoView_Stack(const QUndoView* self);
QUndoGroup* QUndoView_Group(const QUndoView* self);
void QUndoView_SetEmptyLabel(QUndoView* self, struct miqt_string label);
struct miqt_string QUndoView_EmptyLabel(const QUndoView* self);
void QUndoView_SetCleanIcon(QUndoView* self, QIcon* icon);
QIcon* QUndoView_CleanIcon(const QUndoView* self);
void QUndoView_SetStack(QUndoView* self, QUndoStack* stack);
void QUndoView_SetGroup(QUndoView* self, QUndoGroup* group);
struct miqt_string QUndoView_Tr2(const char* s, const char* c);
struct miqt_string QUndoView_Tr3(const char* s, const char* c, int n);
struct miqt_string QUndoView_TrUtf82(const char* s, const char* c);
struct miqt_string QUndoView_TrUtf83(const char* s, const char* c, int n);
bool QUndoView_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QUndoView_virtualbase_VisualRect(const void* self, QModelIndex* index);
bool QUndoView_override_virtual_ScrollTo(void* self, intptr_t slot);
void QUndoView_virtualbase_ScrollTo(void* self, QModelIndex* index, int hint);
bool QUndoView_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QUndoView_virtualbase_IndexAt(const void* self, QPoint* p);
bool QUndoView_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QUndoView_virtualbase_DoItemsLayout(void* self);
bool QUndoView_override_virtual_Reset(void* self, intptr_t slot);
void QUndoView_virtualbase_Reset(void* self);
bool QUndoView_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QUndoView_virtualbase_SetRootIndex(void* self, QModelIndex* index);
bool QUndoView_override_virtual_Event(void* self, intptr_t slot);
bool QUndoView_virtualbase_Event(void* self, QEvent* e);
bool QUndoView_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QUndoView_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
bool QUndoView_override_virtual_DataChanged(void* self, intptr_t slot);
void QUndoView_virtualbase_DataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
bool QUndoView_override_virtual_RowsInserted(void* self, intptr_t slot);
void QUndoView_virtualbase_RowsInserted(void* self, QModelIndex* parent, int start, int end);
bool QUndoView_override_virtual_RowsAboutToBeRemoved(void* self, intptr_t slot);
void QUndoView_virtualbase_RowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
bool QUndoView_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_MouseMoveEvent(void* self, QMouseEvent* e);
bool QUndoView_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* e);
bool QUndoView_override_virtual_WheelEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_WheelEvent(void* self, QWheelEvent* e);
bool QUndoView_override_virtual_TimerEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_TimerEvent(void* self, QTimerEvent* e);
bool QUndoView_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ResizeEvent(void* self, QResizeEvent* e);
bool QUndoView_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* e);
bool QUndoView_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* e);
bool QUndoView_override_virtual_DropEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_DropEvent(void* self, QDropEvent* e);
bool QUndoView_override_virtual_StartDrag(void* self, intptr_t slot);
void QUndoView_virtualbase_StartDrag(void* self, int supportedActions);
bool QUndoView_override_virtual_ViewOptions(void* self, intptr_t slot);
QStyleOptionViewItem* QUndoView_virtualbase_ViewOptions(const void* self);
bool QUndoView_override_virtual_PaintEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_PaintEvent(void* self, QPaintEvent* e);
bool QUndoView_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QUndoView_virtualbase_HorizontalOffset(const void* self);
bool QUndoView_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QUndoView_virtualbase_VerticalOffset(const void* self);
bool QUndoView_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QUndoView_virtualbase_MoveCursor(void* self, int cursorAction, int modifiers);
bool QUndoView_override_virtual_SetSelection(void* self, intptr_t slot);
void QUndoView_virtualbase_SetSelection(void* self, QRect* rect, int command);
bool QUndoView_override_virtual_VisualRegionForSelection(void* self, intptr_t slot);
QRegion* QUndoView_virtualbase_VisualRegionForSelection(const void* self, QItemSelection* selection);
bool QUndoView_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QUndoView_virtualbase_SelectedIndexes(const void* self);
bool QUndoView_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QUndoView_virtualbase_UpdateGeometries(void* self);
bool QUndoView_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QUndoView_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
bool QUndoView_override_virtual_SelectionChanged(void* self, intptr_t slot);
void QUndoView_virtualbase_SelectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
bool QUndoView_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QUndoView_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
bool QUndoView_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QUndoView_virtualbase_ViewportSizeHint(const void* self);
bool QUndoView_override_virtual_SetModel(void* self, intptr_t slot);
void QUndoView_virtualbase_SetModel(void* self, QAbstractItemModel* model);
bool QUndoView_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QUndoView_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
bool QUndoView_override_virtual_KeyboardSearch(void* self, intptr_t slot);
void QUndoView_virtualbase_KeyboardSearch(void* self, struct miqt_string search);
bool QUndoView_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QUndoView_virtualbase_SizeHintForRow(const void* self, int row);
bool QUndoView_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QUndoView_virtualbase_SizeHintForColumn(const void* self, int column);
bool QUndoView_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QUndoView_virtualbase_InputMethodQuery(const void* self, int query);
bool QUndoView_override_virtual_SelectAll(void* self, intptr_t slot);
void QUndoView_virtualbase_SelectAll(void* self);
bool QUndoView_override_virtual_UpdateEditorData(void* self, intptr_t slot);
void QUndoView_virtualbase_UpdateEditorData(void* self);
bool QUndoView_override_virtual_UpdateEditorGeometries(void* self, intptr_t slot);
void QUndoView_virtualbase_UpdateEditorGeometries(void* self);
bool QUndoView_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QUndoView_virtualbase_VerticalScrollbarAction(void* self, int action);
bool QUndoView_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QUndoView_virtualbase_HorizontalScrollbarAction(void* self, int action);
bool QUndoView_override_virtual_VerticalScrollbarValueChanged(void* self, intptr_t slot);
void QUndoView_virtualbase_VerticalScrollbarValueChanged(void* self, int value);
bool QUndoView_override_virtual_HorizontalScrollbarValueChanged(void* self, intptr_t slot);
void QUndoView_virtualbase_HorizontalScrollbarValueChanged(void* self, int value);
bool QUndoView_override_virtual_CloseEditor(void* self, intptr_t slot);
void QUndoView_virtualbase_CloseEditor(void* self, QWidget* editor, int hint);
bool QUndoView_override_virtual_CommitData(void* self, intptr_t slot);
void QUndoView_virtualbase_CommitData(void* self, QWidget* editor);
bool QUndoView_override_virtual_EditorDestroyed(void* self, intptr_t slot);
void QUndoView_virtualbase_EditorDestroyed(void* self, QObject* editor);
bool QUndoView_override_virtual_Edit2(void* self, intptr_t slot);
bool QUndoView_virtualbase_Edit2(void* self, QModelIndex* index, int trigger, QEvent* event);
bool QUndoView_override_virtual_SelectionCommand(void* self, intptr_t slot);
int QUndoView_virtualbase_SelectionCommand(const void* self, QModelIndex* index, QEvent* event);
bool QUndoView_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QUndoView_virtualbase_FocusNextPrevChild(void* self, bool next);
bool QUndoView_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QUndoView_virtualbase_ViewportEvent(void* self, QEvent* event);
bool QUndoView_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
bool QUndoView_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QUndoView_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
bool QUndoView_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
bool QUndoView_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
bool QUndoView_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
bool QUndoView_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* event);
bool QUndoView_override_virtual_EventFilter(void* self, intptr_t slot);
bool QUndoView_virtualbase_EventFilter(void* self, QObject* object, QEvent* event);
bool QUndoView_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QUndoView_virtualbase_MinimumSizeHint(const void* self);
bool QUndoView_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QUndoView_virtualbase_SizeHint(const void* self);
bool QUndoView_override_virtual_SetupViewport(void* self, intptr_t slot);
void QUndoView_virtualbase_SetupViewport(void* self, QWidget* viewport);
bool QUndoView_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* param1);
bool QUndoView_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ChangeEvent(void* self, QEvent* param1);
bool QUndoView_override_virtual_DevType(void* self, intptr_t slot);
int QUndoView_virtualbase_DevType(const void* self);
bool QUndoView_override_virtual_SetVisible(void* self, intptr_t slot);
void QUndoView_virtualbase_SetVisible(void* self, bool visible);
bool QUndoView_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QUndoView_virtualbase_HeightForWidth(const void* self, int param1);
bool QUndoView_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QUndoView_virtualbase_HasHeightForWidth(const void* self);
bool QUndoView_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QUndoView_virtualbase_PaintEngine(const void* self);
bool QUndoView_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
bool QUndoView_override_virtual_EnterEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_EnterEvent(void* self, QEvent* event);
bool QUndoView_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_LeaveEvent(void* self, QEvent* event);
bool QUndoView_override_virtual_MoveEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_MoveEvent(void* self, QMoveEvent* event);
bool QUndoView_override_virtual_CloseEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_CloseEvent(void* self, QCloseEvent* event);
bool QUndoView_override_virtual_TabletEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_TabletEvent(void* self, QTabletEvent* event);
bool QUndoView_override_virtual_ActionEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ActionEvent(void* self, QActionEvent* event);
bool QUndoView_override_virtual_ShowEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ShowEvent(void* self, QShowEvent* event);
bool QUndoView_override_virtual_HideEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_HideEvent(void* self, QHideEvent* event);
bool QUndoView_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QUndoView_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
bool QUndoView_override_virtual_Metric(void* self, intptr_t slot);
int QUndoView_virtualbase_Metric(const void* self, int param1);
bool QUndoView_override_virtual_InitPainter(void* self, intptr_t slot);
void QUndoView_virtualbase_InitPainter(const void* self, QPainter* painter);
bool QUndoView_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QUndoView_virtualbase_Redirected(const void* self, QPoint* offset);
bool QUndoView_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QUndoView_virtualbase_SharedPainter(const void* self);
bool QUndoView_override_virtual_ChildEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_ChildEvent(void* self, QChildEvent* event);
bool QUndoView_override_virtual_CustomEvent(void* self, intptr_t slot);
void QUndoView_virtualbase_CustomEvent(void* self, QEvent* event);
bool QUndoView_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QUndoView_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
bool QUndoView_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QUndoView_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
void QUndoView_Delete(QUndoView* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
