#pragma once
#ifndef MIQT_QT_GEN_QMESSAGEBOX_H
#define MIQT_QT_GEN_QMESSAGEBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractButton;
class QActionEvent;
class QCheckBox;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDialog;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMessageBox;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPixmap;
class QPoint;
class QPushButton;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractButton QAbstractButton;
typedef struct QActionEvent QActionEvent;
typedef struct QCheckBox QCheckBox;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMessageBox QMessageBox;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPushButton QPushButton;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QMessageBox* QMessageBox_new(QWidget* parent);
QMessageBox* QMessageBox_new2();
QMessageBox* QMessageBox_new3(int icon, struct miqt_string title, struct miqt_string text);
QMessageBox* QMessageBox_new4(struct miqt_string title, struct miqt_string text, int icon, int button0, int button1, int button2);
QMessageBox* QMessageBox_new5(int icon, struct miqt_string title, struct miqt_string text, int buttons);
QMessageBox* QMessageBox_new6(int icon, struct miqt_string title, struct miqt_string text, int buttons, QWidget* parent);
QMessageBox* QMessageBox_new7(int icon, struct miqt_string title, struct miqt_string text, int buttons, QWidget* parent, int flags);
QMessageBox* QMessageBox_new8(struct miqt_string title, struct miqt_string text, int icon, int button0, int button1, int button2, QWidget* parent);
QMessageBox* QMessageBox_new9(struct miqt_string title, struct miqt_string text, int icon, int button0, int button1, int button2, QWidget* parent, int f);
void QMessageBox_virtbase(QMessageBox* src, QDialog** outptr_QDialog);
QMetaObject* QMessageBox_MetaObject(const QMessageBox* self);
void* QMessageBox_Metacast(QMessageBox* self, const char* param1);
struct miqt_string QMessageBox_Tr(const char* s);
struct miqt_string QMessageBox_TrUtf8(const char* s);
void QMessageBox_AddButton(QMessageBox* self, QAbstractButton* button, int role);
QPushButton* QMessageBox_AddButton2(QMessageBox* self, struct miqt_string text, int role);
QPushButton* QMessageBox_AddButtonWithButton(QMessageBox* self, int button);
void QMessageBox_RemoveButton(QMessageBox* self, QAbstractButton* button);
struct miqt_array /* of QAbstractButton* */  QMessageBox_Buttons(const QMessageBox* self);
int QMessageBox_ButtonRole(const QMessageBox* self, QAbstractButton* button);
void QMessageBox_SetStandardButtons(QMessageBox* self, int buttons);
int QMessageBox_StandardButtons(const QMessageBox* self);
int QMessageBox_StandardButton(const QMessageBox* self, QAbstractButton* button);
QAbstractButton* QMessageBox_Button(const QMessageBox* self, int which);
QPushButton* QMessageBox_DefaultButton(const QMessageBox* self);
void QMessageBox_SetDefaultButton(QMessageBox* self, QPushButton* button);
void QMessageBox_SetDefaultButtonWithButton(QMessageBox* self, int button);
QAbstractButton* QMessageBox_EscapeButton(const QMessageBox* self);
void QMessageBox_SetEscapeButton(QMessageBox* self, QAbstractButton* button);
void QMessageBox_SetEscapeButtonWithButton(QMessageBox* self, int button);
QAbstractButton* QMessageBox_ClickedButton(const QMessageBox* self);
struct miqt_string QMessageBox_Text(const QMessageBox* self);
void QMessageBox_SetText(QMessageBox* self, struct miqt_string text);
int QMessageBox_Icon(const QMessageBox* self);
void QMessageBox_SetIcon(QMessageBox* self, int icon);
QPixmap* QMessageBox_IconPixmap(const QMessageBox* self);
void QMessageBox_SetIconPixmap(QMessageBox* self, QPixmap* pixmap);
int QMessageBox_TextFormat(const QMessageBox* self);
void QMessageBox_SetTextFormat(QMessageBox* self, int format);
void QMessageBox_SetTextInteractionFlags(QMessageBox* self, int flags);
int QMessageBox_TextInteractionFlags(const QMessageBox* self);
void QMessageBox_SetCheckBox(QMessageBox* self, QCheckBox* cb);
QCheckBox* QMessageBox_CheckBox(const QMessageBox* self);
int QMessageBox_Information(QWidget* parent, struct miqt_string title, struct miqt_string text);
int QMessageBox_Question(QWidget* parent, struct miqt_string title, struct miqt_string text);
int QMessageBox_Warning(QWidget* parent, struct miqt_string title, struct miqt_string text);
int QMessageBox_Critical(QWidget* parent, struct miqt_string title, struct miqt_string text);
void QMessageBox_About(QWidget* parent, struct miqt_string title, struct miqt_string text);
void QMessageBox_AboutQt(QWidget* parent);
int QMessageBox_Information2(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0);
int QMessageBox_Information3(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text);
int QMessageBox_Information4(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0);
int QMessageBox_Question2(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0);
int QMessageBox_Question3(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text);
int QMessageBox_Question4(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Warning2(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Warning3(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text);
int QMessageBox_Warning4(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Critical2(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Critical3(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text);
int QMessageBox_Critical4(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
struct miqt_string QMessageBox_ButtonText(const QMessageBox* self, int button);
void QMessageBox_SetButtonText(QMessageBox* self, int button, struct miqt_string text);
struct miqt_string QMessageBox_InformativeText(const QMessageBox* self);
void QMessageBox_SetInformativeText(QMessageBox* self, struct miqt_string text);
struct miqt_string QMessageBox_DetailedText(const QMessageBox* self);
void QMessageBox_SetDetailedText(QMessageBox* self, struct miqt_string text);
void QMessageBox_SetWindowTitle(QMessageBox* self, struct miqt_string title);
void QMessageBox_SetWindowModality(QMessageBox* self, int windowModality);
QPixmap* QMessageBox_StandardIcon(int icon);
void QMessageBox_ButtonClicked(QMessageBox* self, QAbstractButton* button);
void QMessageBox_connect_ButtonClicked(QMessageBox* self, intptr_t slot);
bool QMessageBox_Event(QMessageBox* self, QEvent* e);
void QMessageBox_ResizeEvent(QMessageBox* self, QResizeEvent* event);
void QMessageBox_ShowEvent(QMessageBox* self, QShowEvent* event);
void QMessageBox_CloseEvent(QMessageBox* self, QCloseEvent* event);
void QMessageBox_KeyPressEvent(QMessageBox* self, QKeyEvent* event);
void QMessageBox_ChangeEvent(QMessageBox* self, QEvent* event);
struct miqt_string QMessageBox_Tr2(const char* s, const char* c);
struct miqt_string QMessageBox_Tr3(const char* s, const char* c, int n);
struct miqt_string QMessageBox_TrUtf82(const char* s, const char* c);
struct miqt_string QMessageBox_TrUtf83(const char* s, const char* c, int n);
int QMessageBox_Information42(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons);
int QMessageBox_Information5(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons, int defaultButton);
int QMessageBox_Question42(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons);
int QMessageBox_Question5(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons, int defaultButton);
int QMessageBox_Warning42(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons);
int QMessageBox_Warning5(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons, int defaultButton);
int QMessageBox_Critical42(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons);
int QMessageBox_Critical5(QWidget* parent, struct miqt_string title, struct miqt_string text, int buttons, int defaultButton);
void QMessageBox_AboutQt2(QWidget* parent, struct miqt_string title);
int QMessageBox_Information52(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Information6(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1, int button2);
int QMessageBox_Information53(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text);
int QMessageBox_Information62(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text);
int QMessageBox_Information7(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber);
int QMessageBox_Information8(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_Information54(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Question52(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1);
int QMessageBox_Question6(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1, int button2);
int QMessageBox_Question53(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text);
int QMessageBox_Question62(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text);
int QMessageBox_Question7(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber);
int QMessageBox_Question8(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_Warning6(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1, int button2);
int QMessageBox_Warning52(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text);
int QMessageBox_Warning62(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text);
int QMessageBox_Warning7(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber);
int QMessageBox_Warning8(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_Critical6(QWidget* parent, struct miqt_string title, struct miqt_string text, int button0, int button1, int button2);
int QMessageBox_Critical52(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text);
int QMessageBox_Critical62(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text);
int QMessageBox_Critical7(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber);
int QMessageBox_Critical8(QWidget* parent, struct miqt_string title, struct miqt_string text, struct miqt_string button0Text, struct miqt_string button1Text, struct miqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
bool QMessageBox_override_virtual_Event(void* self, intptr_t slot);
bool QMessageBox_virtualbase_Event(void* self, QEvent* e);
bool QMessageBox_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ResizeEvent(void* self, QResizeEvent* event);
bool QMessageBox_override_virtual_ShowEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ShowEvent(void* self, QShowEvent* event);
bool QMessageBox_override_virtual_CloseEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_CloseEvent(void* self, QCloseEvent* event);
bool QMessageBox_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_KeyPressEvent(void* self, QKeyEvent* event);
bool QMessageBox_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ChangeEvent(void* self, QEvent* event);
bool QMessageBox_override_virtual_SetVisible(void* self, intptr_t slot);
void QMessageBox_virtualbase_SetVisible(void* self, bool visible);
bool QMessageBox_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QMessageBox_virtualbase_SizeHint(const void* self);
bool QMessageBox_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QMessageBox_virtualbase_MinimumSizeHint(const void* self);
bool QMessageBox_override_virtual_Open(void* self, intptr_t slot);
void QMessageBox_virtualbase_Open(void* self);
bool QMessageBox_override_virtual_Exec(void* self, intptr_t slot);
int QMessageBox_virtualbase_Exec(void* self);
bool QMessageBox_override_virtual_Done(void* self, intptr_t slot);
void QMessageBox_virtualbase_Done(void* self, int param1);
bool QMessageBox_override_virtual_Accept(void* self, intptr_t slot);
void QMessageBox_virtualbase_Accept(void* self);
bool QMessageBox_override_virtual_Reject(void* self, intptr_t slot);
void QMessageBox_virtualbase_Reject(void* self);
bool QMessageBox_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* param1);
bool QMessageBox_override_virtual_EventFilter(void* self, intptr_t slot);
bool QMessageBox_virtualbase_EventFilter(void* self, QObject* param1, QEvent* param2);
bool QMessageBox_override_virtual_DevType(void* self, intptr_t slot);
int QMessageBox_virtualbase_DevType(const void* self);
bool QMessageBox_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QMessageBox_virtualbase_HeightForWidth(const void* self, int param1);
bool QMessageBox_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QMessageBox_virtualbase_HasHeightForWidth(const void* self);
bool QMessageBox_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QMessageBox_virtualbase_PaintEngine(const void* self);
bool QMessageBox_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_MousePressEvent(void* self, QMouseEvent* event);
bool QMessageBox_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* event);
bool QMessageBox_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QMessageBox_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_MouseMoveEvent(void* self, QMouseEvent* event);
bool QMessageBox_override_virtual_WheelEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_WheelEvent(void* self, QWheelEvent* event);
bool QMessageBox_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* event);
bool QMessageBox_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_FocusInEvent(void* self, QFocusEvent* event);
bool QMessageBox_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_FocusOutEvent(void* self, QFocusEvent* event);
bool QMessageBox_override_virtual_EnterEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_EnterEvent(void* self, QEvent* event);
bool QMessageBox_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_LeaveEvent(void* self, QEvent* event);
bool QMessageBox_override_virtual_PaintEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_PaintEvent(void* self, QPaintEvent* event);
bool QMessageBox_override_virtual_MoveEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_MoveEvent(void* self, QMoveEvent* event);
bool QMessageBox_override_virtual_TabletEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_TabletEvent(void* self, QTabletEvent* event);
bool QMessageBox_override_virtual_ActionEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ActionEvent(void* self, QActionEvent* event);
bool QMessageBox_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* event);
bool QMessageBox_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* event);
bool QMessageBox_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* event);
bool QMessageBox_override_virtual_DropEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_DropEvent(void* self, QDropEvent* event);
bool QMessageBox_override_virtual_HideEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_HideEvent(void* self, QHideEvent* event);
bool QMessageBox_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QMessageBox_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
bool QMessageBox_override_virtual_Metric(void* self, intptr_t slot);
int QMessageBox_virtualbase_Metric(const void* self, int param1);
bool QMessageBox_override_virtual_InitPainter(void* self, intptr_t slot);
void QMessageBox_virtualbase_InitPainter(const void* self, QPainter* painter);
bool QMessageBox_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QMessageBox_virtualbase_Redirected(const void* self, QPoint* offset);
bool QMessageBox_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QMessageBox_virtualbase_SharedPainter(const void* self);
bool QMessageBox_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
bool QMessageBox_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QMessageBox_virtualbase_InputMethodQuery(const void* self, int param1);
bool QMessageBox_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QMessageBox_virtualbase_FocusNextPrevChild(void* self, bool next);
bool QMessageBox_override_virtual_TimerEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_TimerEvent(void* self, QTimerEvent* event);
bool QMessageBox_override_virtual_ChildEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_ChildEvent(void* self, QChildEvent* event);
bool QMessageBox_override_virtual_CustomEvent(void* self, intptr_t slot);
void QMessageBox_virtualbase_CustomEvent(void* self, QEvent* event);
bool QMessageBox_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QMessageBox_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
bool QMessageBox_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QMessageBox_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
void QMessageBox_Delete(QMessageBox* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
