#pragma once
#ifndef MIQT_QT_GEN_QTEXTBROWSER_H
#define MIQT_QT_GEN_QTEXTBROWSER_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTextBrowser;
class QTextCursor;
class QTextEdit;
class QTimerEvent;
class QUrl;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextBrowser QTextBrowser;
typedef struct QTextCursor QTextCursor;
typedef struct QTextEdit QTextEdit;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QTextBrowser* QTextBrowser_new(QWidget* parent);
QTextBrowser* QTextBrowser_new2();
void QTextBrowser_virtbase(QTextBrowser* src, QTextEdit** outptr_QTextEdit);
QMetaObject* QTextBrowser_MetaObject(const QTextBrowser* self);
void* QTextBrowser_Metacast(QTextBrowser* self, const char* param1);
struct miqt_string QTextBrowser_Tr(const char* s);
struct miqt_string QTextBrowser_TrUtf8(const char* s);
QUrl* QTextBrowser_Source(const QTextBrowser* self);
int QTextBrowser_SourceType(const QTextBrowser* self);
struct miqt_array /* of struct miqt_string */  QTextBrowser_SearchPaths(const QTextBrowser* self);
void QTextBrowser_SetSearchPaths(QTextBrowser* self, struct miqt_array /* of struct miqt_string */  paths);
QVariant* QTextBrowser_LoadResource(QTextBrowser* self, int typeVal, QUrl* name);
bool QTextBrowser_IsBackwardAvailable(const QTextBrowser* self);
bool QTextBrowser_IsForwardAvailable(const QTextBrowser* self);
void QTextBrowser_ClearHistory(QTextBrowser* self);
struct miqt_string QTextBrowser_HistoryTitle(const QTextBrowser* self, int param1);
QUrl* QTextBrowser_HistoryUrl(const QTextBrowser* self, int param1);
int QTextBrowser_BackwardHistoryCount(const QTextBrowser* self);
int QTextBrowser_ForwardHistoryCount(const QTextBrowser* self);
bool QTextBrowser_OpenExternalLinks(const QTextBrowser* self);
void QTextBrowser_SetOpenExternalLinks(QTextBrowser* self, bool open);
bool QTextBrowser_OpenLinks(const QTextBrowser* self);
void QTextBrowser_SetOpenLinks(QTextBrowser* self, bool open);
void QTextBrowser_SetSource(QTextBrowser* self, QUrl* name);
void QTextBrowser_SetSource2(QTextBrowser* self, QUrl* name, int typeVal);
void QTextBrowser_Backward(QTextBrowser* self);
void QTextBrowser_Forward(QTextBrowser* self);
void QTextBrowser_Home(QTextBrowser* self);
void QTextBrowser_Reload(QTextBrowser* self);
void QTextBrowser_BackwardAvailable(QTextBrowser* self, bool param1);
void QTextBrowser_connect_BackwardAvailable(QTextBrowser* self, intptr_t slot);
void QTextBrowser_ForwardAvailable(QTextBrowser* self, bool param1);
void QTextBrowser_connect_ForwardAvailable(QTextBrowser* self, intptr_t slot);
void QTextBrowser_HistoryChanged(QTextBrowser* self);
void QTextBrowser_connect_HistoryChanged(QTextBrowser* self, intptr_t slot);
void QTextBrowser_SourceChanged(QTextBrowser* self, QUrl* param1);
void QTextBrowser_connect_SourceChanged(QTextBrowser* self, intptr_t slot);
void QTextBrowser_Highlighted(QTextBrowser* self, QUrl* param1);
void QTextBrowser_connect_Highlighted(QTextBrowser* self, intptr_t slot);
void QTextBrowser_HighlightedWithQString(QTextBrowser* self, struct miqt_string param1);
void QTextBrowser_connect_HighlightedWithQString(QTextBrowser* self, intptr_t slot);
void QTextBrowser_AnchorClicked(QTextBrowser* self, QUrl* param1);
void QTextBrowser_connect_AnchorClicked(QTextBrowser* self, intptr_t slot);
bool QTextBrowser_Event(QTextBrowser* self, QEvent* e);
void QTextBrowser_KeyPressEvent(QTextBrowser* self, QKeyEvent* ev);
void QTextBrowser_MouseMoveEvent(QTextBrowser* self, QMouseEvent* ev);
void QTextBrowser_MousePressEvent(QTextBrowser* self, QMouseEvent* ev);
void QTextBrowser_MouseReleaseEvent(QTextBrowser* self, QMouseEvent* ev);
void QTextBrowser_FocusOutEvent(QTextBrowser* self, QFocusEvent* ev);
bool QTextBrowser_FocusNextPrevChild(QTextBrowser* self, bool next);
void QTextBrowser_PaintEvent(QTextBrowser* self, QPaintEvent* e);
struct miqt_string QTextBrowser_Tr2(const char* s, const char* c);
struct miqt_string QTextBrowser_Tr3(const char* s, const char* c, int n);
struct miqt_string QTextBrowser_TrUtf82(const char* s, const char* c);
struct miqt_string QTextBrowser_TrUtf83(const char* s, const char* c, int n);
bool QTextBrowser_override_virtual_LoadResource(void* self, intptr_t slot);
QVariant* QTextBrowser_virtualbase_LoadResource(void* self, int typeVal, QUrl* name);
bool QTextBrowser_override_virtual_SetSource(void* self, intptr_t slot);
void QTextBrowser_virtualbase_SetSource(void* self, QUrl* name);
bool QTextBrowser_override_virtual_Backward(void* self, intptr_t slot);
void QTextBrowser_virtualbase_Backward(void* self);
bool QTextBrowser_override_virtual_Forward(void* self, intptr_t slot);
void QTextBrowser_virtualbase_Forward(void* self);
bool QTextBrowser_override_virtual_Home(void* self, intptr_t slot);
void QTextBrowser_virtualbase_Home(void* self);
bool QTextBrowser_override_virtual_Reload(void* self, intptr_t slot);
void QTextBrowser_virtualbase_Reload(void* self);
bool QTextBrowser_override_virtual_Event(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_Event(void* self, QEvent* e);
bool QTextBrowser_override_virtual_KeyPressEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_KeyPressEvent(void* self, QKeyEvent* ev);
bool QTextBrowser_override_virtual_MouseMoveEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_MouseMoveEvent(void* self, QMouseEvent* ev);
bool QTextBrowser_override_virtual_MousePressEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_MousePressEvent(void* self, QMouseEvent* ev);
bool QTextBrowser_override_virtual_MouseReleaseEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_MouseReleaseEvent(void* self, QMouseEvent* ev);
bool QTextBrowser_override_virtual_FocusOutEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_FocusOutEvent(void* self, QFocusEvent* ev);
bool QTextBrowser_override_virtual_FocusNextPrevChild(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_FocusNextPrevChild(void* self, bool next);
bool QTextBrowser_override_virtual_PaintEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_PaintEvent(void* self, QPaintEvent* e);
bool QTextBrowser_override_virtual_InputMethodQuery(void* self, intptr_t slot);
QVariant* QTextBrowser_virtualbase_InputMethodQuery(const void* self, int property);
bool QTextBrowser_override_virtual_TimerEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_TimerEvent(void* self, QTimerEvent* e);
bool QTextBrowser_override_virtual_KeyReleaseEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_KeyReleaseEvent(void* self, QKeyEvent* e);
bool QTextBrowser_override_virtual_ResizeEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ResizeEvent(void* self, QResizeEvent* e);
bool QTextBrowser_override_virtual_MouseDoubleClickEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_MouseDoubleClickEvent(void* self, QMouseEvent* e);
bool QTextBrowser_override_virtual_ContextMenuEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ContextMenuEvent(void* self, QContextMenuEvent* e);
bool QTextBrowser_override_virtual_DragEnterEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DragEnterEvent(void* self, QDragEnterEvent* e);
bool QTextBrowser_override_virtual_DragLeaveEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DragLeaveEvent(void* self, QDragLeaveEvent* e);
bool QTextBrowser_override_virtual_DragMoveEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DragMoveEvent(void* self, QDragMoveEvent* e);
bool QTextBrowser_override_virtual_DropEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DropEvent(void* self, QDropEvent* e);
bool QTextBrowser_override_virtual_FocusInEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_FocusInEvent(void* self, QFocusEvent* e);
bool QTextBrowser_override_virtual_ShowEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ShowEvent(void* self, QShowEvent* param1);
bool QTextBrowser_override_virtual_ChangeEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ChangeEvent(void* self, QEvent* e);
bool QTextBrowser_override_virtual_WheelEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_WheelEvent(void* self, QWheelEvent* e);
bool QTextBrowser_override_virtual_CreateMimeDataFromSelection(void* self, intptr_t slot);
QMimeData* QTextBrowser_virtualbase_CreateMimeDataFromSelection(const void* self);
bool QTextBrowser_override_virtual_CanInsertFromMimeData(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_CanInsertFromMimeData(const void* self, QMimeData* source);
bool QTextBrowser_override_virtual_InsertFromMimeData(void* self, intptr_t slot);
void QTextBrowser_virtualbase_InsertFromMimeData(void* self, QMimeData* source);
bool QTextBrowser_override_virtual_InputMethodEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_InputMethodEvent(void* self, QInputMethodEvent* param1);
bool QTextBrowser_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
bool QTextBrowser_override_virtual_DoSetTextCursor(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DoSetTextCursor(void* self, QTextCursor* cursor);
bool QTextBrowser_override_virtual_MinimumSizeHint(void* self, intptr_t slot);
QSize* QTextBrowser_virtualbase_MinimumSizeHint(const void* self);
bool QTextBrowser_override_virtual_SizeHint(void* self, intptr_t slot);
QSize* QTextBrowser_virtualbase_SizeHint(const void* self);
bool QTextBrowser_override_virtual_SetupViewport(void* self, intptr_t slot);
void QTextBrowser_virtualbase_SetupViewport(void* self, QWidget* viewport);
bool QTextBrowser_override_virtual_EventFilter(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_EventFilter(void* self, QObject* param1, QEvent* param2);
bool QTextBrowser_override_virtual_ViewportEvent(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_ViewportEvent(void* self, QEvent* param1);
bool QTextBrowser_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QTextBrowser_virtualbase_ViewportSizeHint(const void* self);
bool QTextBrowser_override_virtual_DevType(void* self, intptr_t slot);
int QTextBrowser_virtualbase_DevType(const void* self);
bool QTextBrowser_override_virtual_SetVisible(void* self, intptr_t slot);
void QTextBrowser_virtualbase_SetVisible(void* self, bool visible);
bool QTextBrowser_override_virtual_HeightForWidth(void* self, intptr_t slot);
int QTextBrowser_virtualbase_HeightForWidth(const void* self, int param1);
bool QTextBrowser_override_virtual_HasHeightForWidth(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_HasHeightForWidth(const void* self);
bool QTextBrowser_override_virtual_PaintEngine(void* self, intptr_t slot);
QPaintEngine* QTextBrowser_virtualbase_PaintEngine(const void* self);
bool QTextBrowser_override_virtual_EnterEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_EnterEvent(void* self, QEvent* event);
bool QTextBrowser_override_virtual_LeaveEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_LeaveEvent(void* self, QEvent* event);
bool QTextBrowser_override_virtual_MoveEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_MoveEvent(void* self, QMoveEvent* event);
bool QTextBrowser_override_virtual_CloseEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_CloseEvent(void* self, QCloseEvent* event);
bool QTextBrowser_override_virtual_TabletEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_TabletEvent(void* self, QTabletEvent* event);
bool QTextBrowser_override_virtual_ActionEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ActionEvent(void* self, QActionEvent* event);
bool QTextBrowser_override_virtual_HideEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_HideEvent(void* self, QHideEvent* event);
bool QTextBrowser_override_virtual_NativeEvent(void* self, intptr_t slot);
bool QTextBrowser_virtualbase_NativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
bool QTextBrowser_override_virtual_Metric(void* self, intptr_t slot);
int QTextBrowser_virtualbase_Metric(const void* self, int param1);
bool QTextBrowser_override_virtual_InitPainter(void* self, intptr_t slot);
void QTextBrowser_virtualbase_InitPainter(const void* self, QPainter* painter);
bool QTextBrowser_override_virtual_Redirected(void* self, intptr_t slot);
QPaintDevice* QTextBrowser_virtualbase_Redirected(const void* self, QPoint* offset);
bool QTextBrowser_override_virtual_SharedPainter(void* self, intptr_t slot);
QPainter* QTextBrowser_virtualbase_SharedPainter(const void* self);
bool QTextBrowser_override_virtual_ChildEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ChildEvent(void* self, QChildEvent* event);
bool QTextBrowser_override_virtual_CustomEvent(void* self, intptr_t slot);
void QTextBrowser_virtualbase_CustomEvent(void* self, QEvent* event);
bool QTextBrowser_override_virtual_ConnectNotify(void* self, intptr_t slot);
void QTextBrowser_virtualbase_ConnectNotify(void* self, QMetaMethod* signal);
bool QTextBrowser_override_virtual_DisconnectNotify(void* self, intptr_t slot);
void QTextBrowser_virtualbase_DisconnectNotify(void* self, QMetaMethod* signal);
void QTextBrowser_Delete(QTextBrowser* self);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
