#pragma once
#ifndef MIQT_QT_GEN_QTABLEWIDGET_H
#define MIQT_QT_GEN_QTABLEWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemView;
class QAbstractScrollArea;
class QBrush;
class QColor;
class QDataStream;
class QDropEvent;
class QEvent;
class QFont;
class QFrame;
class QIcon;
class QItemSelectionModel;
class QMetaObject;
class QMimeData;
class QModelIndex;
class QObject;
class QPaintDevice;
class QPaintEvent;
class QPoint;
class QRect;
class QSize;
class QStyleOptionViewItem;
class QTableView;
class QTableWidget;
class QTableWidgetItem;
class QTableWidgetSelectionRange;
class QTimerEvent;
class QVariant;
class QWidget;
#else
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QBrush QBrush;
typedef struct QColor QColor;
typedef struct QDataStream QDataStream;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QIcon QIcon;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QSize QSize;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTableView QTableView;
typedef struct QTableWidget QTableWidget;
typedef struct QTableWidgetItem QTableWidgetItem;
typedef struct QTableWidgetSelectionRange QTableWidgetSelectionRange;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

void QTableWidgetSelectionRange_new(QTableWidgetSelectionRange** outptr_QTableWidgetSelectionRange);
void QTableWidgetSelectionRange_new2(int top, int left, int bottom, int right, QTableWidgetSelectionRange** outptr_QTableWidgetSelectionRange);
void QTableWidgetSelectionRange_new3(QTableWidgetSelectionRange* other, QTableWidgetSelectionRange** outptr_QTableWidgetSelectionRange);
void QTableWidgetSelectionRange_OperatorAssign(QTableWidgetSelectionRange* self, QTableWidgetSelectionRange* other);
int QTableWidgetSelectionRange_TopRow(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_BottomRow(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_LeftColumn(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_RightColumn(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_RowCount(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_ColumnCount(const QTableWidgetSelectionRange* self);
void QTableWidgetSelectionRange_Delete(QTableWidgetSelectionRange* self, bool isSubclass);

void QTableWidgetItem_new(QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new2(struct miqt_string text, QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new3(QIcon* icon, struct miqt_string text, QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new4(QTableWidgetItem* other, QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new5(int typeVal, QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new6(struct miqt_string text, int typeVal, QTableWidgetItem** outptr_QTableWidgetItem);
void QTableWidgetItem_new7(QIcon* icon, struct miqt_string text, int typeVal, QTableWidgetItem** outptr_QTableWidgetItem);
QTableWidgetItem* QTableWidgetItem_Clone(const QTableWidgetItem* self);
QTableWidget* QTableWidgetItem_TableWidget(const QTableWidgetItem* self);
int QTableWidgetItem_Row(const QTableWidgetItem* self);
int QTableWidgetItem_Column(const QTableWidgetItem* self);
void QTableWidgetItem_SetSelected(QTableWidgetItem* self, bool selectVal);
bool QTableWidgetItem_IsSelected(const QTableWidgetItem* self);
int QTableWidgetItem_Flags(const QTableWidgetItem* self);
void QTableWidgetItem_SetFlags(QTableWidgetItem* self, int flags);
struct miqt_string QTableWidgetItem_Text(const QTableWidgetItem* self);
void QTableWidgetItem_SetText(QTableWidgetItem* self, struct miqt_string text);
QIcon* QTableWidgetItem_Icon(const QTableWidgetItem* self);
void QTableWidgetItem_SetIcon(QTableWidgetItem* self, QIcon* icon);
struct miqt_string QTableWidgetItem_StatusTip(const QTableWidgetItem* self);
void QTableWidgetItem_SetStatusTip(QTableWidgetItem* self, struct miqt_string statusTip);
struct miqt_string QTableWidgetItem_ToolTip(const QTableWidgetItem* self);
void QTableWidgetItem_SetToolTip(QTableWidgetItem* self, struct miqt_string toolTip);
struct miqt_string QTableWidgetItem_WhatsThis(const QTableWidgetItem* self);
void QTableWidgetItem_SetWhatsThis(QTableWidgetItem* self, struct miqt_string whatsThis);
QFont* QTableWidgetItem_Font(const QTableWidgetItem* self);
void QTableWidgetItem_SetFont(QTableWidgetItem* self, QFont* font);
int QTableWidgetItem_TextAlignment(const QTableWidgetItem* self);
void QTableWidgetItem_SetTextAlignment(QTableWidgetItem* self, int alignment);
QColor* QTableWidgetItem_BackgroundColor(const QTableWidgetItem* self);
void QTableWidgetItem_SetBackgroundColor(QTableWidgetItem* self, QColor* color);
QBrush* QTableWidgetItem_Background(const QTableWidgetItem* self);
void QTableWidgetItem_SetBackground(QTableWidgetItem* self, QBrush* brush);
QColor* QTableWidgetItem_TextColor(const QTableWidgetItem* self);
void QTableWidgetItem_SetTextColor(QTableWidgetItem* self, QColor* color);
QBrush* QTableWidgetItem_Foreground(const QTableWidgetItem* self);
void QTableWidgetItem_SetForeground(QTableWidgetItem* self, QBrush* brush);
int QTableWidgetItem_CheckState(const QTableWidgetItem* self);
void QTableWidgetItem_SetCheckState(QTableWidgetItem* self, int state);
QSize* QTableWidgetItem_SizeHint(const QTableWidgetItem* self);
void QTableWidgetItem_SetSizeHint(QTableWidgetItem* self, QSize* size);
QVariant* QTableWidgetItem_Data(const QTableWidgetItem* self, int role);
void QTableWidgetItem_SetData(QTableWidgetItem* self, int role, QVariant* value);
bool QTableWidgetItem_OperatorLesser(const QTableWidgetItem* self, QTableWidgetItem* other);
void QTableWidgetItem_Read(QTableWidgetItem* self, QDataStream* in);
void QTableWidgetItem_Write(const QTableWidgetItem* self, QDataStream* out);
void QTableWidgetItem_OperatorAssign(QTableWidgetItem* self, QTableWidgetItem* other);
int QTableWidgetItem_Type(const QTableWidgetItem* self);
void QTableWidgetItem_override_virtual_Clone(void* self, intptr_t slot);
QTableWidgetItem* QTableWidgetItem_virtualbase_Clone(const void* self);
void QTableWidgetItem_override_virtual_Data(void* self, intptr_t slot);
QVariant* QTableWidgetItem_virtualbase_Data(const void* self, int role);
void QTableWidgetItem_override_virtual_SetData(void* self, intptr_t slot);
void QTableWidgetItem_virtualbase_SetData(void* self, int role, QVariant* value);
void QTableWidgetItem_override_virtual_OperatorLesser(void* self, intptr_t slot);
bool QTableWidgetItem_virtualbase_OperatorLesser(const void* self, QTableWidgetItem* other);
void QTableWidgetItem_override_virtual_Read(void* self, intptr_t slot);
void QTableWidgetItem_virtualbase_Read(void* self, QDataStream* in);
void QTableWidgetItem_override_virtual_Write(void* self, intptr_t slot);
void QTableWidgetItem_virtualbase_Write(const void* self, QDataStream* out);
void QTableWidgetItem_Delete(QTableWidgetItem* self, bool isSubclass);

void QTableWidget_new(QWidget* parent, QTableWidget** outptr_QTableWidget, QTableView** outptr_QTableView, QAbstractItemView** outptr_QAbstractItemView, QAbstractScrollArea** outptr_QAbstractScrollArea, QFrame** outptr_QFrame, QWidget** outptr_QWidget, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
void QTableWidget_new2(QTableWidget** outptr_QTableWidget, QTableView** outptr_QTableView, QAbstractItemView** outptr_QAbstractItemView, QAbstractScrollArea** outptr_QAbstractScrollArea, QFrame** outptr_QFrame, QWidget** outptr_QWidget, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
void QTableWidget_new3(int rows, int columns, QTableWidget** outptr_QTableWidget, QTableView** outptr_QTableView, QAbstractItemView** outptr_QAbstractItemView, QAbstractScrollArea** outptr_QAbstractScrollArea, QFrame** outptr_QFrame, QWidget** outptr_QWidget, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
void QTableWidget_new4(int rows, int columns, QWidget* parent, QTableWidget** outptr_QTableWidget, QTableView** outptr_QTableView, QAbstractItemView** outptr_QAbstractItemView, QAbstractScrollArea** outptr_QAbstractScrollArea, QFrame** outptr_QFrame, QWidget** outptr_QWidget, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
QMetaObject* QTableWidget_MetaObject(const QTableWidget* self);
void* QTableWidget_Metacast(QTableWidget* self, const char* param1);
struct miqt_string QTableWidget_Tr(const char* s);
struct miqt_string QTableWidget_TrUtf8(const char* s);
void QTableWidget_SetRowCount(QTableWidget* self, int rows);
int QTableWidget_RowCount(const QTableWidget* self);
void QTableWidget_SetColumnCount(QTableWidget* self, int columns);
int QTableWidget_ColumnCount(const QTableWidget* self);
int QTableWidget_Row(const QTableWidget* self, QTableWidgetItem* item);
int QTableWidget_Column(const QTableWidget* self, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_Item(const QTableWidget* self, int row, int column);
void QTableWidget_SetItem(QTableWidget* self, int row, int column, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeItem(QTableWidget* self, int row, int column);
QTableWidgetItem* QTableWidget_VerticalHeaderItem(const QTableWidget* self, int row);
void QTableWidget_SetVerticalHeaderItem(QTableWidget* self, int row, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeVerticalHeaderItem(QTableWidget* self, int row);
QTableWidgetItem* QTableWidget_HorizontalHeaderItem(const QTableWidget* self, int column);
void QTableWidget_SetHorizontalHeaderItem(QTableWidget* self, int column, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeHorizontalHeaderItem(QTableWidget* self, int column);
void QTableWidget_SetVerticalHeaderLabels(QTableWidget* self, struct miqt_array /* of struct miqt_string */  labels);
void QTableWidget_SetHorizontalHeaderLabels(QTableWidget* self, struct miqt_array /* of struct miqt_string */  labels);
int QTableWidget_CurrentRow(const QTableWidget* self);
int QTableWidget_CurrentColumn(const QTableWidget* self);
QTableWidgetItem* QTableWidget_CurrentItem(const QTableWidget* self);
void QTableWidget_SetCurrentItem(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_SetCurrentItem2(QTableWidget* self, QTableWidgetItem* item, int command);
void QTableWidget_SetCurrentCell(QTableWidget* self, int row, int column);
void QTableWidget_SetCurrentCell2(QTableWidget* self, int row, int column, int command);
void QTableWidget_SortItems(QTableWidget* self, int column);
void QTableWidget_SetSortingEnabled(QTableWidget* self, bool enable);
bool QTableWidget_IsSortingEnabled(const QTableWidget* self);
void QTableWidget_EditItem(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_OpenPersistentEditor(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_ClosePersistentEditor(QTableWidget* self, QTableWidgetItem* item);
bool QTableWidget_IsPersistentEditorOpen(const QTableWidget* self, QTableWidgetItem* item);
QWidget* QTableWidget_CellWidget(const QTableWidget* self, int row, int column);
void QTableWidget_SetCellWidget(QTableWidget* self, int row, int column, QWidget* widget);
void QTableWidget_RemoveCellWidget(QTableWidget* self, int row, int column);
bool QTableWidget_IsItemSelected(const QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_SetItemSelected(QTableWidget* self, QTableWidgetItem* item, bool selectVal);
void QTableWidget_SetRangeSelected(QTableWidget* self, QTableWidgetSelectionRange* rangeVal, bool selectVal);
struct miqt_array /* of QTableWidgetSelectionRange* */  QTableWidget_SelectedRanges(const QTableWidget* self);
struct miqt_array /* of QTableWidgetItem* */  QTableWidget_SelectedItems(const QTableWidget* self);
struct miqt_array /* of QTableWidgetItem* */  QTableWidget_FindItems(const QTableWidget* self, struct miqt_string text, int flags);
int QTableWidget_VisualRow(const QTableWidget* self, int logicalRow);
int QTableWidget_VisualColumn(const QTableWidget* self, int logicalColumn);
QTableWidgetItem* QTableWidget_ItemAt(const QTableWidget* self, QPoint* p);
QTableWidgetItem* QTableWidget_ItemAt2(const QTableWidget* self, int x, int y);
QRect* QTableWidget_VisualItemRect(const QTableWidget* self, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_ItemPrototype(const QTableWidget* self);
void QTableWidget_SetItemPrototype(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_ScrollToItem(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_InsertRow(QTableWidget* self, int row);
void QTableWidget_InsertColumn(QTableWidget* self, int column);
void QTableWidget_RemoveRow(QTableWidget* self, int row);
void QTableWidget_RemoveColumn(QTableWidget* self, int column);
void QTableWidget_Clear(QTableWidget* self);
void QTableWidget_ClearContents(QTableWidget* self);
void QTableWidget_ItemPressed(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemPressed(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemClicked(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemDoubleClicked(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemDoubleClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemActivated(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemActivated(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemEntered(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemEntered(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemChanged(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_connect_ItemChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CurrentItemChanged(QTableWidget* self, QTableWidgetItem* current, QTableWidgetItem* previous);
void QTableWidget_connect_CurrentItemChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemSelectionChanged(QTableWidget* self);
void QTableWidget_connect_ItemSelectionChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CellPressed(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellPressed(QTableWidget* self, intptr_t slot);
void QTableWidget_CellClicked(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_CellDoubleClicked(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellDoubleClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_CellActivated(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellActivated(QTableWidget* self, intptr_t slot);
void QTableWidget_CellEntered(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellEntered(QTableWidget* self, intptr_t slot);
void QTableWidget_CellChanged(QTableWidget* self, int row, int column);
void QTableWidget_connect_CellChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CurrentCellChanged(QTableWidget* self, int currentRow, int currentColumn, int previousRow, int previousColumn);
void QTableWidget_connect_CurrentCellChanged(QTableWidget* self, intptr_t slot);
bool QTableWidget_Event(QTableWidget* self, QEvent* e);
struct miqt_array /* of struct miqt_string */  QTableWidget_MimeTypes(const QTableWidget* self);
QMimeData* QTableWidget_MimeData(const QTableWidget* self, struct miqt_array /* of QTableWidgetItem* */  items);
bool QTableWidget_DropMimeData(QTableWidget* self, int row, int column, QMimeData* data, int action);
int QTableWidget_SupportedDropActions(const QTableWidget* self);
void QTableWidget_DropEvent(QTableWidget* self, QDropEvent* event);
struct miqt_string QTableWidget_Tr2(const char* s, const char* c);
struct miqt_string QTableWidget_Tr3(const char* s, const char* c, int n);
struct miqt_string QTableWidget_TrUtf82(const char* s, const char* c);
struct miqt_string QTableWidget_TrUtf83(const char* s, const char* c, int n);
void QTableWidget_SortItems2(QTableWidget* self, int column, int order);
void QTableWidget_ScrollToItem2(QTableWidget* self, QTableWidgetItem* item, int hint);
void QTableWidget_override_virtual_Event(void* self, intptr_t slot);
bool QTableWidget_virtualbase_Event(void* self, QEvent* e);
void QTableWidget_override_virtual_MimeTypes(void* self, intptr_t slot);
struct miqt_array /* of struct miqt_string */  QTableWidget_virtualbase_MimeTypes(const void* self);
void QTableWidget_override_virtual_MimeData(void* self, intptr_t slot);
QMimeData* QTableWidget_virtualbase_MimeData(const void* self, struct miqt_array /* of QTableWidgetItem* */  items);
void QTableWidget_override_virtual_DropMimeData(void* self, intptr_t slot);
bool QTableWidget_virtualbase_DropMimeData(void* self, int row, int column, QMimeData* data, int action);
void QTableWidget_override_virtual_SupportedDropActions(void* self, intptr_t slot);
int QTableWidget_virtualbase_SupportedDropActions(const void* self);
void QTableWidget_override_virtual_DropEvent(void* self, intptr_t slot);
void QTableWidget_virtualbase_DropEvent(void* self, QDropEvent* event);
void QTableWidget_override_virtual_SetRootIndex(void* self, intptr_t slot);
void QTableWidget_virtualbase_SetRootIndex(void* self, QModelIndex* index);
void QTableWidget_override_virtual_SetSelectionModel(void* self, intptr_t slot);
void QTableWidget_virtualbase_SetSelectionModel(void* self, QItemSelectionModel* selectionModel);
void QTableWidget_override_virtual_DoItemsLayout(void* self, intptr_t slot);
void QTableWidget_virtualbase_DoItemsLayout(void* self);
void QTableWidget_override_virtual_VisualRect(void* self, intptr_t slot);
QRect* QTableWidget_virtualbase_VisualRect(const void* self, QModelIndex* index);
void QTableWidget_override_virtual_ScrollTo(void* self, intptr_t slot);
void QTableWidget_virtualbase_ScrollTo(void* self, QModelIndex* index, int hint);
void QTableWidget_override_virtual_IndexAt(void* self, intptr_t slot);
QModelIndex* QTableWidget_virtualbase_IndexAt(const void* self, QPoint* p);
void QTableWidget_override_virtual_ScrollContentsBy(void* self, intptr_t slot);
void QTableWidget_virtualbase_ScrollContentsBy(void* self, int dx, int dy);
void QTableWidget_override_virtual_ViewOptions(void* self, intptr_t slot);
QStyleOptionViewItem* QTableWidget_virtualbase_ViewOptions(const void* self);
void QTableWidget_override_virtual_PaintEvent(void* self, intptr_t slot);
void QTableWidget_virtualbase_PaintEvent(void* self, QPaintEvent* e);
void QTableWidget_override_virtual_TimerEvent(void* self, intptr_t slot);
void QTableWidget_virtualbase_TimerEvent(void* self, QTimerEvent* event);
void QTableWidget_override_virtual_HorizontalOffset(void* self, intptr_t slot);
int QTableWidget_virtualbase_HorizontalOffset(const void* self);
void QTableWidget_override_virtual_VerticalOffset(void* self, intptr_t slot);
int QTableWidget_virtualbase_VerticalOffset(const void* self);
void QTableWidget_override_virtual_MoveCursor(void* self, intptr_t slot);
QModelIndex* QTableWidget_virtualbase_MoveCursor(void* self, int cursorAction, int modifiers);
void QTableWidget_override_virtual_SetSelection(void* self, intptr_t slot);
void QTableWidget_virtualbase_SetSelection(void* self, QRect* rect, int command);
void QTableWidget_override_virtual_SelectedIndexes(void* self, intptr_t slot);
struct miqt_array /* of QModelIndex* */  QTableWidget_virtualbase_SelectedIndexes(const void* self);
void QTableWidget_override_virtual_UpdateGeometries(void* self, intptr_t slot);
void QTableWidget_virtualbase_UpdateGeometries(void* self);
void QTableWidget_override_virtual_ViewportSizeHint(void* self, intptr_t slot);
QSize* QTableWidget_virtualbase_ViewportSizeHint(const void* self);
void QTableWidget_override_virtual_SizeHintForRow(void* self, intptr_t slot);
int QTableWidget_virtualbase_SizeHintForRow(const void* self, int row);
void QTableWidget_override_virtual_SizeHintForColumn(void* self, intptr_t slot);
int QTableWidget_virtualbase_SizeHintForColumn(const void* self, int column);
void QTableWidget_override_virtual_VerticalScrollbarAction(void* self, intptr_t slot);
void QTableWidget_virtualbase_VerticalScrollbarAction(void* self, int action);
void QTableWidget_override_virtual_HorizontalScrollbarAction(void* self, intptr_t slot);
void QTableWidget_virtualbase_HorizontalScrollbarAction(void* self, int action);
void QTableWidget_override_virtual_IsIndexHidden(void* self, intptr_t slot);
bool QTableWidget_virtualbase_IsIndexHidden(const void* self, QModelIndex* index);
void QTableWidget_override_virtual_CurrentChanged(void* self, intptr_t slot);
void QTableWidget_virtualbase_CurrentChanged(void* self, QModelIndex* current, QModelIndex* previous);
void QTableWidget_Delete(QTableWidget* self, bool isSubclass);

#ifdef __cplusplus
} /* extern C */
#endif 

#endif
