#pragma once
#ifndef MIQT_QT_OPENGL_GEN_QGL_H
#define MIQT_QT_OPENGL_GEN_QGL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QColor;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QGLContext;
class QGLFormat;
class QGLWidget;
class QHideEvent;
class QImage;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPixmap;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QSurfaceFormat;
class QTabletEvent;
class QThread;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QColor QColor;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QGLContext QGLContext;
typedef struct QGLFormat QGLFormat;
typedef struct QGLWidget QGLWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSurfaceFormat QSurfaceFormat;
typedef struct QTabletEvent QTabletEvent;
typedef struct QThread QThread;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QGLFormat* QGLFormat_new();
QGLFormat* QGLFormat_new2(int options);
QGLFormat* QGLFormat_new3(QGLFormat* other);
QGLFormat* QGLFormat_new4(int options, int plane);
void QGLFormat_operatorAssign(QGLFormat* self, QGLFormat* other);
void QGLFormat_setDepthBufferSize(QGLFormat* self, int size);
int QGLFormat_depthBufferSize(const QGLFormat* self);
void QGLFormat_setAccumBufferSize(QGLFormat* self, int size);
int QGLFormat_accumBufferSize(const QGLFormat* self);
void QGLFormat_setRedBufferSize(QGLFormat* self, int size);
int QGLFormat_redBufferSize(const QGLFormat* self);
void QGLFormat_setGreenBufferSize(QGLFormat* self, int size);
int QGLFormat_greenBufferSize(const QGLFormat* self);
void QGLFormat_setBlueBufferSize(QGLFormat* self, int size);
int QGLFormat_blueBufferSize(const QGLFormat* self);
void QGLFormat_setAlphaBufferSize(QGLFormat* self, int size);
int QGLFormat_alphaBufferSize(const QGLFormat* self);
void QGLFormat_setStencilBufferSize(QGLFormat* self, int size);
int QGLFormat_stencilBufferSize(const QGLFormat* self);
void QGLFormat_setSampleBuffers(QGLFormat* self, bool enable);
bool QGLFormat_sampleBuffers(const QGLFormat* self);
void QGLFormat_setSamples(QGLFormat* self, int numSamples);
int QGLFormat_samples(const QGLFormat* self);
void QGLFormat_setSwapInterval(QGLFormat* self, int interval);
int QGLFormat_swapInterval(const QGLFormat* self);
bool QGLFormat_doubleBuffer(const QGLFormat* self);
void QGLFormat_setDoubleBuffer(QGLFormat* self, bool enable);
bool QGLFormat_depth(const QGLFormat* self);
void QGLFormat_setDepth(QGLFormat* self, bool enable);
bool QGLFormat_rgba(const QGLFormat* self);
void QGLFormat_setRgba(QGLFormat* self, bool enable);
bool QGLFormat_alpha(const QGLFormat* self);
void QGLFormat_setAlpha(QGLFormat* self, bool enable);
bool QGLFormat_accum(const QGLFormat* self);
void QGLFormat_setAccum(QGLFormat* self, bool enable);
bool QGLFormat_stencil(const QGLFormat* self);
void QGLFormat_setStencil(QGLFormat* self, bool enable);
bool QGLFormat_stereo(const QGLFormat* self);
void QGLFormat_setStereo(QGLFormat* self, bool enable);
bool QGLFormat_directRendering(const QGLFormat* self);
void QGLFormat_setDirectRendering(QGLFormat* self, bool enable);
bool QGLFormat_hasOverlay(const QGLFormat* self);
void QGLFormat_setOverlay(QGLFormat* self, bool enable);
int QGLFormat_plane(const QGLFormat* self);
void QGLFormat_setPlane(QGLFormat* self, int plane);
void QGLFormat_setOption(QGLFormat* self, int opt);
bool QGLFormat_testOption(const QGLFormat* self, int opt);
QGLFormat* QGLFormat_defaultFormat();
void QGLFormat_setDefaultFormat(QGLFormat* f);
QGLFormat* QGLFormat_defaultOverlayFormat();
void QGLFormat_setDefaultOverlayFormat(QGLFormat* f);
bool QGLFormat_hasOpenGL();
bool QGLFormat_hasOpenGLOverlays();
void QGLFormat_setVersion(QGLFormat* self, int major, int minor);
int QGLFormat_majorVersion(const QGLFormat* self);
int QGLFormat_minorVersion(const QGLFormat* self);
void QGLFormat_setProfile(QGLFormat* self, int profile);
int QGLFormat_profile(const QGLFormat* self);
int QGLFormat_openGLVersionFlags();
QGLFormat* QGLFormat_fromSurfaceFormat(QSurfaceFormat* format);
QSurfaceFormat* QGLFormat_toSurfaceFormat(QGLFormat* format);

void QGLFormat_delete(QGLFormat* self);

QGLContext* QGLContext_new(QGLFormat* format, QPaintDevice* device);
QGLContext* QGLContext_new2(QGLFormat* format);
bool QGLContext_create(QGLContext* self, QGLContext* shareContext);
bool QGLContext_isValid(const QGLContext* self);
bool QGLContext_isSharing(const QGLContext* self);
void QGLContext_reset(QGLContext* self);
bool QGLContext_areSharing(QGLContext* context1, QGLContext* context2);
QGLFormat* QGLContext_format(const QGLContext* self);
QGLFormat* QGLContext_requestedFormat(const QGLContext* self);
void QGLContext_setFormat(QGLContext* self, QGLFormat* format);
void QGLContext_moveToThread(QGLContext* self, QThread* thread);
void QGLContext_makeCurrent(QGLContext* self);
void QGLContext_doneCurrent(QGLContext* self);
void QGLContext_swapBuffers(const QGLContext* self);
void QGLContext_setTextureCacheLimit(int size);
int QGLContext_textureCacheLimit();
QPaintDevice* QGLContext_device(const QGLContext* self);
QColor* QGLContext_overlayTransparentColor(const QGLContext* self);
QGLContext* QGLContext_currentContext();
bool QGLContext_chooseContext(QGLContext* self, QGLContext* shareContext);

bool QGLContext_override_virtual_create(void* self, intptr_t slot);
bool QGLContext_virtualbase_create(void* self, QGLContext* shareContext);
bool QGLContext_override_virtual_makeCurrent(void* self, intptr_t slot);
void QGLContext_virtualbase_makeCurrent(void* self);
bool QGLContext_override_virtual_doneCurrent(void* self, intptr_t slot);
void QGLContext_virtualbase_doneCurrent(void* self);
bool QGLContext_override_virtual_swapBuffers(void* self, intptr_t slot);
void QGLContext_virtualbase_swapBuffers(const void* self);
bool QGLContext_override_virtual_chooseContext(void* self, intptr_t slot);
bool QGLContext_virtualbase_chooseContext(void* self, QGLContext* shareContext);

bool QGLContext_protectedbase_deviceIsPixmap(bool* _dynamic_cast_ok, const void* self);
bool QGLContext_protectedbase_windowCreated(bool* _dynamic_cast_ok, const void* self);
void QGLContext_protectedbase_setWindowCreated(bool* _dynamic_cast_ok, void* self, bool on);
bool QGLContext_protectedbase_initialized(bool* _dynamic_cast_ok, const void* self);
void QGLContext_protectedbase_setInitialized(bool* _dynamic_cast_ok, void* self, bool on);
unsigned int QGLContext_protectedbase_colorIndex(bool* _dynamic_cast_ok, const void* self, QColor* c);
void QGLContext_protectedbase_setValid(bool* _dynamic_cast_ok, void* self, bool valid);
void QGLContext_protectedbase_setDevice(bool* _dynamic_cast_ok, void* self, QPaintDevice* pDev);

void QGLContext_delete(QGLContext* self);

QGLWidget* QGLWidget_new(QWidget* parent);
QGLWidget* QGLWidget_new2();
QGLWidget* QGLWidget_new3(QGLContext* context);
QGLWidget* QGLWidget_new4(QGLFormat* format);
QGLWidget* QGLWidget_new5(QWidget* parent, QGLWidget* shareWidget);
QGLWidget* QGLWidget_new6(QWidget* parent, QGLWidget* shareWidget, int f);
QGLWidget* QGLWidget_new7(QGLContext* context, QWidget* parent);
QGLWidget* QGLWidget_new8(QGLContext* context, QWidget* parent, QGLWidget* shareWidget);
QGLWidget* QGLWidget_new9(QGLContext* context, QWidget* parent, QGLWidget* shareWidget, int f);
QGLWidget* QGLWidget_new10(QGLFormat* format, QWidget* parent);
QGLWidget* QGLWidget_new11(QGLFormat* format, QWidget* parent, QGLWidget* shareWidget);
QGLWidget* QGLWidget_new12(QGLFormat* format, QWidget* parent, QGLWidget* shareWidget, int f);
void QGLWidget_virtbase(QGLWidget* src, QWidget** outptr_QWidget);
QMetaObject* QGLWidget_metaObject(const QGLWidget* self);
void* QGLWidget_metacast(QGLWidget* self, const char* param1);
struct miqt_string QGLWidget_tr(const char* s);
struct miqt_string QGLWidget_trUtf8(const char* s);
void QGLWidget_qglColor(const QGLWidget* self, QColor* c);
void QGLWidget_qglClearColor(const QGLWidget* self, QColor* c);
bool QGLWidget_isValid(const QGLWidget* self);
bool QGLWidget_isSharing(const QGLWidget* self);
void QGLWidget_makeCurrent(QGLWidget* self);
void QGLWidget_doneCurrent(QGLWidget* self);
bool QGLWidget_doubleBuffer(const QGLWidget* self);
void QGLWidget_swapBuffers(QGLWidget* self);
QGLFormat* QGLWidget_format(const QGLWidget* self);
void QGLWidget_setFormat(QGLWidget* self, QGLFormat* format);
QGLContext* QGLWidget_context(const QGLWidget* self);
void QGLWidget_setContext(QGLWidget* self, QGLContext* context);
QPixmap* QGLWidget_renderPixmap(QGLWidget* self);
QImage* QGLWidget_grabFrameBuffer(QGLWidget* self);
void QGLWidget_makeOverlayCurrent(QGLWidget* self);
QGLContext* QGLWidget_overlayContext(const QGLWidget* self);
QImage* QGLWidget_convertToGLFormat(QImage* img);
void QGLWidget_renderText(QGLWidget* self, int x, int y, struct miqt_string str);
void QGLWidget_renderText2(QGLWidget* self, double x, double y, double z, struct miqt_string str);
QPaintEngine* QGLWidget_paintEngine(const QGLWidget* self);
void QGLWidget_updateGL(QGLWidget* self);
void QGLWidget_updateOverlayGL(QGLWidget* self);
bool QGLWidget_event(QGLWidget* self, QEvent* param1);
void QGLWidget_initializeGL(QGLWidget* self);
void QGLWidget_resizeGL(QGLWidget* self, int w, int h);
void QGLWidget_paintGL(QGLWidget* self);
void QGLWidget_initializeOverlayGL(QGLWidget* self);
void QGLWidget_resizeOverlayGL(QGLWidget* self, int w, int h);
void QGLWidget_paintOverlayGL(QGLWidget* self);
void QGLWidget_paintEvent(QGLWidget* self, QPaintEvent* param1);
void QGLWidget_resizeEvent(QGLWidget* self, QResizeEvent* param1);
void QGLWidget_glInit(QGLWidget* self);
void QGLWidget_glDraw(QGLWidget* self);
struct miqt_string QGLWidget_tr2(const char* s, const char* c);
struct miqt_string QGLWidget_tr3(const char* s, const char* c, int n);
struct miqt_string QGLWidget_trUtf82(const char* s, const char* c);
struct miqt_string QGLWidget_trUtf83(const char* s, const char* c, int n);
void QGLWidget_setContext2(QGLWidget* self, QGLContext* context, QGLContext* shareContext);
void QGLWidget_setContext3(QGLWidget* self, QGLContext* context, QGLContext* shareContext, bool deleteOldContext);
QPixmap* QGLWidget_renderPixmapWithInt(QGLWidget* self, int w);
QPixmap* QGLWidget_renderPixmap2(QGLWidget* self, int w, int h);
QPixmap* QGLWidget_renderPixmap3(QGLWidget* self, int w, int h, bool useContext);
QImage* QGLWidget_grabFrameBufferWithWithAlpha(QGLWidget* self, bool withAlpha);
void QGLWidget_renderText3(QGLWidget* self, int x, int y, struct miqt_string str, QFont* fnt);
void QGLWidget_renderText4(QGLWidget* self, double x, double y, double z, struct miqt_string str, QFont* fnt);

bool QGLWidget_override_virtual_paintEngine(void* self, intptr_t slot);
QPaintEngine* QGLWidget_virtualbase_paintEngine(const void* self);
bool QGLWidget_override_virtual_updateGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_updateGL(void* self);
bool QGLWidget_override_virtual_updateOverlayGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_updateOverlayGL(void* self);
bool QGLWidget_override_virtual_event(void* self, intptr_t slot);
bool QGLWidget_virtualbase_event(void* self, QEvent* param1);
bool QGLWidget_override_virtual_initializeGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_initializeGL(void* self);
bool QGLWidget_override_virtual_resizeGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_resizeGL(void* self, int w, int h);
bool QGLWidget_override_virtual_paintGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_paintGL(void* self);
bool QGLWidget_override_virtual_initializeOverlayGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_initializeOverlayGL(void* self);
bool QGLWidget_override_virtual_resizeOverlayGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_resizeOverlayGL(void* self, int w, int h);
bool QGLWidget_override_virtual_paintOverlayGL(void* self, intptr_t slot);
void QGLWidget_virtualbase_paintOverlayGL(void* self);
bool QGLWidget_override_virtual_paintEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_paintEvent(void* self, QPaintEvent* param1);
bool QGLWidget_override_virtual_resizeEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_resizeEvent(void* self, QResizeEvent* param1);
bool QGLWidget_override_virtual_glInit(void* self, intptr_t slot);
void QGLWidget_virtualbase_glInit(void* self);
bool QGLWidget_override_virtual_glDraw(void* self, intptr_t slot);
void QGLWidget_virtualbase_glDraw(void* self);
bool QGLWidget_override_virtual_devType(void* self, intptr_t slot);
int QGLWidget_virtualbase_devType(const void* self);
bool QGLWidget_override_virtual_setVisible(void* self, intptr_t slot);
void QGLWidget_virtualbase_setVisible(void* self, bool visible);
bool QGLWidget_override_virtual_sizeHint(void* self, intptr_t slot);
QSize* QGLWidget_virtualbase_sizeHint(const void* self);
bool QGLWidget_override_virtual_minimumSizeHint(void* self, intptr_t slot);
QSize* QGLWidget_virtualbase_minimumSizeHint(const void* self);
bool QGLWidget_override_virtual_heightForWidth(void* self, intptr_t slot);
int QGLWidget_virtualbase_heightForWidth(const void* self, int param1);
bool QGLWidget_override_virtual_hasHeightForWidth(void* self, intptr_t slot);
bool QGLWidget_virtualbase_hasHeightForWidth(const void* self);
bool QGLWidget_override_virtual_mousePressEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
bool QGLWidget_override_virtual_mouseReleaseEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
bool QGLWidget_override_virtual_mouseDoubleClickEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
bool QGLWidget_override_virtual_mouseMoveEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
bool QGLWidget_override_virtual_wheelEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_wheelEvent(void* self, QWheelEvent* event);
bool QGLWidget_override_virtual_keyPressEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
bool QGLWidget_override_virtual_keyReleaseEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
bool QGLWidget_override_virtual_focusInEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_focusInEvent(void* self, QFocusEvent* event);
bool QGLWidget_override_virtual_focusOutEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
bool QGLWidget_override_virtual_enterEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_enterEvent(void* self, QEvent* event);
bool QGLWidget_override_virtual_leaveEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_leaveEvent(void* self, QEvent* event);
bool QGLWidget_override_virtual_moveEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_moveEvent(void* self, QMoveEvent* event);
bool QGLWidget_override_virtual_closeEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_closeEvent(void* self, QCloseEvent* event);
bool QGLWidget_override_virtual_contextMenuEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* event);
bool QGLWidget_override_virtual_tabletEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_tabletEvent(void* self, QTabletEvent* event);
bool QGLWidget_override_virtual_actionEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_actionEvent(void* self, QActionEvent* event);
bool QGLWidget_override_virtual_dragEnterEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
bool QGLWidget_override_virtual_dragMoveEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
bool QGLWidget_override_virtual_dragLeaveEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
bool QGLWidget_override_virtual_dropEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_dropEvent(void* self, QDropEvent* event);
bool QGLWidget_override_virtual_showEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_showEvent(void* self, QShowEvent* event);
bool QGLWidget_override_virtual_hideEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QGLWidget_override_virtual_nativeEvent(void* self, intptr_t slot);
bool QGLWidget_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
bool QGLWidget_override_virtual_changeEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_changeEvent(void* self, QEvent* param1);
bool QGLWidget_override_virtual_metric(void* self, intptr_t slot);
int QGLWidget_virtualbase_metric(const void* self, int param1);
bool QGLWidget_override_virtual_initPainter(void* self, intptr_t slot);
void QGLWidget_virtualbase_initPainter(const void* self, QPainter* painter);
bool QGLWidget_override_virtual_redirected(void* self, intptr_t slot);
QPaintDevice* QGLWidget_virtualbase_redirected(const void* self, QPoint* offset);
bool QGLWidget_override_virtual_sharedPainter(void* self, intptr_t slot);
QPainter* QGLWidget_virtualbase_sharedPainter(const void* self);
bool QGLWidget_override_virtual_inputMethodEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QGLWidget_override_virtual_inputMethodQuery(void* self, intptr_t slot);
QVariant* QGLWidget_virtualbase_inputMethodQuery(const void* self, int param1);
bool QGLWidget_override_virtual_focusNextPrevChild(void* self, intptr_t slot);
bool QGLWidget_virtualbase_focusNextPrevChild(void* self, bool next);
bool QGLWidget_override_virtual_eventFilter(void* self, intptr_t slot);
bool QGLWidget_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
bool QGLWidget_override_virtual_timerEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_timerEvent(void* self, QTimerEvent* event);
bool QGLWidget_override_virtual_childEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_childEvent(void* self, QChildEvent* event);
bool QGLWidget_override_virtual_customEvent(void* self, intptr_t slot);
void QGLWidget_virtualbase_customEvent(void* self, QEvent* event);
bool QGLWidget_override_virtual_connectNotify(void* self, intptr_t slot);
void QGLWidget_virtualbase_connectNotify(void* self, QMetaMethod* signal);
bool QGLWidget_override_virtual_disconnectNotify(void* self, intptr_t slot);
void QGLWidget_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);

void QGLWidget_protectedbase_setAutoBufferSwap(bool* _dynamic_cast_ok, void* self, bool on);
bool QGLWidget_protectedbase_autoBufferSwap(bool* _dynamic_cast_ok, const void* self);
void QGLWidget_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QGLWidget_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QGLWidget_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QGLWidget_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QGLWidget_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QGLWidget_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QGLWidget_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QGLWidget_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QGLWidget_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);

void QGLWidget_delete(QGLWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
